Feature/bot base application
Studio-Yandex-Practicum/ask_nenaprasno_bot pull request #1
Opened 2022-06-10 09:43 UTC by Danielseddian

Собрал основу под бота и несколько инструментов в tools:
os_tools: инструменты на основе os - BASE_DIR (доступ к корневой директории), get_secret (для доступа к .env)
logger: для настройки логирования, принимает имя и уровень логирования (для указания уровня логирования следует запустить его прежде других инструментов
bot: два метода для запуска бота - init_webhook (асинхронный метод) и init_pooling (классический метод для случаев, когда требуется запуск бота в pooling режиме

2022-06-11 10:16 UTC, AntonZelinsky requested changes
Денис, посмотри бот который мы разрабатывали на этой библиотеке, только на старой версии. Он не идеален, но есть много вещей, к которым стоит стремиться
https://github.com/ProCharity/ProCharity_bot

2022-06-11 10:16 UTC, AntonZelinsky commented on requirements.txt
> +python-telegram-bot==20.0a0
Они сегодня выкатили новый релиз, нужно сразу обновить все зависимости.
https://github.com/python-telegram-bot/python-telegram-bot/releases/tag/v20.0a1

2022-06-11 10:16 UTC, AntonZelinsky commented on config.py
> +if path.exists(env_path := path.join(BASE_DIR, ".env")):
Ты сначала импортировал pathlib, а потом использовал os библиотеку. Она считается устаревшей и менее производительной. Всё должно быть на pathlib!
Если этого файла нет, то приложение упадёт на следуйщей строке, что в принципе окей, нечего запускаться без конфигураций.

2022-06-11 10:16 UTC, AntonZelinsky commented on config.py
> +if not (get_secret := None):
Что это и зачем?

2022-06-11 10:16 UTC, AntonZelinsky commented on tools/bot.py
> +    starlette_app = Starlette(
Запуск сервера должен быть в отдельном файле, так как если ты захочешь положить приложение в докер контейнер, то будешь запускать не uvicorn докера, а просто вызывать команду запуска питон файла. Это очень большой антипаттерн.

Да и скорее всего, наше приложение будет писаться не в одном файле, поэтому, сразу лучше его разнести

2022-06-11 10:16 UTC, AntonZelinsky commented on tools/__init__.py
> +from tools.bot import init_webhook, init_pooling
Почему папка тулс, а в ней бот? Давай пока всё на одном уровне будет лежать, а потом подумаем как лучше разбить

2022-06-11 10:16 UTC, AntonZelinsky commented on config.py
> +def get_logger(name: str = __name__, level: str = "INFO"):
Должен вызываться метод конфигурирующий логи, настраивающий папки вывода, формат, уровни и всё.
Получение логгеров  для логирования должно быть стандартное, питонячье `logging.getLogger(),` только там где нужно.
Подобную логику мы реализовывали в этом проекте и получилось, что выстрелили себе в ногу — https://github.com/ProCharity/ProCharity_bot/blob/develop/app/logger.py .
А тут, мы пошли вторым путём и он делает как раз то что нужно — https://github.com/Studio-Yandex-Practicum/Lubimovka_backend/tree/develop/config/logging.

Позже, нужно будет реализовать подобную систему, как делали в этих проектах, чтобы логи ошибок слаживались в одну папку, а все остальные логи в другую. Плюс, ещё чтобы была ротация файлов и архивирование старых файлов. 
Это уже как стандарт работы. 

Сейчас, достаточно сделать минимальное конфигурирование логера и проверить, что он работает.

2022-06-11 10:16 UTC, AntonZelinsky commented on tools/bot.py
> +            app.add_handler(handler(*params))
Ой, это мега усложнение, просто добавить в апликейшен нужные хэндлеры  и всё, как было в том примере, как в [этом](https://github.com/python-telegram-bot/python-telegram-bot/blob/master/examples/conversationbot2.py). Два `for,` это сломать мозг можно.
Придерживайся принципа KISS!

2022-06-11 10:16 UTC, AntonZelinsky commented on config.py
> +TOKEN = getenv("TELEGRAM_TOKEN")
Если ты уже установил `dotenv`, то может его и придерживаться? А то много всего намешено

2022-06-11 12:36 UTC, Danielseddian commented on config.py
> +def get_logger(name: str = __name__, level: str = "INFO"):
Интересненько :) Поизучаю тогда, а пока сделаю ПР без нее

2022-06-11 12:51 UTC, Danielseddian commented on config.py
> +TOKEN = getenv("TELEGRAM_TOKEN")
Не совсем понял, не вижу в dotenv метода для доступа к переменным окружения (аналога getenv), вместо этого воспользуюсь тогда методом dotenv_values()

2022-06-12 21:34 UTC, veselij commented on requirements.txt
> +python-telegram-bot==20.0a0
Денис, посмотри еще у себя лишние зависимости в файле requirements - там откуда Django взялась и еще пара библиотек лишних

2022-06-12 21:51 UTC, veselij requested changes
привет,
в целом уже стало лучше. но есть над чем еще поработать.
я предлагаю такую структуру сделать

В корне сделать папочку - бот-сервис и туда перенести все файлы. На рут уровне оставить README, попку бот-сервис и папку Docs
В папочек бота создать папку src
В итоге чтобы получилось, что то вида

README.md
Docs/
Bot/
	.env.sample -надо добавить пример
	requirements.txt
	src/
		core/
			config.py
			logger.py
		main.py
		bot.py
		server.py

В README неплохо бы описать какие варианты запуска есть, и как их произвести,
Python Main.py - запуск в режиме webhook
Python bot.py -  запуск в режиме pooling

2022-06-12 21:51 UTC, veselij commented on bot.py
> +    app = Application.builder().updater(None).token(config.TOKEN).build()
у тебя в этих местах дублирование, кода, я бы предложил вынести в 1 функцию создание Бота с навешивающем хендлеров. в инитах вызывать ее чтобы получить бота и запускать. с вебхуком я бы сделал асинк контекст менеджер, чтобы останавливать бота (когда например старите остановится)

2022-06-12 21:51 UTC, veselij commented on bot.py
> +    return app
а бы добавил запуск пулинга через __main__
if __name__ == "__main__":
    init_pooling()

2022-06-12 21:51 UTC, veselij commented on config.py
> +VARS = dotenv_values(BASE_DIR/".env")
предлагаю использовать пайдантик для менеджмента настроек (https://pydantic-docs.helpmanual.io/usage/settings/), тогда не надо будет конвертировать в int и т.п. и если какие-то данные отсутствуют в конфетах, то мы сразу об этом узнаем.

2022-06-12 21:51 UTC, veselij commented on main.py
> +async def main():
всю логику вьюх и раутов предлагаю вынести в отдельный модуль server.py чтобы в main оставить только запуск сервиса

2022-06-12 21:51 UTC, veselij commented on main.py
> +    webserver = uvicorn.Server(
аналогично как с ботом, сделать запуск в __main__, чтобы это работало только когда запускаем локально (не в докере). Так как в докере будем запускать через внешний менеджер Gunicorn

2022-06-12 21:51 UTC, veselij commented on main.py
> +    async with app:
нам надо бы по хорошему запускать старите приложение только и на его старте запускать бота. можно посмотреть в эту сторону https://www.starlette.io/events/

2022-06-12 21:51 UTC, veselij commented on main.py
> +    import asyncio
тут нужен запуск старлета через увикорн для отладки со стартап запуском бота

2022-06-12 21:51 UTC, veselij commented on requirements.txt
> +Django==4.0.5
проверь пожалуйста на лишение зависимости

2022-06-13 09:51 UTC, AntonZelinsky commented
@veselij 

> я предлагаю такую структуру сделать
> 
> В корне сделать папочку - бот-сервис и туда перенести все файлы. На рут уровне оставить README, попку бот-сервис и папку Docs
> В папочек бота создать папку src
> В итоге чтобы получилось, что то вида
> 
> README.md
> Docs/
> Bot/
> .env.sample -надо добавить пример
> requirements.txt
> src/
> core/
> config.py
> logger.py
> main.py
> bot.py
> server.py
> 
> В README неплохо бы описать какие варианты запуска есть, и как их произвести,
> Python Main.py - запуск в режиме webhook
> Python bot.py - запуск в режиме pooling

Предлагаю файлы запуска назвать в соответствии с тем, что они будут делать: run_bot и run_application (запуск бота и ). Папка Bot и файл bot.py на одном уровне, это очень плохая идея. И в чём разница между паками Bot, src и core? давайте пока в папки не выделять ничего, так как не до конца понятна архитектура, а спланировать уже сейчас папки — это будет оверхедом.
main.py — это худшее название которое можно придумать. Не стоит такое название вообще использовать, если нет какой-то определённой причины.
bot.py и server.py хорошие названия, бот в папку точно перерастёт

2022-06-13 09:54 UTC, veselij commented
Там форматирование съехало видимо. Имелось ввиду как на картинке![image](https://user-images.githubusercontent.com/23584808/173328535-e4a9b182-8947-4814-ac30-673f6ee75009.jpeg)

2022-06-13 10:14 UTC, Danielseddian commented on requirements.txt
> +python-telegram-bot==20.0a0
Оставил только python-telegram-bot, starlette и uvicorn, по идее, остальные библиотеки доставляются, как придаток к этим (устанавливаются совместно).

2022-06-13 18:29 UTC, AntonZelinsky requested changes

2022-06-13 18:29 UTC, AntonZelinsky commented on Bot/src/core/config.py
> +HOST = (s := Settings()).host
Предлагаю не использовать эту конструкцию в коде, она только усложняет понимание кода и если посмотреть через дизассемблер на эту конструкцию, то код становится на 3 команды больше и сложнее.
Так код выглядит значительно лучше, не считая очень плохого названия переменной
```suggestion
s = Settings()
HOST = s.host
```
Это очень плохой пример синтаксического сахара, который только ухудшает восприятие кода.
Эта конструкция первая в списке на добавление в документацию как плохие практики

2022-06-13 18:29 UTC, AntonZelinsky commented on .gitignore
> +tools/private.key
Чувствую, это не нужно игнорить, это какие-то твои личные игноры

2022-06-13 18:29 UTC, AntonZelinsky commented on Bot/src/bot.py
> +    app = (Application.builder() if webhook else ApplicationBuilder()).token(config.TOKEN).build()
Слишком сложно!
```
appBuilder = Application.builder().token(config.TOKEN) #не знаю, нужен тут builder или нет, в одних местах твоего когд использовался, а в других уже нет
if(use_webhook):
    appBuilder.updater(None)
app = appBuilder.build()
...
return app
```

2022-06-13 18:29 UTC, AntonZelinsky commented on Bot/src/server.py
> +            yield
А зачем это всё? `await bot_app.bot.set_webhook(url=f"{config.WEBHOOK_URL}/telegram")` нужно взывать ведь всего один раз. 
Когда вызывается этот метод, он сообщает телеграму, что на таком домене ждут запросы от него, и он сразу начинает слать сюда запросы. Подозреваю, что даже если сервер ещё не запущен, запрос будет отправляться несколько раз, в течении нескольких секунд и застанет сервер запущенным. Если нужно на 100% быть в этом уверенными, то тогда лучше использовать `on_startup` [событие](https://www.starlette.io/events/) сервера, а не контекстный менеджер.
Почитал для чего нужен lifespan и выглядит так, он нужен для того, чтобы, по сути, была вторая сущность приложения, но функция которую ты запускаешь, делает один hhtp запрос и завершает свою работу. Это имело бы смысл, если бы тебе нужно было запустить бота как пулинг. Мне так кажется.)

2022-06-13 19:02 UTC, veselij commented on Bot/src/server.py
> +            yield
Антон, посмотри, пожалуйста, как сейчас сделано, я так посоветовал, lifespan = выполняет перед запуском on_startup и потом shutdown (после остановки старлета) как я понял. контекстный менеджер, чтобы после shutdown корректно завершить бота. по идее можно наверное забить на корректное завершение? и просто использовать on_startup и там запустить бота, но мне показалось это как то неправильным. как думаешь лучше? по другому как запустить бота в принципе не придумал, может есть другие идеи?

2022-06-13 19:55 UTC, AntonZelinsky commented on Bot/src/server.py
> +            yield
С того что я вижу в [документации](https://www.starlette.io/events/) и коде, эта штука делает вовсе не то что ты думаешь.
![image](https://user-images.githubusercontent.com/1431279/173432947-ec959e18-4c18-4b75-9da0-20c93f6e67fd.png)
![image](https://user-images.githubusercontent.com/1431279/173433610-858f29d7-a130-4e59-959a-303fce47bca9.png)
Он выполняет то что тебе нужно, но это не значит, что он для этого предназначен. По-хорошему, поставь точку остановки приложения внутри этого контекстного метода и внутри ран_бот (не беру в учёт последний комит, там немного поменялось, но не структорно всё то же самое) и посмотри сколько раз он вызывается, у меня есть подозрения, что не один раз.
Перечитай мой комент выше.

2022-06-13 20:13 UTC, AntonZelinsky commented on Bot/src/main.py
> +app = Starlette(routes=routes, lifespan=manage_bot)
Предлагаю файл сервер и мэйн (дурацкое название, уже говорил об этом) совместить в один, только от контекстного менеджера избавиться, а вместо его использовать hook `on_startup`.
Кстати, что это такое и зачем? `app.state.bot = bot` я ни в одном из примеров не видел подобного. Что точно нужно?

И ты опять потерял файл run_bot, третий раз пишу про это! Больше не буду, просто скажу на доработку.

Вообще, перечитай все фидбеки, внимательно перечитай, там очень много хороших идей!

2022-06-14 06:03 UTC, veselij commented on Bot/src/server.py
> +            yield
я поигрался с break points, работает так, один раз перед стартом сервера вызывается bot.start(), и после выключения сервера 1 раз bot.stop(), т.е. работает как будто отдельные on_startup и shutdown завел. только через одну функцию.
Антон у тебя были сомнения, что перед каждым реквестом это срабатывает? как милдваре?

2022-06-14 06:05 UTC, veselij commented on Bot/src/main.py
> +app = Starlette(routes=routes, lifespan=manage_bot)
app.state.bot = bot это нам надо, чтобы мы потом во View могли получить доступ к боту через 

`async def telegram(request: Request) -> Response:
    await request.app.state.bot.update_queue.put(
        Update.de_json(data=await request.json(), bot=request.app.state.bot.bot)
    )
    return Response()`

https://www.starlette.io/applications/#storing-state-on-the-app-instance

2022-06-14 11:18 UTC, AntonZelinsky commented on Bot/src/main.py
> +app = Starlette(routes=routes, lifespan=manage_bot)
Со `app.state.bot` абсолютно неочевидный интерфейс, глобального объекта в рамках апи. Окей, если так нужно, то пусть так и будет, но добавь комментарий описывающий, что это значит и зачем это нужно, а так же, в методе хэлз вызови какой-нибудь метод бота, на примрем получение статистики или информации о пользователе. Это будет иллюстрировать пример работы с ботом и не будет возникать сложностей с пониманием `app.state.bot` .

Предлагаю переменную `app = Starlette` назвать апи! Так как апп используется много где в приложении до этого и путает, а так, будет на 100% понтно что это и зачем.

2022-06-14 11:37 UTC, AntonZelinsky commented on Bot/src/server.py
> +            yield
Окей, понял как это работает, но всё равно, давай мы не будем использовать контекстный менеджер. Если тебе нужно запустить и остановить бота, то переопредели два соответствующих метода. Это будет намного очевиднее. Я понимаю, что в питоне есть такой паттерн, но он сложнее в понимании и не несёт каких-то дополнительных плюшек, к тому же, он написан не как класс, а как метод с кучей `async with` и `yield`, что уже начинает быть сложным для понимания.
Поэтому, предлагаю сделать как проще. Всё равно, эти два метода станут контекстным менеджером под капотом бота

2022-06-14 12:38 UTC, veselij commented on Bot/src/main.py
> +app = Starlette(routes=routes, lifespan=manage_bot)
Да, мне тоже не понравилось. Но я больше никак не смог придумать как скрестить с ювикорном и запуск бота и сервера. У вас с Матвеем может есть идеи как это сделать более очевидно?

2022-06-14 13:40 UTC, AntonZelinsky commented on Bot/src/main.py
> +app = Starlette(routes=routes, lifespan=manage_bot)
Пусть так остаётся, будем потом думать. Сейчас, важно поправить все фидбеки про которые писал выше.

2022-06-14 22:49 UTC, AntonZelinsky approved these changes

2022-06-14 22:49 UTC, AntonZelinsky commented on Bot/src/run_webhook_api.py
> +    await bot_app.start()
Ой, а зачем ты вызываешь тут старт? Это же команда для пользователей, отправляющая сообщение

2022-06-14 22:49 UTC, AntonZelinsky commented on Bot/src/core/config.py
> +ENVS = dotenv_values()
Выглядит так, как будто это константа. Не соответствие pep8!
Всё таки, `os.getenv("HOST")` выглядит лучше, чем `ENVS["HOST"]`
Хотя залез в код этой библиотеки и значения можно получать `env.get("HOST")`, давай на это и заменим.

2022-06-14 22:49 UTC, AntonZelinsky commented on Bot/requirements.txt
> +pydantic==1.9.1
Мы же вроде как отказались от пидантика?

2022-06-15 08:20 UTC, veselij commented on Bot/src/run_webhook_api.py
> +    await bot_app.start()
Start запускает бэкграунд такск, который фетчит данные из update. 
run_webhook под капотом тоже ее запускает. 

a background task that fetches updates from update_queue and processes them.

https://docs.python-telegram-bot.org/telegram.ext.application.html

2022-06-15 11:07 UTC, AntonZelinsky approved these changes
Поправь, пожалуйста, последний фибек и можешь мержить ПР

2022-06-15 11:07 UTC, AntonZelinsky commented on Bot/src/bot.py
> +    await bot_app.bot.set_webhook(url=f"{config.WEBHOOK_IP}/telegram")
Тут же должен быть урл? Либо статический внешний ip, что вызывает множество сложностей. К тому же, на одном ip могут быть множество серверов.

Замени тут на URL и добавь, пожалуйста, в 2 строчки интсрукцию, как запустить на веб хуках:
* Запустить ngrok такой командой
* Урл скопировать в конфиг
* Запустить команду

2022-06-15 13:43 UTC, merged