Daily notifications fixed
Studio-Yandex-Practicum/ask_nenaprasno_bot pull request #101
Opened 2022-08-21 09:28 UTC by AleKuligin

Проверен и скорректирован функционал:
бот каждое утро получает все задачи которые истекают сегодня или истекли. Фильтрует их- выбирает те, которые истекут сегодня и ставит одно напоминание на время равное времени истечения +1 час.
Исключена константа DAYLY_COLLECT_CONSULTATIONS_TIME, ежедневная задача по сбору просроченных заявок запускается в то же время, в которое был запущен бот.

2022-08-21 10:11 UTC, veselij requested changes

2022-08-21 10:11 UTC, veselij commented on .env.example
> +SITE_API_BOT_TOKEN=7HGRpR3z29wQr01B                             # Токен(uuid) для идентификации бота на сайте.
не надо в гит заливать токены

2022-08-21 10:11 UTC, veselij commented on src/jobs.py
> +            data = (
а зачем лишняя переменая

2022-08-21 10:11 UTC, veselij commented on src/bot.py
> +        overdue_reminder_job, time=datetime.utcnow().time(), name=DAILY_CONSULTATIONS_REMINDER_JOB
надо запускать как было в 0:00 иначе если ты запустишь бота в 23:00, то потеряешь все напоминания

2022-08-21 18:48 UTC, AleKuligin commented on src/jobs.py
> +            data = (
выделял для дальнейшего сравнения с уже поставленными задачами, чтобы исключить дубликаты, но потом поменял подход, а переменную обратно не вернул. Исправлю.

2022-08-21 18:48 UTC, AleKuligin commented on .env.example
> +SITE_API_BOT_TOKEN=7HGRpR3z29wQr01B                             # Токен(uuid) для идентификации бота на сайте.
ок

2022-08-21 18:50 UTC, AleKuligin commented on src/bot.py
> +        overdue_reminder_job, time=datetime.utcnow().time(), name=DAILY_CONSULTATIONS_REMINDER_JOB
кстати, если логика должна быть именно такой, то надо сразу в код заложить запуск в 00:00 и не давать возможности менять этот параметр через переменную окружения.

2022-08-23 18:27 UTC, veselij approved these changes

2022-08-23 18:27 UTC, merged