ver 1
Studio-Yandex-Practicum/ask_nenaprasno_bot pull request #104
Opened 2022-08-22 20:36 UTC by xrito

2022-08-24 09:49 UTC, veselij requested changes

2022-08-24 09:49 UTC, veselij commented on .env.example
> +DAILY_REMINDER_FOR_OVERDUE_CONSULTATIONS=9:00                   # время ежедневного получения заявок утром
на 17-00 попросили поменять

2022-08-24 09:49 UTC, veselij commented on src/jobs.py
> +        time_remind = datetime.strptime(consultation.due, DATE_FORMAT)
а зачем переименовал, due_time больше подходит

2022-08-24 09:49 UTC, veselij commented on src/jobs.py
>          return False
return due_time.date() <= date.today()

2022-08-24 09:49 UTC, veselij commented on src/jobs.py
> +                data=(
давай еще сюда передовать сообещние с плэйсхолдерами. так как текст у нас все-таки меняется немного, и мы не можем просто заккоментировать

2022-08-24 15:07 UTC, xrito commented on .env.example
> +DAILY_REMINDER_FOR_OVERDUE_CONSULTATIONS=9:00                   # время ежедневного получения заявок утром
ок, поменяю

2022-08-24 15:07 UTC, xrito commented on src/jobs.py
> +        time_remind = datetime.strptime(consultation.due, DATE_FORMAT)
хорошо верну, первоначально был time_remind

2022-08-24 15:11 UTC, xrito commented on src/jobs.py
> +                data=(
так понимаю речь идет о закоментированной строчке # "Час прошел, а наша надежда - нет 😃\n" ?

2022-08-26 09:50 UTC, veselij requested changes

2022-08-26 09:50 UTC, veselij commented on .env.example
> +# DAYLY_COLLECT_CONSULTATIONS_TIME=00:00                        # время ежедневного получения истекающих заявок  захардкодиkb через конфиг, без env
удали тогда отсюда совсем

2022-08-26 09:50 UTC, veselij commented on src/jobs.py
>          user_expired = await APIService().get_user_expired_consultations(telegram_id)
сделай пожалуйста сначала созание APIService. а потом у нее вызывай 2 метода, иначе создаешь два раза объект в памяти

2022-08-26 09:50 UTC, veselij commented on src/jobs.py
> +        return due_time.date() <= date.today()
какая-то муть получилась)) что мы тут хотим проверить, что дата или сегодня или вчера, тогда достаточно место трех строк сделать одну return due_time.date() <= date.today()

2022-08-26 09:50 UTC, veselij commented on src/jobs.py
>              "(https://ask.nenaprasno.ru/doctor/consultation/"
id заявки надо в url добавить

2022-08-26 09:50 UTC, veselij commented on src/jobs.py
> +                data=(
текст лучше полностью вынести, так как еще что то в нем поменяться может

2022-08-26 12:16 UTC, xrito commented on .env.example
> +# DAYLY_COLLECT_CONSULTATIONS_TIME=00:00                        # время ежедневного получения истекающих заявок  захардкодиkb через конфиг, без env
ок

2022-08-26 13:23 UTC, xrito commented on .env.example
> +# DAYLY_COLLECT_CONSULTATIONS_TIME=00:00                        # время ежедневного получения истекающих заявок  захардкодиkb через конфиг, без env
ок

2022-08-26 13:25 UTC, xrito commented on src/jobs.py
>              "(https://ask.nenaprasno.ru/doctor/consultation/"
ок

2022-08-26 13:28 UTC, xrito commented on src/jobs.py
> +        return due_time.date() <= date.today()
да наверное неправльно понял из за коментария

2022-08-26 15:23 UTC, xrito commented on src/jobs.py
>          user_expired = await APIService().get_user_expired_consultations(telegram_id)
ок

2022-08-26 15:23 UTC, xrito commented on src/jobs.py
> +                data=(
а куда лучше текст сообщения вынести? в daily_consulations_reminder_job?

2022-08-28 15:37 UTC, AntonZelinsky approved these changes

2022-08-28 15:37 UTC, AntonZelinsky commented on src/core/config.py
> +DAYLY_COLLECT_CONSULTATIONS_TIME = time(hour=0, minute=0, tzinfo=timezone.utc)
Полагаю, этот комментарий по окончании разработки должен быть удалён

2022-08-28 15:37 UTC, AntonZelinsky commented on src/jobs.py
> +            f"(https://ask.nenaprasno.ru/doctor/consultation/{consultation_id})"
Я в этом [ПРе](https://github.com/Studio-Yandex-Practicum/ask_nenaprasno_bot/pull/110#discussion_r956743625) отписался как должны выглядеть ссылки на заявку, поправь, пожалуйста, тут ссылку

2022-08-28 15:37 UTC, AntonZelinsky commented on src/jobs.py
>      consultation = await APIService().get_consultation(consultation_id)
В этом файле много раз создаётся экземпляр класса `APIService,` я предлагаю сделать один раз вверху, а не тратить время и память создание `APIService`

2022-08-28 16:42 UTC, xrito commented on src/core/config.py
> +DAYLY_COLLECT_CONSULTATIONS_TIME = time(hour=0, minute=0, tzinfo=timezone.utc)
+

2022-08-28 16:42 UTC, xrito commented on src/core/config.py
> +DAYLY_COLLECT_CONSULTATIONS_TIME = time(hour=0, minute=0, tzinfo=timezone.utc)
удалил сразу

2022-08-28 16:46 UTC, xrito commented on src/jobs.py
>      consultation = await APIService().get_consultation(consultation_id)
сделал

2022-08-28 16:53 UTC, xrito commented on src/jobs.py
> +            f"(https://ask.nenaprasno.ru/doctor/consultation/{consultation_id})"
ок

2022-08-28 23:06 UTC, merged

2022-08-29 13:06 UTC, malyshevadv commented
Не были внесены соответствующие изменения в фал .github\workflows\deploy.yaml для добавления переменной DAYLY_COLLECT_CONSULTATIONS_TIME  в .env файл при деплое. Исправляется в рамках PR 115 (https://github.com/Studio-Yandex-Practicum/ask_nenaprasno_bot/pull/115)