Add opportunity to check limits of Telegram
Studio-Yandex-Practicum/ask_nenaprasno_bot pull request #105
Opened 2022-08-23 01:29 UTC by sdvkam

Задача: Обход лимитов для рассылок Телеграмма - Первый вариант 
1. для лимита в 1 сообщение в секунду для одного пользователя работает 
2. для лимита в 30 сообщений за секунду для разных пользователей - не знаю как проверить

2022-08-24 10:09 UTC, veselij requested changes
честно говоря, я ничего не понял как это работает и работает ли это в принципе. очень много магических цифр и названий из которых сложно понять цель. есть неиспользуемые методы у класса.
Так же есть изенения из другого PR, почему они тут?

2022-08-24 10:09 UTC, veselij commented on src/decorators/limits.py
> +WITHOUT_CHECK = False
магические цифры а что они значат? 1сек еще могу предположить, а что такое 40ms вообще не понятно

2022-08-24 10:09 UTC, veselij commented on src/decorators/limits.py
> +def cheat_limits_of_telegram(func):
почему cheat мы разве обманываем кого-то? мы же наоборот соблюдаем правила... надо подумать над другим именем. возможно force_telegramm_limit или throttling_messages

2022-08-24 10:09 UTC, veselij commented on src/decorators/limits.py
> +        if WITHOUT_CHECK:
а почему такое возможно в принципе?

2022-08-24 10:09 UTC, veselij commented on src/decorators/limits.py
> +        return await func(*args, **kwargs)
логику isinstance и AttributeError невозможно понять...

2022-08-24 10:09 UTC, veselij commented on src/decorators/limits.py
> +        self.users_last_sending = {}
а эти методы нигде не используются, зачем они?

2022-08-24 10:09 UTC, veselij commented on src/decorators/limits.py
> +        point_for_user = self.users_last_sending.get(telegram_id, currently - 3 * USER_DURATIN) + USER_DURATIN
а что за магия умножения на 3?

2022-08-24 10:51 UTC, sdvkam commented on src/decorators/limits.py
> +WITHOUT_CHECK = False
Одно из ограничений в Телеграме:
 - не больше 30 сообщений в секунду для разных пользователей
т.е. если посылать сообщения для разных пользователей через 1/30 секунды - то ограничение мы обойдём 
All_DURATION ~ 1/30 секунды

2022-08-24 10:53 UTC, sdvkam commented on src/decorators/limits.py
> +        if WITHOUT_CHECK:
WITHOUT_CHECK - включение и выключение режима обхода лимита.

2022-08-24 11:10 UTC, sdvkam commented on src/decorators/limits.py
> +        return await func(*args, **kwargs)
1. У нас три функции выводят сообщения пользователю. Нам надо из аргументов функции получить id бота. В одной функции id бота передаётся напрямую, в другой передаётся объект Update из которого этот id можно получить.
Isinstance проверяет какой тип значений мы получили.
2. При проверки столкнулся с тем что при вызове одной из трёх функций, один аргумент не был именован. Возникла ошибка. Я подумал, что если при дальнейшей поддержки кода, кто-нибудь может также опустить. Поэтому поставил проверку и запись в логи.

2022-08-24 11:22 UTC, sdvkam commented on src/decorators/limits.py
> +        point_for_user = self.users_last_sending.get(telegram_id, currently - 3 * USER_DURATIN) + USER_DURATIN
В словаре user_last_sending мы храним время последнего отправленного сообщения для каждого пользователя бота.
Иногда может оказаться, что в словаре не будет данных о каком-либо пользователе (первое отправленое сообщения).
Метод get в этом случае даст None. А нам нужно получить значение времени для этого пользователя. И оно должно быть меньше текущего момента. Поэтому и отнимаю от текущего времени. Почему "3"? - 🤷‍♂️.

2022-08-24 11:23 UTC, sdvkam commented on src/decorators/limits.py
> +        if WITHOUT_CHECK:
Название конечно не говорящее о сути.

2022-08-24 11:30 UTC, sdvkam commented
Изменения из другого PR:
В модуле: timezone нужно было поправить только одну функцию. Был неименованный параметр.
Но при коммите автоматически было внесено куча изменений в этот модуль. Я глянул в главную ветку на сайте и увидел, что этот модуль уже поправлен. И просто скопировал его код в модуль своей ветки. Поправил функцию и запушил.

2022-08-26 08:38 UTC, AntonZelinsky commented on src/decorators/limits.py
> +        if WITHOUT_CHECK:
В принципе, может быть полезно отключить для каких-то тестов, но значение может из конфигов брать, а не хардкодить тут?

2022-08-26 08:39 UTC, AntonZelinsky commented on src/decorators/limits.py
> +WITHOUT_CHECK = False
Добавь комментарии и ссылку на документ телеграмма к этим переменным

2022-08-28 15:17 UTC, closed without merging