Reworked webhook's methods for real-time updates to work with the current site API methods
Studio-Yandex-Practicum/ask_nenaprasno_bot pull request #110
Opened 2022-08-24 20:14 UTC by malyshevadv

Reworked webhook's methods for real-time updates to work with the current site API methods.

Для информации, текущее API, отправляющее информацию о новых сообщениях:

==== POST /bot/consultation/assign ====

{

consultation_id: 'DUzg7XyhptwUt6',

due: '2022-08-18T12:22:43.906Z',

trello_card_id: '62fb8b3a3873f3005243db39',

username_trello: 'drkotovmaxim',

telegram_id: '[[261550045](tel:261550045)](tel:261550045)’

}

==== POST /bot/consultation/close ====

{ consultation_id: 'vpa0NxvzV0kk9n' }

==== POST /bot/consultation/message ====

{

consultation_id: 'vpa0NxvzV0kk9n',

trello_card_id: '62f4d9ed6b564e009d5d490d',

username_trello: 'user98803724',

telegram_id: '888'

}==== POST /bot/consultation/feedback ====

{

consultation_id: 'vpa0NxvzV0kk9n',

trello_card_id: '62f4d9ed6b564e009d5d490d',

username_trello: 'user98803724',

telegram_id: '888'

}

2022-08-24 20:39 UTC, AntonZelinsky commented on src/run_webhook_api.py
> +            f"Получена новая заявка №<<TBA>>\n"
Ой, а что это значит `<<TBA>>`?

2022-08-24 20:39 UTC, AntonZelinsky commented on src/run_webhook_api.py
> +    #     bot = api.state.bot_app.bot
???

2022-08-24 20:39 UTC, AntonZelinsky commented on src/run_webhook_api.py
> +    # ! information is provided, without the consultation_response. Once fixed,
Docstring???

2022-08-25 06:08 UTC, malyshevadv commented on src/run_webhook_api.py
> +            f"Получена новая заявка №<<TBA>>\n"
to be added :)

2022-08-25 06:11 UTC, malyshevadv commented on src/run_webhook_api.py
> +            f"Получена новая заявка №<<TBA>>\n"
Сейчас номер заявки не возвращается, а в требованиях к сообщению он есть. Могу добавить какой то радобный номер вместо этого или другую фразу

2022-08-26 10:02 UTC, veselij requested changes

2022-08-26 10:02 UTC, veselij commented on src/run_webhook_api.py
> +            f"Получена новая заявка №<<TBA>>\n"
давай пока уберем все это лишнее, будем считать, что номер заявки нам не нужен, чтобы не забыть про него, я в ноушене задачу добавлю

2022-08-26 10:02 UTC, veselij commented on src/run_webhook_api.py
> +    # ! information is provided, without the consultation_response. Once fixed,
так, мы не должны получать никакой текст отзыва. вот поля которые должны приходить
{
   "consultation_id":"1234",
   "username_trello": "xxx",
   "telegram_id": "id"
}

сделай FeedbackConsultationModel с этими полями

надо поправить ClosedConsultationModel - убрать лишнее поля тоже, оставить только поле consultation_id

вот тут описание
https://docs.google.com/spreadsheets/d/1ul1fCjuQeBiYlC7-n_x1929o3NXk4kUiu-ucxbHeahc/edit#gid=823814981

после этого убрать все эти комментарии

2022-08-26 10:02 UTC, veselij commented on src/run_webhook_api.py
> +            f"Вы получили новый отзыв по заявке №<<TBA>>\n"
место №<<TBA>> надо посдавить ссылку на заявку на сайте, чтобы человек мог на нее нажать и его перебросило на страницу заявки на сайте где и будет отзыв

2022-08-28 15:16 UTC, AntonZelinsky approved these changes

2022-08-28 15:16 UTC, AntonZelinsky commented on src/run_webhook_api.py
> +            f"[Открыть заявку на сайте]({URL_SITE}doctor/consultation/{request_data.consultation_id})\n"
А давай везде переделаем ссылку на такого вида `https://ask-nnyp.klbrtest.ru/consultation/redirect/KeDDzS_KModxnJ`, сайтом она будет преобразована в `https://ask-nnyp.klbrtest.ru/manager/consultation/KeDDzS_KModxnJ?` для менеджера и в `https://ask-nnyp.klbrtest.ru/doctor/consultation/KeDDzS_KModxnJ?` для доктора. 
Если менеджер перейдёт по ссылке  для доктора, то на той странице не будет элементов управления заявками

2022-08-28 23:09 UTC, merged