Feature/limits of telegram new version
Studio-Yandex-Practicum/ask_nenaprasno_bot pull request #111
Opened 2022-08-26 10:02 UTC by sdvkam

Новая версия декоратора для решения проблем лимита.
Должен быстрее проталкивать сообщения.
Тесты пройдены, вроде работает.
Учел замечания сделанные к другому PR с решением этой же задачи.

2022-08-27 23:50 UTC, AntonZelinsky requested changes
Не актуально из-за сегодняшнего релиза библиотеки, в которой выкатили эту фитчу..(
https://github.com/python-telegram-bot/python-telegram-bot/wiki/Avoiding-flood-limits

2022-08-27 23:50 UTC, AntonZelinsky commented on src/decorators/limits.py
> +def regulating_time_sending_messages(func):
В название лучше добавить avoiding limits. MODE_ACCOUNTING_LIMIT_TELEGRAM сюда же. Получилось два совершенно разных названия и не понятно, что они значат. Уж лучше AVOIDING_TELEGRSM_LIMITS, может какой-то предикат добавить, чтобы более понятное было название

2022-08-27 23:50 UTC, AntonZelinsky commented on src/decorators/limits.py
> +        self.curent_second = self.curent_second - timedelta(microseconds=self.curent_second.microsecond)
Что это код делает? Что-то очень странное!
Просто отрезает секунды? 
![image](https://user-images.githubusercontent.com/1431279/187051400-2c559ad9-dfc0-403b-b24e-51035a3fe593.png)

2022-08-28 00:11 UTC, sdvkam commented on src/decorators/limits.py
> +        self.curent_second = self.curent_second - timedelta(microseconds=self.curent_second.microsecond)
Округляет до секунды

2022-08-28 14:51 UTC, closed without merging

2022-08-28 22:51 UTC, AntonZelinsky commented on src/decorators/limits.py
> +        self.curent_second = self.curent_second - timedelta(microseconds=self.curent_second.microsecond)
Удалять миллисекунды нужно так ` datetime.datetime.now().replace(microsecond=0)`