Impliment close_consultation view fn
Studio-Yandex-Practicum/ask_nenaprasno_bot pull request #117
Opened 2022-08-30 17:53 UTC by Anzhela-Namistyuk

**Задача**
Реализация view consultaion_close
эта view принимает от сайта уведомления о том, что та или иная заявка закрыта врачом. Нам соответсвенно надо, получив такое сообщение, найти все Jobы по напоминаниям, которые заведены для данной заявки (через час после истечения срока или по истечению через день или уже истекшей) и удалить их, так как напоминать о заявке уже нет смысла.

**Примечание**
В коде удаляются Jobы которые напоминают о истечении срока через час.
Остальные описанные в задании Jobы напоминания не удаляются так как их нет в коде.
Эти Jobы еще не созданы.

2022-08-30 21:45 UTC, AntonZelinsky commented on requirements.txt
> +telegram~=0.0.1
Ой, а что за новая зависимость?

2022-08-31 07:08 UTC, Anzhela-Namistyuk commented on requirements.txt
> +telegram~=0.0.1
В файле run_webhook_api.py  eсть строчка from telegram import Bot, Update. Пайчарм предложил добавить завистмость

2022-08-31 10:14 UTC, MatMerd requested changes

2022-08-31 10:14 UTC, MatMerd commented on requirements.txt
> +telegram~=0.0.1
Анжела, нам не нужна эта зависимость. У нас всё импортится из PTB

2022-08-31 10:20 UTC, AntonZelinsky commented on requirements.txt
> +telegram~=0.0.1
Не, мы так не добавляем зависимости,  зависимости добавляются через poetry. Работало раньше без этой строчки и будет дальше. Библиотека PTB имеет такое пространство имён.

2022-08-31 10:20 UTC, AntonZelinsky commented on requirements.txt
> +telegram~=0.0.1
Не, мы так не добавляем зависимости,  зависимости добавляются через poetry. Работало раньше без этой строчки и будет дальше. Библиотека PTB имеет такое пространство имён.

2022-08-31 21:15 UTC, AntonZelinsky approved these changes

2022-08-31 21:15 UTC, merged