moved urls to core.config as URL constants
Studio-Yandex-Practicum/ask_nenaprasno_bot pull request #118
Opened 2022-08-30 18:14 UTC by Erduyta

**Задача**: "вынести домен сайта в конфиг из сообщений"

Создал три новых константы в конфиге, провел замену доменов на константы в тексте сообщений.

2022-08-31 17:23 UTC, Erduyta commented
Убрал trello и wiki urls из конфига обратно в код.

2022-08-31 18:48 UTC, MatMerd requested changes, later dismissed

2022-08-31 18:48 UTC, MatMerd commented on src/core/config.py
> +URL_ASK_NNYP = "https://ask-nnyp.klbrtest.ru/consultation/redirect/"
Мне не очень нравится нейминг. Давай сделаем более понятное название. Я как только увидел, сразу начал расшифровывать. В урле - это понятно, растягивать урл не оч круто.

2022-08-31 21:30 UTC, AntonZelinsky commented on src/core/config.py
> +URL_ASK_NNYP = "https://ask-nnyp.klbrtest.ru/consultation/redirect/"
Ну да, суть задания в том, чтобы вынести `https://ask-nnyp.klbrtest.ru` в отдельную переменную, а потом везде подставлять там, где используются  домен сайта. Только это значение должно браться из env, ведь на каждом сервере оно будет своё: `https://ask-nnyp.klbrtest.ru`, `https://ask-nn.klbrtest.ru` и `https://ask.nenaprasno.ru/`

Кстати, а что за переменная `HOST`? для чего она используется? Может, будем добавлять комментарии в конфиг файл, а то очень легко запутаться. Плюс, .env.example файл не включает половину переменных которые у нас тут есть.
@MatMerd @veselij может для тестового сервера файл .env будем комитать? так, мы все будем видеть его актуальное состояние и какие точно используются переменные. На проде уже так нельзя делать, а тут почему бы и нет? Токен от бота нестрашно если узнают, всё равно с этим сделать ничего не смогут. А удобнее явно всем будем

2022-08-31 21:32 UTC, AntonZelinsky commented on src/core/config.py
> +URL_ASK_NNYP = "https://ask-nnyp.klbrtest.ru/consultation/redirect/"
Плюс, переменная с доменом сайта должна использоваться во всех сообщения отправляемых в боте, так как сейчас там полнейший бардак.

2022-08-31 21:34 UTC, AntonZelinsky commented on src/core/config.py
> +URL_ASK_NNYP = "https://ask-nnyp.klbrtest.ru/consultation/redirect/"
И чем эта переменная отличается от URL_SITE?

2022-08-31 21:35 UTC, Erduyta commented on src/core/config.py
> +URL_ASK_NNYP = "https://ask-nnyp.klbrtest.ru/consultation/redirect/"
Поменял имя константы URL'a на `URL_ASK_NENAPRASNO`.

2022-08-31 21:36 UTC, AntonZelinsky commented on src/core/config.py
> +URL_ASK_NNYP = "https://ask-nnyp.klbrtest.ru/consultation/redirect/"
Окей, а таперь перечитай что я писал выше)

2022-08-31 22:21 UTC, Erduyta commented on src/core/config.py
> +URL_ASK_NNYP = "https://ask-nnyp.klbrtest.ru/consultation/redirect/"
У меня твои комментарии на тот момент не прогрузились, сорри.

2022-08-31 23:23 UTC, Erduyta commented
Переделал константу, оставив только главную часть URL, по этой же причине удалил URL_SITE_DONATION.

2022-09-02 22:27 UTC, AntonZelinsky approved these changes
Как поправишь урлы, можешь сам мержить

2022-09-02 22:27 UTC, AntonZelinsky commented on src/core/config.py
> +URL_ASK_NENAPRASNO = "https://ask-nnyp.klbrtest.ru/"
Я бы  значение переменной использовал без последней косой черты
```suggestion
URL_ASK_NENAPRASNO = "https://ask-nnyp.klbrtest.ru"
```
А использовал потом таким образом
```
f"({config.URL_ASK_NENAPRASNO}/consultation/redirect/{consultation_id})"
```
```
InlineKeyboardButton("Поддержать проект", url=f"{config.URL_SITE}/#donation"),
```
На мой взгляд проще воспринимать.

2022-09-02 22:40 UTC, AntonZelinsky commented on src/core/config.py
> +URL_ASK_NENAPRASNO = "https://ask-nnyp.klbrtest.ru/"
во[т как раз при](https://github.com/Studio-Yandex-Practicum/ask_nenaprasno_bot/pull/120/files)мер того, что у нас используются разные переменные и нет порядка в них . Тут используется совсем другая переменная URL_SITE. В чём между ними разница? Давайте использовать какую-то одну.
Мне больше нравится новый вариант, как более читаемый, а первый предлагаю удалить. Плюс, в этом же ПРе пройдись по всем ссылкам и поправь хардкоды. И кстати, значение переменной нужно делать не константой, а брать из .env файла (писал уже об этом)

2022-09-03 09:59 UTC, veselij commented on src/jobs.py
> +            f"({config.URL_ASK_NENAPRASNO}consultation/redirect/{consultation_id})"
"/" забыл

2022-09-03 18:06 UTC, merged