First version of API Client. Api_client_dumpdata is a temporary file.…
Studio-Yandex-Practicum/ask_nenaprasno_bot pull request #12
Opened 2022-06-17 07:18 UTC by IPfa

API Клиент.

Основная функция main получает на вход обязательный параметр url - ссылку по которой необходимо сделать запрос, и два опциональных параметра telegram_id и user_timezone для post и put запросов соответсвенно. 

Далее функция проверяет соответсвует ли запрос ендпоинтам приложения. Ендпоинты взяты из таблицы - https://docs.google.com/spreadsheets/d/1ul1fCjuQeBiYlC7-n_x1929o3NXk4kUiu-ucxbHeahc/edit#gid=429815105&range=D2:G8. 

В случае совпадения функция main вызывает соответствующую функцию из файла api_client_functions.py. В api_client_functions.py каждая функция отвечает за свой запрос - get (получение статистики), post(аутентификация пользователя), put(установка временного пояса для пользователя).

Сервер возвращает данные в формате json, функции get, post и put десериализуют данные.

Так как API сайта пока не написан функции get, post и put возвращают json данные из файла api_client_dumpdata.py.

2022-06-17 10:20 UTC, veselij requested changes
в целом концепция ок, но реализацию надо сделать немного по другому.

предлагаю сделать с помощью классов:
1. создать абстрактный базовый класс APICallService c тремя методами get, put, post
2. создать реализацию базового класса APICallSerice  и в ней реализовать методы get post put  на основе aiohttp клиента (или httpx) которые будут вызывать API сайта и возвращать дикты
3. создать реализацию базового класса APICallService и в ней реализовать те же 3 метода, только место реального вызова сайта - просто отдать дикты с dumpdata
4. создать класс SiteService, который при инициализации будет принимать экземпляр   APICallService. и в методах SiteService уже реализовать методы authenticate_user, set_user_time_zone ...которые внутри себя будут вызывать методы get, post, put APICallService и преобразовывать дикты в датаклассы

при таком сетапе, мы сможем при создании SiteService дать ему или реальный APICallService или APICallService который отдает dump Data. при этом методам authenticate_user, set_user_time_zone будет все равно какая конкретно APICallService им подставлена.

2022-06-17 10:20 UTC, veselij commented on requirements.txt
> +requests==2.28.0
web запросы лучше делать асинхронно. надо посмотреть в сторону httpx или aiohttp

2022-06-17 10:20 UTC, veselij commented on src/api_client_ask_nenaprasno.py
> +    endpoint = url.replace(config.WEBHOOK_URL, '')
webhook_url это адрес на котором наш сервер слушает запросы от трелло, поэтому его тут использовать не надо. Надо создать новую переменную в env SITE_URL например

2022-06-17 10:20 UTC, veselij commented on src/api_client_ask_nenaprasno.py
> +        search_result = re.search(i, endpoint)
ты на каждый типа запроса добавил цикл, что не есть хорошо, при большом количестве запросов все может начать тормозить. 
помимо цикла ты еще работаешь с поиском по стрингам, что не самая быстрая операция в питоне

2022-06-17 10:20 UTC, veselij commented on src/api_client_ask_nenaprasno.py
> +                    )
в таком исполнении ты не поймаешь экспешен, так как ты не указал, что надо отлавливать. 
райзить базовый класс эксепшена тоже не правильно, если райзишь, то надо создаст свой кастомные экспешен, на который ты сможешь дальше в коде реагировать
также надо добавит логирование

2022-06-17 10:20 UTC, veselij commented on src/api_client_functions.py
> +    response = json.dumps(TGBOT_STAT_MONTHLY)
не самый удобный способ замокать вызов функции, надо менять во многих местах и не забыть потом во всех местах поменять.

2022-06-20 08:09 UTC, veselij requested changes
привет, давай по итогу делать, как Антон предлагал в чате, я согласен, что это более грамотный и легко читаемый вариант.
 посмотри там в чате пример Антона.

2022-06-20 08:09 UTC, veselij commented on src/api_client_ask_nenaprasno.py
> +SITE_SERVICE = SiteService(API_SERVICE_DUBM)
заглавные используются только для констант, тут же ты создаешь экземпляры классов, не по pep

2022-06-20 08:09 UTC, veselij commented on src/api_client_ask_nenaprasno.py
> +SITE_SERVICE = SiteService(API_SERVICE_DUBM)
так же как писал Антон, ту мы можем нарваться на проблему с многопоточностью. и решили сделать создание или fake или Real сервиса в файле __init__.py в зависимости от флага из конфига

2022-06-20 08:09 UTC, veselij commented on src/api_client_ask_nenaprasno.py
> +async def main(url, **kwargs):
не совсем понял а для чего это нам надо? мы же должны будем импортнуть класс сервиса и вызывать его методы в других частях приложения (будет делаться в других заданиях)

2022-06-20 08:09 UTC, veselij commented on src/api_client_dumpdata.py
> +TGBOT_AUTH = {
предлагаю, как писал Антон, мокать не вызовы http get/pots/put а бизнеслогику, тогда можно описать датакласс для каждого дикта данных и в фейк бизнес логике отдавать как раз экземпляры этих датаклоссов сформированные в ручную с фейковыми данными

2022-06-20 08:09 UTC, veselij commented on src/api_client_functions.py
> +        return request.status_code
давай мокать эти методы, как писал Антон

2022-06-21 07:41 UTC, veselij requested changes

2022-06-21 07:41 UTC, veselij commented on src/api_client.py
> +    # @abstractmethod
закоментированый код не надо оставлять, лучше удалить

2022-06-21 07:41 UTC, veselij commented on src/api_client.py
> +# по методу на каждую url?
да, в данном случает надо на каждую статистику по своему методу. урлы могут поменять и твой парсер перестанет работать, в то время когда в отдельных методах, тебе надо будет поменять только url
и выходные данные у тебя сильно отличаются. и как ты заметил с моками проблемы.

удали эти комментарии тоже и задавай вопрос в диалоге лучше

2022-06-21 07:41 UTC, veselij commented on src/api_client.py
> +    async def authenticate_user(self, telegram_id: int) -> bool:
разве бул возвращает метод? он же возвращает датакласс с данными юзера (на основе ответа от API)

2022-06-21 07:41 UTC, veselij commented on src/api_client.py
> +        response = response.json()
этот кусочек бесполезен и только усложняет чтение, можно только ретерн оставит и датакласс (значения прописать прям в датаклассе)

2022-06-21 07:41 UTC, veselij commented on src/api_client.py
> +        )
аналогично, сделай просто return true

2022-06-21 07:41 UTC, veselij commented on src/api_client.py
> +        self.authentication_code = config.authentication_code  # Другой Таск
параметры SITE_URL и code лучше передать как аргументы через инит.
мне кажется лучше передать SITE_URL в Enum в котором будет несколько полей - на каждое поле свой полный url. 
из .env брать параметр SITE_URL, а в конфете сконструировать Enum с полными путям на основе этого SITE_URL
и тогда в методах можно будет вызывать self.apis.AUTH_API без хардкодинга /tgbot/auth


т.е. как то так

```
import Enum

SITE_URL = env.get("SITE_URL")

class SiteAPI(Enum):
    USER_MONTH_STAT_URL = f"{SITE_URL}/tgbot/stat/weekly/user"
    USER_AUTH_URL = f"{SITE_URL}/tgbot/auth"
```



```
class RealAPIService(APIService):
     def __init__(self, SiteAPI, authentication_code ):
          self.apis = SiteAPI
```

2022-06-21 07:41 UTC, veselij commented on src/api_client.py
> +                return True
тут как раз надо создать  датакласс из json

2022-06-21 07:41 UTC, veselij commented on src/api_client.py
> +    async def authenticate_user(self, telegram_id: int) -> bool:
возвращать должны датакласс UserData

2022-06-21 07:41 UTC, veselij commented on src/api_client.py
> +            if response.status_code == HTTPStatus.CREATED:
ответ будет код 200

2022-06-21 07:41 UTC, veselij commented on src/api_client.py
> +        )
не нужен этот класс, надо вынести эти файлы в папку  services и там создать файл __init__.py. и в этом файле написать что-то типа

```

from core.config import DEBUG

from services.api_service import FakeAPIService, RealAPIService

if DEBUG:
    ConreateAPIService = FakeAPIService
else:
    ConreateAPIService = RealAPIService

```

2022-06-21 07:41 UTC, veselij commented on src/api_client_dataclasses.py
> +    user_id_in_trello: int
тут str надо, так как там UUID

2022-06-21 07:41 UTC, veselij commented on src/api_client_dataclasses.py
> +    user_ticket_resolve_avg_time: time
float

2022-06-21 07:41 UTC, veselij commented on src/api_client_dataclasses.py
> +    user_id_in_trello: int
str

2022-06-21 22:32 UTC, AntonZelinsky approved these changes
После правки фидбеков можно мержить, только нужно сообщить коллегам, что обновился дев и что нужно обновить свой файл .env

2022-06-21 22:32 UTC, AntonZelinsky commented on src/core/config.py
> +DEBUG = True
У нас пока нет поддержки нескольких конфигов, поэтому, эту переменную лучше в .env файл отправить. Плюс, дебаг это очень общее название, не характеризующее то, что произойдёт после переключения. Лучше назвать `MOCK_API` или `FAKE_API`, или `REAL_API`.

2022-06-21 22:32 UTC, AntonZelinsky commented on src/service/api_client.py
> +            return False
Стыдно!
```suggestion
            return response.status_code == HTTPStatus.OK
```

2022-06-21 22:32 UTC, AntonZelinsky commented on src/service/api_client.py
> +class APIService(ABC):
Разнеси все эти три класса по трём файлам

2022-06-22 20:14 UTC, veselij approved these changes
усправь пожалуйста 2 мелких замечания и мерджи

2022-06-22 20:14 UTC, veselij commented on src/service/__init__.py
> +from service.api_client import (
импортируешь из несуществующего модуля

2022-06-22 20:14 UTC, veselij commented on src/service/__init__.py
> +FAKE_API = env.get("FAKE_API")
это надо сделать в файле config которы уже есть в проекте и из него импортную просто FAKE_API  и тогда можно будет убрать лишний импорт

2022-06-22 20:32 UTC, merged