fix monthly statistics
Studio-Yandex-Practicum/ask_nenaprasno_bot pull request #121
Opened 2022-09-01 18:58 UTC by cianoid

fix monthly statistics message
fix daily notification of overdue consultations

2022-09-03 09:56 UTC, veselij requested changes

2022-09-03 09:56 UTC, veselij commented on src/conversation/menu.py
>      td_object = timedelta(days=0, hours=0, milliseconds=time)
td_object надо переименовать, не понятно, что это. Answer_time_ms например

2022-09-03 09:56 UTC, veselij commented on src/conversation/menu.py
> +def format_average_user_answer_time(time: float) -> str:
float | None

2022-09-03 09:56 UTC, veselij commented on src/conversation/menu.py
>      hours = td_object.seconds // 3600
можно сразу в f строке подставить

2022-09-03 09:56 UTC, veselij commented on src/conversation/menu.py
> +def format_rating(rating: float) -> str:
float | None

2022-09-03 09:56 UTC, veselij commented on src/conversation/menu.py
> +    if user_statistics is None or not isinstance(user_statistics.closed_consultations, int):
closed_consultations у нас толко int, если будет не int, то должно упасть в другом месте. так что проверять isinstance не надо

2022-09-03 09:56 UTC, veselij commented on src/conversation/menu.py
> +    if user_statistics.closed_consultations < 1:
с > 0 было более читаемо

2022-09-04 04:17 UTC, cianoid commented on src/conversation/menu.py
>      hours = td_object.seconds // 3600
ЯП не рекомендует проводить вычисления в f-строке, поэтому предлагаю оставить без изменений.

2022-09-05 11:36 UTC, veselij commented on src/conversation/menu.py
>      hours = td_object.seconds // 3600
мелкие можно на мой взгляд если там все явно. какие-то линтеры вообще f строки не реккомендуют. не принципиально

2022-09-05 11:36 UTC, veselij approved these changes

2022-09-05 11:36 UTC, merged