Добавлена диаграмма с текущей архитектурой бота
Studio-Yandex-Practicum/ask_nenaprasno_bot pull request #122
Opened 2022-09-01 19:34 UTC by malyshevadv

2022-09-03 12:10 UTC, veselij requested changes
третий раз смотрю на схему и пытаюсь понять, что мы ей хотим сказать)

у бота точно не хватает еще API который слушает телегам. вообще наверное стоит разделить отдельно сущность бота, отдельно сущность web сервера starlett

авторизация не описана еще

2022-09-03 18:48 UTC, malyshevadv commented
Идея, которую я вкладываю в эту схему - позволить понять, что как работает и куда обращается за информацией без чтения всех файлов кода, где не всегда четко понятно, что откуда берется. Надеюсь, стало получше

2022-09-05 11:33 UTC, veselij requested changes
сейчас намного понятнее стало, мне кажется еще стоит все таки явно выделить на схеме что у нас есть отдельно сущность веб сервера, которая спрятана за nginx и есть отдельно бот и веб сервер вызывает методы бота для отправки уведомлений. Т.е. у нас всего 6 сущностей:
1. фронт APIs
2. фронт БД
3. облако - сам телеграмм с API
4. веб сервер для бота с 2мя вебхуками
5. сам бот
6. nginx

2022-09-05 17:07 UTC, malyshevadv commented
Нужно пояснение, так как я немного не понимаю, где nginx и как он используется.
И хочу уточнить про 2 вебхука - один для уведомлений в реальном времени от сайта, а второй для телеграма, так? Или какой второй?

2022-09-05 18:15 UTC, veselij commented
> @veselij , нужно пояснение, так как я немного не понимаю, где nginx и как он используется.
> 
> И хочу уточнить про 2 вебхука - один для уведомлений в реальном времени от сайта, а второй для телеграма, так? Или какой второй?

nginx принимает все внешние запросы от сайта и телеграмма и перенаправляет их нашему веб серверу у которого два эндпоинта как ты написала - все верно

2022-09-08 09:14 UTC, veselij approved these changes

2022-09-08 09:15 UTC, veselij commented
@AntonZelinsky  @MatMerd посмотрите пожалуйста

2022-09-09 16:34 UTC, merged