add func word_ending and refact .env.example
Studio-Yandex-Practicum/ask_nenaprasno_bot pull request #127
Opened 2022-09-05 19:35 UTC by AngelNad

**Выполнение задачи:**
"Написать функцию, которая будет менять окончания слов “день” и “час” в зависимости от числа рядом с этим словом"

_Дополнительно:_
Т.к. запуск приложения от ветки develop выдавал ошибку об отсутствии переменной в файле .env, то изменила файл .env.example добавив туда `DAILY_REMINDER_FOR_OVERDUE_CONSULTATIONS` и удалив дублирующую, незадействованную.

2022-09-06 13:26 UTC, veselij requested changes

2022-09-06 13:26 UTC, veselij commented on .env.example
> +DAILY_REMINDER_FOR_OVERDUE_CONSULTATIONS=14:00                  # время ежедневного получения напоминаний о просроченных заявках
а почему время поменялось?

2022-09-06 13:26 UTC, veselij commented on src/conversation/menu.py
> +    return five
как-то названия не читаются, если не смотреть на вызов функции, то не понятно, что такое one, two, five. можно кстати сделать в один if elif else?

2022-09-07 12:04 UTC, AngelNad commented on .env.example
> +DAILY_REMINDER_FOR_OVERDUE_CONSULTATIONS=14:00                  # время ежедневного получения напоминаний о просроченных заявках
Подсказали, что по UTC нужно устанавливать, были изменения, а это вроде значит 3 часа разницы должно быть

2022-09-07 12:18 UTC, AngelNad commented on src/conversation/menu.py
> +    return five
если поменять на такие, норм будет?
time_end_1
time_end_2_4
time_end_5

по конструкции только вторую часть можно if elif сделать, т.к. там 2 смысловые части и 2-ая идёт уже после получения остатка одного знака после запятой (num = number % 10)

2022-09-07 13:32 UTC, veselij commented on .env.example
> +DAILY_REMINDER_FOR_OVERDUE_CONSULTATIONS=14:00                  # время ежедневного получения напоминаний о просроченных заявках
нам наоборот надо задать по UTC. а мы потом скажем что в 17-00 по нужной таймзоне

2022-09-07 13:46 UTC, veselij commented on src/conversation/menu.py
> +    return five
у меня такая мысль по логике - есть случай когда окончание 2,3,4 (остаток от деления на 10) и это все что угодно, но не 12,13,14 т.е. деление на цело на 10 !=1. есть второй случай когда окончание 1, но не 11 (т.е. остаток от деления на 10 =1) и есть все остальное. таким образов все попадает в if elif else.
get_word_case больше подходит как название. а аргументы может назвать single=день, few=дня, many=дней.

не факт что только для времени будем использовать, например, "у вас 3 заявки" тоже надо просклонять

2022-09-07 19:18 UTC, AngelNad commented on src/conversation/menu.py
> +    return five
Саша, так не работает, если я правильно поняла твою логику:
![image](https://user-images.githubusercontent.com/88459527/188959576-fa76e16f-fdcd-4cf2-b7f2-ec6680511873.png)

2022-09-07 19:23 UTC, AngelNad commented on src/conversation/menu.py
> +    return five
по поводу просклонять "у вас 3 заявки" это как следующую задачу оформить?

2022-09-07 19:50 UTC, AngelNad commented on src/conversation/menu.py
> +    return five
pylint не проходит с elif и else
![2022-09-07 22 41 22-vp2td](https://user-images.githubusercontent.com/88459527/188964521-92b04195-50fc-4519-878e-478cba453b8f.png)
![2022-09-07 22 46 08-83z8l](https://user-images.githubusercontent.com/88459527/188964524-a595da80-b2ba-44ea-b05c-8b8d0036c9ca.png)

2022-09-07 19:56 UTC, AngelNad commented on src/conversation/menu.py
> +    return five
Изменила что получилось, отправила на ревью

2022-09-08 09:16 UTC, veselij approved these changes

2022-09-08 11:14 UTC, merged