Feature/create jobs based on local time
Studio-Yandex-Practicum/ask_nenaprasno_bot pull request #128
Opened 2022-09-06 00:34 UTC by 4u3o

Создавать задачи для рассылок с учетётом таймзоны врача.
[notion tast](https://www.notion.so/dfc010c912744d21b7e9f987624a39fd)

2022-09-06 14:45 UTC, veselij requested changes

2022-09-06 14:45 UTC, veselij commented on src/core/utils.py
> +async def get_timezone_from_str(tz_string: Optional[str]) -> timezone:
а зачем асинхронной ее делать?

2022-09-06 14:45 UTC, veselij commented on src/jobs.py
> +        user_timezone = await get_timezone_from_str(user.timezone)
давай таймзону сохраним при ее смене/уставновке в бота с ключом telegram_id, и тут ее достанем, чтобы не делать доп запросы
туда же можно сохранить trello_name, чтобы не делать запросы

2022-09-06 14:45 UTC, veselij commented on src/jobs.py
> +            continue
а вот эта часть нужна? джоба разве не сработает сразу если ТЗ UTC?

2022-09-06 14:45 UTC, veselij commented on src/jobs.py
> +            continue
аналогичный вопрос

2022-09-06 14:45 UTC, veselij commented on src/jobs.py
> +        )
а почему мы не доверяем старой статистике? она же за предыдущую неделю. там ничего не может изменится

2022-09-06 16:47 UTC, veselij commented on src/jobs.py
> +        user_timezone = await get_timezone_from_str(user.timezone)
добавили trello_name в статиску месячную - поправь пожалуйста модели и используй от туда

2022-09-06 21:18 UTC, 4u3o commented on src/jobs.py
> +        )
По описанию статистика меняться не должна, т.к. "за прошлую неделю", но фактически, если я сейчас дерну ручку, добавлю себе новую заявку и снова дерну ручку - ответ изменится. Предполагаю что статистика за 7 последних дней. 
С месячной статистикой все нормально, она не изменяется, поэтому ее не проверяю.

2022-09-06 21:26 UTC, 4u3o commented on src/core/utils.py
> +async def get_timezone_from_str(tz_string: Optional[str]) -> timezone:
бес попутал, исправлю.

2022-09-06 21:28 UTC, 4u3o commented on src/jobs.py
> +            continue
Например у нас джоба weekly_stat_job назначена 01:00UTC, и она сама должна добавить другую джобу (send_weekly_statistic_job) на это же время, разве она сработает? По-моему это время будет уже "пройденным" и джоба выполнится через сутки.

2022-09-06 23:14 UTC, 4u3o commented on src/core/utils.py
> +async def get_timezone_from_str(tz_string: Optional[str]) -> timezone:
У меня тут, если врач не указал таймзону в боте -> вернется таймзона UTC, мб стоит возвращать МСК?

2022-09-06 23:25 UTC, 4u3o commented on src/jobs.py
> +        user_timezone = await get_timezone_from_str(user.timezone)
Под "сохранить в бота" имеется в виду `context.bot_data.update({tg_id: timezone})`?

2022-09-07 09:02 UTC, veselij commented on src/core/utils.py
> +async def get_timezone_from_str(tz_string: Optional[str]) -> timezone:
да, дефолт лучше Мск

2022-09-07 09:02 UTC, veselij commented on src/jobs.py
> +        user_timezone = await get_timezone_from_str(user.timezone)
да, верно

2022-09-07 09:05 UTC, veselij commented on src/jobs.py
> +        )
поговорили вчера с Антоном по этой части. Смотри что надо сделать, после того как мы стянули все статистики, проходимся по ним и планируем по 1 джобе на 1 часовой пояс. внутри этой джобы будет запрос обновленной статстики, потом фильтрование из этой статистики всех врачей у кого эта таймзона и отправка всем этим врачам обновленной статистики. Т.е. мы должны сделать максимум 24 запроса обновленной статистики. по 1 одному запросу на таймзону. иначае если будет 1000 врачей, то мы сделаем 1000 запросов, а если они в одной таймзоне то 1000 запросов в один момент времени по сути

2022-09-07 09:55 UTC, 4u3o commented on src/jobs.py
> +        )
Понял, сделаю

2022-09-07 10:14 UTC, 4u3o commented on src/jobs.py
> +        )
А по статистику по UTC+0  все таки нужно сразу отправлять или тоже в джобу планировать?

2022-09-08 10:56 UTC, veselij approved these changes

2022-09-08 10:56 UTC, veselij commented
@4u3o пофикси конфликты пожалуйста и можно мерджить

2022-09-08 12:58 UTC, merged