Add constants and menu.
Studio-Yandex-Practicum/ask_nenaprasno_bot pull request #13
Opened 2022-06-17 07:56 UTC by kapkaevandrey

## Ticket - [Create bot menu](https://www.notion.so/25e02e29ca674807a793a7df3e832903).
Added two beta keyboard in file with name bot_keyboards. 
__First__  - for request some info (for example - month statistic). At this moment keyboard have format inline and can be send to user when they need it.
__Second__ -  Inline keyboard for remind. This keyboard send when user receive some message about some events (for example - "Need pay check")

2022-06-17 09:13 UTC, veselij requested changes
практически все готово, осталось имена переменных и функций подправить и все!

2022-06-17 09:13 UTC, veselij commented on src/bot_menu.py
> +MENU_BUTTONS = [
я бы не писал заглавными буквами, все таки это не константа

2022-06-17 09:13 UTC, veselij commented on src/bot_menu.py
> +remind_one_hour = InlineKeyboardButton(
допиши в конце _button

2022-06-17 09:13 UTC, veselij commented on src/bot_menu.py
> +send_check_reactions = [
не понятно из названия, что это, может что-то типа bill_replay_buttons

2022-06-17 09:13 UTC, veselij commented on src/bot_menu.py
> +request_inline_keyboard = InlineKeyboardMarkup(MENU_BUTTONS)
тоже не очевидно, лучше menu_keyboard

2022-06-17 09:13 UTC, veselij commented on src/bot_menu.py
> +reminder_inline_keyboard = InlineKeyboardMarkup(send_check_reactions)
bill_keyboard. и надо еще добавить одну keyboard - просто с 1 кнопкой напомнить через час

2022-06-17 09:13 UTC, veselij commented on src/bot_menu.py
> +async def button(update: Update, context: ContextTypes.DEFAULT_TYPE) -> None:
название функций должно отражать какое действие она производит, тут не понятно, лучше что-то типа handling_menu_button_click

2022-06-17 09:13 UTC, veselij commented on src/bot_menu.py
> +    await query.answer()
надо добавить отправку сообщения с текстом нажатой кнопки (можно текст callback_data)

2022-06-17 10:39 UTC, veselij approved these changes

2022-06-17 23:37 UTC, AntonZelinsky commented on src/bot_menu.py
> +        "Меню", reply_markup=menu_keyboard
Я против выделения переменных типа `menu_keyboard` на уровне файла, а для их ещё одну переменную `menu_buttons,` хотя про переиспользование тут речи не идёт. А вот разобраться что к чему относится очень сложно. Я предлагаю перенести всё в функцию где непосредственно используются эти переменные.

2022-06-17 23:37 UTC, AntonZelinsky commented on src/bot_menu.py
> +    callback_data=command_constants.COMMAND_HOUR_REMIND
Это не из этой задачи, но ладно, пусть будет, главное по скорее смержить в дев код

2022-06-18 06:32 UTC, kapkaevandrey commented on src/bot_menu.py
> +    callback_data=command_constants.COMMAND_HOUR_REMIND
Про кнопку мен писал @veselij поэтому я её и сделал и она же используется в клавиатуре напоминании. Возможно стоит сделать файл buttons где собирать все кнопки и клавиатуры. Т.к. если вывод меню это отдельная команда, то клавиатура напоминание вызвается реакцией на определённое событие.

2022-06-18 06:32 UTC, kapkaevandrey commented on src/bot_menu.py
> +        "Меню", reply_markup=menu_keyboard
Кнопки меню перенесены в функцию. Клавиатура напоминаний, стала одной переменной.

2022-06-20 07:58 UTC, veselij requested changes
убери пожалуйста все кнопки и кейборды кроме относящихся только к меню

2022-06-20 07:58 UTC, veselij commented on src/bot_menu.py
> +
Андрей, удали пожалуйста эти кнопки и кейборды, в итоге решили они будут в другом месте. рядом с функций напомнить через час

2022-06-20 10:40 UTC, kapkaevandrey commented on src/bot_menu.py
> +
Готово

2022-06-20 10:50 UTC, veselij approved these changes

2022-06-20 11:40 UTC, AntonZelinsky approved these changes

2022-06-20 11:40 UTC, AntonZelinsky commented on src/bot_menu.py
> +menu_handler = CommandHandler('menu', callback=menu)
Давай тут немного изменим префикс на `_command_handler` и добавим его в хорошие практики.
```suggestion
menu_command_handler = CommandHandler('menu', callback=menu)
```
 Сделай потом ещё пост в общий канал

2022-06-20 12:50 UTC, AntonZelinsky commented
И сразу после мержа проверь соответсвие надписям и кнопкам [из этого документа](https://docs.google.com/spreadsheets/d/1TzpqGKxmrp4OoRd5CPHTEfgKlh1KFgtNk3gEKocpxas/edit?pli=1#gid=0)

2022-06-20 15:19 UTC, merged