Feature/send message
Studio-Yandex-Practicum/ask_nenaprasno_bot pull request #14
Opened 2022-06-17 08:17 UTC by Xewus

## Ticket - [Функция отправки сообщений](https://www.notion.so/7d6d35f407814742a0cebea1e480bd4b?p=f36a6369bd9f4111bed1a7026c3ad192)

- Add function `send_message` with exceptions

- Add logger

2022-06-17 09:20 UTC, veselij requested changes
привет,
не надо было закрывать первый PR, там остались все замечания, валидные и для это PR.  Пересмотри пожалуйста замечания из первого PR и поправь в этом PR. основная проблема, в том, что ты делаешь не то, что требуется. Надо сделать одну функцию которая будет рассылать сообщения пользователям. Для этого никакие кнопки меню не нужны

2022-06-17 11:02 UTC, Xewus commented
> вернуть True/False.

То есть, функция отправляет сообщение, а затем, при удачной попытке, возвращает `true`, при неудачной `false`, с записью в лог?

2022-06-17 11:04 UTC, veselij commented
Да.

2022-06-17 11:05 UTC, Xewus commented
> плохая практика перехватывать все эксепшены,
Это - да. Но на каком количестве перехватываемых ошибок остановиться... Тот же `TelegramError` можно разобрать на десяток...

2022-06-18 17:13 UTC, Xewus commented
Удалил всё ранее написанное. Оставил только одну требуемую функцию (в отдельном файле `src/core/send_message.py).
Ранее было указано о необходимости логирования ошибок, но тоже теперь не нужно, так как этим занимается коллега.

2022-06-18 23:09 UTC, AntonZelinsky commented on src/core/send_message.py
> +        return False
Перед выходом, нужно залогировать ошибку. Можно просто написать, что не удалось отправить сообщение пользователю с таким-то id и в лог так же добавить саму ошибку

2022-06-19 07:13 UTC, Xewus commented on src/core/send_message.py
> +        return False
Мне тут от скуки подумалось, может на классе это организовать...
Для логгирования же logger.py всё равно придётся заполнить настройками.

2022-06-19 15:47 UTC, AntonZelinsky commented on src/core/send_message.py
> +        return False
Нет, не нужно. Если класс, то тогда каждый раз нужно будет создавать экземпляр или использовать статический метод, что равносильно простому методу. В общем, пока это не имеет смысла.
Логер в другой задаче будет конфигурироваться, но логирование у тебя будет и без этого работать

2022-06-19 18:23 UTC, Xewus commented on src/core/send_message.py
> +        return False
Так и не придумал (не нашёл), как писать логи без логов, потому сделал минимум  - добавил `import logging` и `logging.error`.
В `src/bot.py` заменил `context.bot.send_message` на новую функцию `send_message`.
Зацепил `isort`ом  и `flake`ом  файл`src/run_webhook_api.py`.
Удалил все коммиты, сделав только 1 для очистки истории..

2022-06-19 22:24 UTC, AntonZelinsky commented on src/core/send_message.py
> +        return False
Я именно про такое логгирование и говорил.
Ошибки нужно логировать не так `wasnt sent.\n{err}'`, а так
`logger.error(msg, error, exc_info=True)`

2022-06-20 06:57 UTC, Xewus reviewed
Замечания исправил.
Подправил код под РЕР8 в файлах, которые затрагивал.
Чтоб никуда не лезть в настройки, добавил `.flake8` для игнорирования длинных строк в `src/core/config.py`, чтоб данные "ошибки" не отвлекали от настоящих.
Если не нужно, при слиянии можно удалить.

2022-06-20 07:10 UTC, AntonZelinsky approved these changes

2022-06-20 07:10 UTC, merged