fix number, active and expiring of consultations
Studio-Yandex-Practicum/ask_nenaprasno_bot pull request #143
Opened 2022-09-07 18:49 UTC by ant0ndk

2022-09-07 18:54 UTC, ant0ndk commented
[Notion](https://www.notion.so/23f4924fc18946f38025a289086e1194)
Добавил на вывод информацию о номере заявки, количестве активных и тех, которые заканчиваются через 1 день.
Последнее реализовано через expiring_consultation_ids, о котором написано в комментарии к [excel пункт 6](https://docs.google.com/spreadsheets/d/1ul1fCjuQeBiYlC7-n_x1929o3NXk4kUiu-ucxbHeahc/edit#gid=429815105)
Но в API я этого не нашел, вероятно добавят позже.

2022-09-14 20:02 UTC, veselij requested changes
привет, немного затфнулось добавление expiring_consultation_ids, сейчас добавили expiring_consultation_data - поправь пожалуйста под это изменение

2022-09-17 10:42 UTC, veselij requested changes

2022-09-17 10:42 UTC, veselij commented on src/run_webhook_api.py
> +    new_consultation_number = active_conusult_list[len(active_conusult_list)]["number"]
а зачем так сложно номер заявки высчитывать и возможно не правильно, у нас же в request_data приходит номер
"{
   ""consultation_id"":""1234"",
   ""**consultation_number**"": ""123"",
   ""trello_card_id"": ""123"", 
   ""username_trello"": ""xxx"",
   ""telegram_id"": ""id""
}"

2022-09-17 10:42 UTC, veselij commented on src/run_webhook_api.py
> +    expiring_consultations = len(active_conusult.expiring_consultation_data)
надо еще в модели services/api_client/models.py добавить поля для expiring_consultation_data, они сейчас не десиарилизуются

2022-09-17 10:42 UTC, veselij commented on src/run_webhook_api.py
> +        f"(https://trello.com/{TRELLO_BORD_ID}/?filter=member:{request_data.username_trello})\n"
вот тут у тебя конфликты - надо поправить и url сделать с помощью функций из core/utils.py - вчера их добавили

2022-09-20 17:48 UTC, veselij commented
а откуда столько изменений и у тебя есть конфликты - сейчас ничего не понятно, что поменялось

2022-09-23 15:06 UTC, veselij approved these changes

2022-09-23 15:06 UTC, merged