Add reminder job on due time
Studio-Yandex-Practicum/ask_nenaprasno_bot pull request #148
Opened 2022-09-10 12:19 UTC by RYPopov

1. Добавлен функционал уведомления в момент истечения заявки.
2. Проведен рефакторинг src/jobs.py согласно предложениям в ПР 116.
3. Вопрос:

Сегодня на встрече обсуждали следующий сценарий: Если у эксперта несколько заявок истекают, например, завтра, должен ли он получить несколько уведомлений (по одному сообщению на каждую истекающую заявку) или одно уведомление с перечнем номеров и ссылок всех истекающих завтра заявок? 

С одной стороны, в примерах оповещений согласно ТЗ предусмотрен только один вариант: одна заявка - одно оповещение. Это упрощает реализацию, делает "трекинг" экспертом просроченных заявок проще. Однако такой вариант "засоряет" тред повторяющимися частями сообщений "В работе количество  заявок... Истекает срок у количество заявок... Открыть Trello (ссылка на доску в trello с отфильтрованными заявками по эксперту)". 

С другой стороны, если будем "запихивать" все истекающие заявки в одно сообщение, то там будет полная "каша" с номерами и ссылками. Пользователю будет сложно ориентироваться, какие-то заявки могу "потеряться". При этом истекающие сегодня заявки в одно сообщение не поместить, так как у них может быть различное время истечения.

Оптимальным представляется промежуточный вариант:
"Урезать" сообщения об уведомлении о просроченных заявках, убрав общую для них часть "В работе ... Открыть Трелло". И добавить джобу единоразового ежедневного уведомления эксперта по шаблону (только если количество заявок в работе больше 0):

"В работе количество  заявок
Истекает срок у количество заявок
Открыть Trello (ссылка на доску в trello с отфильтрованными заявками по эксперту)" 

Таким образом, эксперту придет ряд отдельных коротких сообщений об истекающих ранее/сегодня/завтра заявках с ссылками на них. И дополнительно только одно уведомление о количестве заявок в работе и ссылкой на трелло.

Какой вариант будет наиболее приемлемым с точки зрения функционала приложения?

2022-09-10 12:27 UTC, RYPopov commented
@MatMerd Матвей, уже обсуждали в ПР116, изменить в .env в коде пайплайн проверки название переменной:
вариант DAILY_REMINDER_FOR_OVERDUE_CONSULTATIONS=17:00
заменить на вариант  DAILY_CONSULTATIONS_REMINDER_TIME=17:00

Прежний (текущий) вариант не отражает назначение переменной. В 17:00 мы уведомляем не только об истекших заявках.

Чтобы текущий ПР прошел пайп, сейчас загружу версию, привязанную к прежнему названию переменной окружения.

2022-09-11 17:57 UTC, veselij requested changes
модели лучше вынести в отдельный файл, сейчас у нас все датаклассы лежат в services/models.py

2022-09-11 17:57 UTC, veselij commented on src/core/config.py
>  DAILY_CONSULTATIONS_REMINDER_TIME = get_time("DAILY_REMINDER_FOR_OVERDUE_CONSULTATIONS")
давай сразу правильно называть иначе потом можем долго искать, что не там

2022-09-11 17:57 UTC, veselij commented on src/jobs.py
> +            return False
вот только эту часть надо оставить в базовом классе

2022-09-11 17:57 UTC, veselij commented on src/jobs.py
> +        return False
вот эта часть правильно реализовать в каждом дочернем классе в том же методе is_valid предварительно через  super вызвав is_valid базового класса, чтобы сделать одинаковую для всех проверку и избавиться от этих if таким образом

2022-09-13 21:03 UTC, RYPopov commented on src/core/config.py
>  DAILY_CONSULTATIONS_REMINDER_TIME = get_time("DAILY_REMINDER_FOR_OVERDUE_CONSULTATIONS")
если назову переменную окружения правильно, то не пройду тест в пайпе. Нужно, чтобы ты сначала изменил значение переменной в .env файле на сервере. Иначе не проходит чекап при пулреквесте.

2022-09-13 21:04 UTC, RYPopov commented on src/core/config.py
>  DAILY_CONSULTATIONS_REMINDER_TIME = get_time("DAILY_REMINDER_FOR_OVERDUE_CONSULTATIONS")
Что касается моделей, то могу перенести их в сервисы/модели. На встрече в субботу Матвеем было высказано предложение оставить модели в модуле джоб, так как они используется не являются моделями сервиса.

2022-09-13 21:08 UTC, RYPopov commented on src/jobs.py
> +            return False
придется переделать, чтобы эта часть возвращала объект cоnsultation, так как к атрибуту этого объекта в дальнейшем обращаемся для вторично проверки даты истечения срока. Получится кривовато.

2022-09-13 21:54 UTC, RYPopov commented on src/jobs.py
> +            return False
Решил возвращать объект date or None из суперкласса и сверять с текущей датой в дочерних классах.

2022-09-13 21:56 UTC, RYPopov commented on src/core/config.py
>  DAILY_CONSULTATIONS_REMINDER_TIME = get_time("DAILY_REMINDER_FOR_OVERDUE_CONSULTATIONS")
Александр, модели решил оставить в текущем модуле. Если переносить в модуль сервисы/модели, то там потянется целая вереница импортов. Также нужно будет создавать или импортировать объект `service = APIService()`. Поскольку эти модели используем в качестве конструкта для джобов, то разумнее оставить их в этом же модуле.

2022-09-14 09:17 UTC, veselij approved these changes

2022-09-14 09:17 UTC, veselij commented on src/core/config.py
>  DAILY_CONSULTATIONS_REMINDER_TIME = get_time("DAILY_REMINDER_FOR_OVERDUE_CONSULTATIONS")
ok

2022-09-14 09:17 UTC, merged