add config file persistence, add new constans in config
Studio-Yandex-Practicum/ask_nenaprasno_bot pull request #15
Opened 2022-06-19 22:07 UTC by Andrey-oss-ai

add new file persistence.py
add new constants in settings:
# Persistence file
USE_WEBHOOK = os.getenv('USE_WEBHOOK')
BOT_PERSISTENCE_FILE = os.getenv('BOT_PERSISTENCE_FILE')
HOST_NAME = os.getenv('HOST_NAME')

2022-06-20 07:22 UTC, veselij requested changes
скажи пожалуйста, а ты запускал бота, работало?

2022-06-20 07:22 UTC, veselij commented on src/core/config.py
> +HOST_NAME = os.getenv('HOST_NAME')
посмотри выше как мы берем env переменные, получается 2 разных способа для одного и того же используем в одном файле причем

2022-06-20 07:22 UTC, veselij commented on src/persistence.py
> +    bot = ExtBot(config.TOKEN)
а зачем ты нового бота создаешь?

2022-06-20 07:22 UTC, veselij commented on src/persistence.py
> +        dispatcher = init_webhook(bot, bot_persistence, config.WEBHOOK_URL)
а как это работает, ты просто передаешь нового бота в init и никак его там не используешь...

надо просто в функции create_bot при создании бота добавить конструкцию которая создаст изначального бота с персистант. и не важно web_hook или pooling

2022-06-20 15:03 UTC, Andrey-oss-ai commented on src/persistence.py
> +    bot = ExtBot(config.TOKEN)
Ну сегодня со свежей головой посмотрел и понял какой бред тут написан(

2022-06-20 15:05 UTC, Andrey-oss-ai commented on src/core/config.py
> +HOST_NAME = os.getenv('HOST_NAME')
Ну да, просто на автопилоте добавлял как обычно использовал, доля сомнений закралась при import os, но не обратил на сомнения внимания, исправил

2022-06-20 15:06 UTC, Andrey-oss-ai commented on src/persistence.py
> +        dispatcher = init_webhook(bot, bot_persistence, config.WEBHOOK_URL)
Идея была подключать инита при старте, но идея была так себе, да и смысла не было в этом как сейчас понял

2022-06-20 15:11 UTC, Andrey-oss-ai commented
Исправил все недоработки по ревью. Проверил файл создается все ок, но единственное заметил одну странность, если запускать на MacOS то файл создается сразу как только что то боту напишешь, а если запускать на Win, то файл в пайчарме в проекте  создавался только после завершения работы бота, хотя фактически в папке создавался сразу.

2022-06-20 16:45 UTC, veselij approved these changes

2022-06-20 18:47 UTC, AntonZelinsky approved these changes

2022-06-20 18:47 UTC, AntonZelinsky commented on src/bot.py
> +    ).build()
```suggestion py
    bot_app = ApplicationBuilder()\
        .token(config.TOKEN)\
        .persistence(persistence=bot_persistence)\
        .build()
```

2022-06-20 18:47 UTC, AntonZelinsky commented on src/core/config.py
> +BOT_PERSISTENCE_FILE = env.get('BOT_PERSISTENCE_FILE')
либо добавь в файл инвайрмента значение, либо тут сделай дефолт. Но лучше всё же первое

2022-06-20 18:47 UTC, AntonZelinsky commented on .gitignore
> +/src/test_persistence
Мне кажется, это тут не должно быть

2022-06-20 19:45 UTC, Andrey-oss-ai commented on src/core/config.py
> +BOT_PERSISTENCE_FILE = env.get('BOT_PERSISTENCE_FILE')
Добавил переменную в файл .env.example

2022-06-20 19:46 UTC, Andrey-oss-ai commented on .gitignore
> +/src/test_persistence
Да как то двояко вышло, поправил

2022-06-20 19:47 UTC, Andrey-oss-ai commented
Исправил файлы по комментариям из .gitignore убрал дубль и добавил переменную имени файла в .env.example

2022-06-20 19:54 UTC, Andrey-oss-ai commented on src/bot.py
> +    ).build()
Я всегда считал что практика обратных слешей, менее предпочтительна

2022-06-20 21:27 UTC, AntonZelinsky commented on .env.example
> +BOT_PERSISTENCE_FILE=test_persistence #имя файла persistence бота
Уж если добавил в гит игнор `bot_persistence_file`, то и сюда добавляй его, чтобы никому не приходилось править за тобой

2022-06-20 21:33 UTC, AntonZelinsky commented on src/bot.py
> +    ).build()
Правила нужны не для того, чтобы слепо следовать им, а чтобы выбирать наиболее подходящие для себя.
Но это даже не рекомендация, это описание общепринятой практики. 
Если можешь написать без слэшей, супер, но если тут большая конструкция и выбор стоим между читаемостью и простотой восприятия, и между отсутствием слэшей, то я выберу первый вариант.
p.s. у нас 120 символов длинна строки в проекте.

2022-06-20 22:35 UTC, Andrey-oss-ai commented on .env.example
> +BOT_PERSISTENCE_FILE=test_persistence #имя файла persistence бота
исправил имя файла

2022-06-20 22:36 UTC, Andrey-oss-ai commented
Привел в соответствие имена файлов в .gitignore и .env.example

2022-06-21 11:45 UTC, veselij commented
Андрей, разреши пожалуйста конфликты и подтяни изменения из develop, после этого смерджим

2022-06-21 12:31 UTC, closed without merging