refactor declination_zayavka
Studio-Yandex-Practicum/ask_nenaprasno_bot pull request #151
Opened 2022-09-12 19:46 UTC by AngelNad

**Выполнение задачи:**
по нажатию на кнопку активные заявки - в сообщение бота надо отформатировать текст, чтобы были склонения “заявок” в зависимости от кол-ва. и выровнять пробелы в списке заявок. (аналогично в кнопке - сроки горят)

_Дополнительно:_
- Выяснилось, что лишних пробелов нет. Визуальный эффект сдвига от второй строки происходит из-за ширины цифры "2", которая уже цифры "1"
- Поправила название переменной `link_neneprasno` на `link_nenaprasno`

2022-09-12 20:05 UTC, veselij requested changes

2022-09-12 20:05 UTC, veselij commented on src/conversation/menu.py
> +    declination_zayavka = get_word_case(active_consultations.active_consultations, "заявка", "заявки", "заявок")
ну только заявка надо по английски наппсиать как у нас принято consultation, а не транскриптом

2022-09-12 20:18 UTC, AngelNad commented on src/conversation/menu.py
> +    declination_zayavka = get_word_case(active_consultations.active_consultations, "заявка", "заявки", "заявок")
переименовала

2022-09-13 10:42 UTC, veselij approved these changes

2022-09-13 10:42 UTC, merged