refactor declination word consultations
Studio-Yandex-Practicum/ask_nenaprasno_bot pull request #155
Opened 2022-09-14 20:26 UTC by AngelNad

- Добавлена новая функция для склонения окончания слова "заявок" в родительном падеже.
- Добавлены обе функции склонения для вывода необходимого окончания слов в зависимости от значений в базовом шаблоне напоминаний бота и в шаблоне для уведомлений еженедельной статистики.
- Удалены лишние пробелы в тексте шаблона

2022-09-14 20:35 UTC, veselij requested changes

2022-09-14 20:35 UTC, veselij commented on src/conversation/menu.py
> +    return many
давай обе эти функции вынесем сюда
https://github.com/Studio-Yandex-Practicum/ask_nenaprasno_bot/blob/develop/src/core/utils.py

2022-09-14 20:36 UTC, AngelNad commented
Запуск бота видимо упал, потому что изменили название переменной окружения
https://github.com/Studio-Yandex-Practicum/ask_nenaprasno_bot/pull/154#issuecomment-1247171198

2022-09-15 10:52 UTC, AngelNad commented on src/conversation/menu.py
> +    return many
готово

2022-09-16 05:35 UTC, veselij approved these changes

2022-09-16 05:36 UTC, merged