feature/too-much-overdue-messages
Studio-Yandex-Practicum/ask_nenaprasno_bot pull request #159
Opened 2022-09-16 21:13 UTC by cianoid

2022-09-17 11:16 UTC, veselij requested changes

2022-09-17 11:16 UTC, veselij commented on src/jobs.py
> +        )
давай вот это в отельную функцию вынесем, очень много в одной получается

2022-09-17 11:16 UTC, veselij commented on src/jobs.py
> +            overdue[consultation.telegram_id] = overdue.get(consultation.telegram_id, []) + [consultation]
вот это надо через defaultdict сделать, более правильный путь. 
https://docs.python.org/3/library/collections.html#collections.defaultdict

2022-09-17 11:16 UTC, veselij commented on src/jobs.py
> +    if isinstance(job_data, PastConsultationsData):
вот эту часть давай вынесем в отдельную функцию и ее будем передавать в джобу

2022-09-17 11:16 UTC, veselij commented on src/jobs.py
> +            due_date = datetime.strptime(single_consultation.due, DATE_FORMAT).date()
тебе же тут надо запрос сделать к северу, для этого надо вызвать is_valid у single_consulation и все.
можно также через filter сделать чтобы вернулся генератор и потом его использовать, чтобы не создавать в памяти новый список

2022-09-17 11:16 UTC, veselij commented on src/jobs.py
> +        if len(consultations) > 1:
а какой смысл отрабатывать 1 элемент по разному, давай как генератор с 1 элементов обработаем и все

2022-09-17 20:52 UTC, cianoid commented on src/jobs.py
> +        if len(consultations) > 1:
Для одного элемента текст другой, поэтому и обработка по-разному

2022-09-18 15:28 UTC, veselij requested changes

2022-09-18 15:28 UTC, veselij commented on src/jobs.py
> +            send_reminder,
вот сюда бы я сделал отдельную функцию. isinstance как правило говорит как раз о плохо спроектированной логике. как workaround использовать пытаемся

2022-09-18 15:28 UTC, veselij commented on src/jobs.py
> +    if len(consultations) == 0:
вот тут можно сделать если -0 то ничего не делаем, если один то одна функция с шаблоном под 1 заявку, else другая функция с другим шаблоном

2022-09-18 15:28 UTC, veselij commented on src/jobs.py
> +        return consultations[0]
вот это тогда уберем

2022-09-18 17:57 UTC, cianoid commented on src/jobs.py
> +            send_reminder,
Ты, видимо, не туда тыкнул...

2022-09-19 14:38 UTC, veselij approved these changes

2022-09-19 14:38 UTC, merged