logger added
Studio-Yandex-Practicum/ask_nenaprasno_bot pull request #16
Opened 2022-06-20 05:40 UTC by IvanOsyanin

Сделано:
1.В файл core/config.py - добавил переменные (константы) BASE_DIR и LOG_DIR
2.В файл core/logger.py - прописал настройки логирования и создал два логгера, отличающиеся именами (bot и webhook). Но, в отличие от примера, добавил логгирование не только в файл, но и в поток. Думаю, на этапе разработки так удобнее. Также сделал по другому форматирование вывода лога - добавил туда имена логгера (bot либо webhook пока что).
3. Создал директорию decorators/ в ней создал logger.py. Там реализовал два декоратора:
3.1. Декоратор, которым можно обернуть асинхронную функцию-корутину
3.2. Декоратор, которым можно обернуть синхронную функцию.
Логика декоратора - при возникновении Exception в обернутой им функции, он логгирует ошибку. При этом декоратор принимает два аргумента:
-name (сюда можно писать, например, название функции или команды)
-logger (сюда нужно передать объект логгера)
Это нужно для того, чтобы было проще находить ошибку: аргумент logger (в нашем случае это либо bot, либо webhook) идентифицирует где глобально возникла ошибка, а аргумент name помогает найти команду/функцию где эта ошибка возникла
ПРИМЕЧАНИЕ: В примере была реализована логика, где декоратору можно передать списко функций, ошибки в которых не логгируются. Убрал, т.к. не понял ценности.
4. В файлы bot.py и run_webhook_dpi.py добавил:
4.1. Импорт соотвествующего логгера (bot_logger и webhook_logger соотвественно). Внутри файлов на них ссылается объект logger, чтобы где угодно другие могли использовать logger.info('..'), logger.warning('..') и т.д., не путаясь в названиях логгера
4.2. Каждую функцию/корутину обернул в соотвествующий синхронный, либо асинхронный декоратор.
Итого, сделано две вещи:
1. Везде доступен объект logging чтобы его можно было использовать для логгирования любой информации.
2. Сделан декоратора, который оборачивает функцию, и логирует возникающие в ней ошибки

2022-06-20 07:55 UTC, veselij requested changes
перемудрил немного, нам нужен только 1 логгер и только асинхронный, оборачивать никакие функции пока не надо. мы им обернем только определенные функции где отправляются сообщения в телеграмм. так как мы там отлавливаем все эксепшены, такое если и можно делать, то только точечно. Обернуть все в функцию которая скроет все эксепшены плохая практика, не увидишь где падает приложение.

итого:
1. надо оставит один логгер
2. так как логер останется один, то в конфете можно полностью указать Paths
3. оставить асинхронный декоратор
4. убрать вызовы декоратора со всех функций

2022-06-20 07:55 UTC, veselij commented on src/core/logger.py
> +        f'{LOG_PATH}/{path_name}',
пропиши path в конфиге сразу

2022-06-20 07:55 UTC, veselij commented on src/core/logger.py
> +    return webhook_logger
нет смысла дублировать и усложнять код

2022-06-20 19:36 UTC, IvanOsyanin commented
> 1. надо оставит один логгер
 - Оставил только bot logger, немного сократил код_
> 2. так как логер останется один, то в конфете можно полностью указать Paths
- Путь до файла указал в core/config.py Наименование самого файла - сделал внутри функции get_file_handler файла core/logger.py. Дело в том, что если я указываю только директорию в core/config.py, то могу красиво в одну строчку в файле core/logger.py (строка 38) сделать проверку существует ли папка, и если не существует - создать её. 
> 3. оставить асинхронный декоратор
- Сделано
> 4. убрать вызовы декоратора со всех функций
- Сделано

2022-06-20 19:40 UTC, veselij requested changes
просьба еще смерджить ветку develop чтобы не было конфликтов

2022-06-20 19:40 UTC, veselij commented on src/core/logger.py
> +        f'{LOG_PATH}/bot-log.txt',
давай здесь просто LOG_PATH,

2022-06-20 19:40 UTC, veselij commented on src/core/config.py
> +LOG_PATH = BASE_DIR / 'logs'
LOG_NAME = env.get("LOG_NAME")
LOG_PATH = BASE_DIR / LOG_NAME


а в .env.example добавить LOG_NAME = 'bot.log'
в .gitignore тоже добавить *.log

2022-06-23 13:46 UTC, MatMerd commented
Иван, у тебя конфликты в ветке. Пофиксь их пожалуйста!

2022-06-27 20:28 UTC, veselij requested changes

2022-06-27 20:28 UTC, veselij commented on src/run_webhook_api.py
>  from starlette.routing import Route
тут что то с блэкому тебя, строки короткие, не 120, поэтом сделал ненужные изменения. убери пожалуйста

2022-06-27 20:28 UTC, veselij commented on src/bot.py
> +    await bot_app.bot.set_webhook(url=f'{config.WEBHOOK_URL}/telegram')
что то с блэком, у всех " место '

2022-06-27 20:28 UTC, veselij commented on logs/bot-log.txt
> +2022-06-23 21:27:14,330 INFO Bot:	work
лог файлы называй .log и добавь в гитигнор (этот файл надо удалить из гита)

2022-06-27 20:28 UTC, veselij commented on src/core/config.py
> +BASE_DIR = Path(__file__).parent.parent.parent
```suggestion
BASE_DIR = Path(__file__).resolve().parent.parent
```
логи в src оставим. так как когда скопируем в докер, возможно прав у юзера выше src не будет на запись и задание файлов. также resolve - нормалиовать и получить полный пас

2022-06-27 20:28 UTC, veselij commented on src/core/config.py
> +LOG_PATH = BASE_DIR / 'logs'
а если папки нет?

2022-06-27 20:28 UTC, veselij commented on src/core/config.py
> +LOG_FILE = os.path.join(LOG_PATH, 'bot-log.txt')
не надо миксовать os.path и pathlib. если делаем в pathlib, то можно сконструировать так p = Path('main', 'error.log')

2022-06-27 20:28 UTC, veselij commented on src/core/logger.py
> +LOG_PATH.mkdir(exist_ok=True)
в конфиг лучше убрать

2022-06-27 20:28 UTC, veselij commented on src/core/logger.py
> +    bot_logger = logging.getLogger('Bot')  # noqa
```suggestion
    bot_logger = logging.getLogger(__name__)  # noqa
```

2022-06-27 20:28 UTC, veselij commented on src/core/logger.py
> +def bot_logging():
а какой смысл выносить в функцию, если мы потом все равно создаем один эксземпляр и только его используем.
и так не делают, ты когда вызываешь bot_logger = logging.getLogger('Bot') ты уже создал логгер, который можно получать в любом месте этой же командой,  поэтому можно убрать функцию и последнюю срочку ее вызова

2022-06-27 20:28 UTC, veselij commented on src/decorators/logger.py
> +                await func(*args, **kwargs)
```suggestion
                return await func(*args, **kwargs)
```

2022-06-29 15:56 UTC, veselij approved these changes

2022-06-29 21:57 UTC, AntonZelinsky approved these changes

2022-06-29 21:57 UTC, AntonZelinsky commented on src/core/config.py
> +LOG_NAME = env.get("LOG_NAME")
в .env.exmaple файле не появилась переменная LOG_NAME. Плюс, не понятно что это значит. Он в корень будет писать или эта переменная подразумевает папку?

2022-06-30 10:15 UTC, merged