Fix/messages for callbacks with zero consultations
Studio-Yandex-Practicum/ask_nenaprasno_bot pull request #161
Opened 2022-09-21 07:15 UTC by 4u3o

Не выводить “Посмотреть заявки на сайте:”, если заявок нет.
[notion](https://www.notion.so/55be0dae5da54331a379c239580039fc)

2022-09-21 08:04 UTC, cianoid commented on src/conversation/menu.py
> +            + "\n".join(
Думаю, тут стоит оставить один символ "\n", а то некрасиво будет

2022-09-23 15:08 UTC, veselij commented on src/conversation/menu.py
> +            + "\n".join(
почему один, там же как конец сроки будет применять

2022-09-23 15:10 UTC, veselij commented on src/conversation/menu.py
> +    if any(consultations_list):
а зачем any? если пустой список , и так false будет

2022-09-23 15:13 UTC, veselij requested changes

2022-09-23 15:13 UTC, veselij commented on src/conversation/menu.py
> +            + "\n"
вот этот ты имеешь ввиду лишний?

2022-09-23 16:47 UTC, cianoid commented on src/conversation/menu.py
> +            + "\n"
Я запутался на тот момент. Ща вижу, что все ок

2022-09-23 16:49 UTC, merged