Fixed message for consultation assign
Studio-Yandex-Practicum/ask_nenaprasno_bot pull request #188
Opened 2022-10-18 14:17 UTC by NVTaranets

2022-10-18 18:27 UTC, cianoid commented on src/jobs.py
> +    expired_cons_count = cons_count["expired"]
Давай не будем создавать отдельные переменные, которые используются один раз

2022-10-18 18:28 UTC, cianoid commented on src/jobs.py
>      consultation_count = await service.get_consultations_count(telegram_id)
```suggestion
    consultations_count = await service.get_consultations_count(telegram_id)
```

2022-10-18 18:29 UTC, cianoid commented on src/jobs.py
> +    text = get_reminder_text(job_data, consultation_count)
```suggestion
    text = get_reminder_text(job_data, consultations_count)
```

2022-10-18 18:59 UTC, cianoid commented on src/jobs.py
> +    text = get_reminder_text(job_data, consultation_count)
Пусть будет **consultations_count**

2022-10-18 19:35 UTC, cianoid requested changes
Есть идеи к улучшению. Посмотри и пиши - обсудим если будут вопросы

2022-10-18 19:35 UTC, cianoid commented on src/jobs.py
> +    cons_count: Dict,
Пусть тут все-таки будут переменные **active_consultations_count, expired_consultations_count, expiring_consultations_count**
Не надо передавать словарь

2022-10-18 19:35 UTC, cianoid commented on src/jobs.py
> +    expired_cons_count = cons_count["expired"]
Тогда эти переменные уйдут и в format

2022-10-18 19:35 UTC, cianoid commented on src/jobs.py
> +    text = get_reminder_text(job_data, consultation_count)
```suggestion
    text = get_reminder_text(job_data, **consultation_count)
```
Благодаря изменениям в функции get_reminder_text и get_consultations_count мы сможем просто разворачивать словарь при вызове функции

2022-10-18 19:35 UTC, cianoid commented on src/jobs.py
> +        message = get_reminder_text(consultations[0], consultations_count)
```suggestion
        message = get_reminder_text(consultations[0], **consultations_count)
```

2022-10-18 19:35 UTC, cianoid commented on src/jobs.py
> +            consultations, consultations_count["active"], consultations_count["expired"]
Тут надо будет тоже разворачивать словать **consultations_count**

2022-10-18 19:35 UTC, cianoid commented on src/service/api_client/site_api_service.py
> +    async def get_consultations_count(self, telegram_id: int) -> Dict:
Давай конкретизируем тип возвращаемых данных, укажем, что это словарь, где ключ str, а значение int

2022-10-18 19:35 UTC, cianoid commented on src/service/api_client/site_api_service.py
> +        }
Именна ключей должны быть **active_consultations_count, expired_consultations_count, expiring_consultations_count**

2022-10-18 19:35 UTC, cianoid commented on src/jobs.py
> +        expiring_consultations=expiring_cons_count,
А это где-то в шаблонах используется?
Если нет, то не надо передавать **expiring_consultations** в функцию. Но тогда нужно дописать ****kwargs**

2022-10-18 19:35 UTC, cianoid commented on src/jobs.py
> +    cons_count: Dict,
И в get_overdue_reminder_text нужно будет тоже прописать 
**active_consultations_count: int, expired_consultations_count: int, **kwargs**

2022-10-18 19:35 UTC, cianoid commented on src/run_webhook_api.py
> +    expired_cons_count = consultations_count["expired"]
Давай переименуем переменные, чтобы были одинаковые везде
**active_consultations_count, expired_consultations_count, expiring_consultations_count**

2022-10-19 05:03 UTC, cianoid commented on src/service/api_client/site_api_service.py
> +            "expiring": len(active_cons.expiring_consultations_data),
Посмотри пожалуйста в swagger - https://api-ask-nnyp.klbrtest.ru/__docs-ask/#/tgbot/get_tgbot_stat_active_user__telegram_id_

Там самые актуальные данные

2022-10-20 04:55 UTC, cianoid approved these changes

2022-10-20 04:55 UTC, cianoid commented on src/jobs.py
> +    consultations: List, active_consultations_count: int, expired_consultations_count: int, kwargs: Dict
****kwargs** - как на 267-й строчке

2022-10-20 23:07 UTC, AntonZelinsky approved these changes

2022-10-20 23:07 UTC, AntonZelinsky commented on src/service/api_client/site_api_service.py
> +        }
Тут какая-то ерунда.
Метод `get_user_expired_consultations` возвращает объект класса `UserExpiredConsultations`, а потом это превращается в словарь и дальше уже идёт работа со словарём. Зачем? Если нужно изменить поля данных и/или просто, то просто расширь или создай новую модель данных и всё, дописав необходимым значением. 
Работать со словарём — это практически всегда будет худшей идеей чем с объектами  класса.

![image](https://user-images.githubusercontent.com/1431279/197001744-58e027ef-d6a5-4385-ad18-e472f2e4aa8d.png)

2022-10-25 18:05 UTC, cianoid commented
@NVTaranets , ты тут?
Есть мысли как реализовать, написанное Антоном?

2022-10-25 20:10 UTC, NVTaranets commented
@cianoid Я тут, чуть выше отвечал Антону:
![image](https://user-images.githubusercontent.com/38173712/197871783-bd494ff2-aa9e-4dd3-8357-2b8d972c21c0.png)

2022-10-26 05:23 UTC, cianoid commented
@NVTaranets я слепой) Можешь ссылку на сообщение приложить?

2022-10-26 07:23 UTC, NVTaranets commented on src/service/api_client/site_api_service.py
> +            "expiring": len(active_cons.expiring_consultations_data),
Понятно. Заодно поправил
@dataclass_json
@dataclass(frozen=True)
class UserActiveConsultations:
на предмет нового параметра...

2022-10-26 07:23 UTC, NVTaranets commented on src/service/api_client/site_api_service.py
> +        }
Не знаю уместен ли вопрос в рамках решения этой задачи, но мне непонятно почему разделены вообще ендпоинты заявок активных и просроченных. Просроченная заявка ведь тоже активная (разве что супер статус имеющая). Из за этого отчасти и складывается та ситуация что мы имеем. Понятно, что заявки просроченные идут отдельными джобами в оповещение, но почему их исключили из активных заявок не понятно. Может это было бы не плохо исправить? 
Для формирования текста сообщения о новой завке все данные из этих двух эндпоинтов не нужны. Требуются только количественные значения по каждой из категорий. Я правильно понял, что ты предлагаешь создать

@dataclass(frozen=True)
class ConsultationsCount:
    active_consultations_count: int
    expiring_consultations_count: int
    expired_consultations_count: int
И уже его возвращать из функции get_consultations_count вместо словаря который сделан сейчас?

2022-10-26 08:23 UTC, NVTaranets commented
@cianoid @AntonZelinsky https://github.com/Studio-Yandex-Practicum/ask_nenaprasno_bot/pull/188#discussion_r1004642996

2022-10-26 16:04 UTC, AntonZelinsky commented on src/service/api_client/site_api_service.py
> +        }
Очень хороший вопрос и меня он тоже мучает) Отчасти, это одна из причин, почему я хочу избавиться от апишки.

2022-10-26 16:43 UTC, NVTaranets commented on src/service/api_client/site_api_service.py
> +        }
Это опять же вроде бы не по статусу вопрос, но отправить бот в базу за данными и отказаться от АПИ это:

1. создать предпосылку для утечки данных критических с точки зрения самого объекта задачи
2. связать по рукам и ногам проектировщиков бекенда сайта (любые изменения модели могут сломать бот)
3. привязать два сервиса к работе в одном пространтве (либо выставить базу наружу смотри пункт1)
4. лишить возможности в будущем сделать мобильные приложения для докторов и возможно клиентов
Может стоит просто доправить нелогичности API?

2022-10-26 17:18 UTC, AntonZelinsky commented on src/service/api_client/site_api_service.py
> +        }
Перенёс дискуссию в слек

2022-10-28 16:07 UTC, merged