## Ticket - [Установка часового пояса + диалоги бота к нему](https://www.notion.so/7d6d35f407814742a0cebea1e480bd4b?p=599621be7b1f47e19470172398a5db7e)
Studio-Yandex-Practicum/ask_nenaprasno_bot pull request #19
Opened 2022-06-21 11:17 UTC by KaterinaSolovyeva

Сделала две кнопки объекта ReplyKeyboard:

- 'Отправить свою геолокацию для автоматической настройки часового пояса' - получает гелолокацию, по ней определяет таймзону. Передача по апи пока закомментировала(чтобы не забыть), так как апи пока не готово.

- 'Напишу свою таймзону сам' - распознает введенный текст. Проверяет, существует ли такая таймзона. Если да, то передает её через апи. Если нет, то проверяет, не является ли введенный текст тем, на который отвечать не нужно. Просит пользователя ввести  другую таймзону или выслать геолокацию.

После получения таймзоны меню внизу исчезает

2022-06-21 23:15 UTC, AntonZelinsky commented on src/constants/text_constants.py
> +RHETORICAL_TEXT = ("Напишу свою таймзону сам",)
Пока не будем выносить в отдельный файл. Потом кто-то возьмёт задачу и всё вынесет туда. Я сегодня это уже второй раз пишу. У каждого своя идея как лучше сделать и каждый параллельно и по своему её реализует)

2022-06-23 08:37 UTC, veselij requested changes
привет, немного логика поехала. надо подправить, подключать твой диалог пока никуда не надо. надо просто его описать. позже мы его подключим в диалог start и как обработчики нажатия кнопки меню "установить таймзону".

так же надо устранить конфликты с веткой develop

2022-06-23 08:37 UTC, veselij commented on src/bot.py
> +async def start(update: Update, context: CallbackContext) -> None:
а почему название start, это же не начало работы с ботом, надо подумать над названием

2022-06-23 08:37 UTC, veselij commented on src/bot.py
> +    )
если это диалог то он должен устанавливать какой-то state, чтобы мы могли отдельно обработать эти запросы

2022-06-23 08:37 UTC, veselij commented on src/bot.py
> +async def get_timezone(update: Update, context: CallbackContext):
я бы в название дописал _from_location

2022-06-23 08:37 UTC, veselij commented on src/bot.py
> +    if update.message.location is not None:
а зачем эта проверка, если мы в хендлере фильтруем что это локейшен? а если уж делаешь проверку, то что будет если location None?

2022-06-23 08:37 UTC, veselij commented on src/bot.py
> +async def selected_text(update: Update, context: CallbackContext) -> None:
из названия не понятно, что делает функция, лучше get_timezone_from_text_message

2022-06-23 08:37 UTC, veselij commented on src/bot.py
> +    except zoneinfo.ZoneInfoNotFoundError:
лучше поднять экспт над send_message. чем меньше строк внутри try except тем лучше

2022-06-23 08:37 UTC, veselij commented on src/bot.py
> +        if str(update.message.text) not in text_constants.RHETORICAL_TEXT:
очень странная проверка, что она делает не пойму

2022-06-23 08:37 UTC, veselij commented on src/bot.py
> +    bot_app.add_handler(CommandHandler("start", start))
не надо сюда добавлять. мы должны добавить этот диалог как поддилог в диалог при начале работы с ботом и также в действия по кнопке меню установить таймзону. сейчас ты просто регистрирует команду бота старт как установку таймзоны

2022-06-23 08:37 UTC, veselij commented on src/bot.py
> +    bot_app.add_handler(MessageHandler(filters.LOCATION, get_timezone))
тоже надо прописывать в твоем диалоге, сейчас ты на любое текстовые сообщение которые отправит пользователь в чате вызываешь обработчик selected_text, что не правильно. аналогично с lcoation

2022-06-23 08:55 UTC, KaterinaSolovyeva commented on src/bot.py
> +async def selected_text(update: Update, context: CallbackContext) -> None:
объединила в 1 хэндлер фильтры location и text. Назвала get_timezone_from_location

2022-06-23 08:57 UTC, KaterinaSolovyeva commented on src/bot.py
> +    except zoneinfo.ZoneInfoNotFoundError:
Получается тогда даже если будет ошибка, выведется сообщение, что Установлен часовой пояс

2022-06-23 08:59 UTC, KaterinaSolovyeva commented on src/bot.py
> +        if str(update.message.text) not in text_constants.RHETORICAL_TEXT:
проверяет, что текст - не написан ботом. Без этой проверки получится такое, например, сообщение бота:
Часового пояса "Напишу свою таймзону сам" нет.

2022-06-23 10:14 UTC, KaterinaSolovyeva commented on src/bot.py
> +    )
подожду, когда Айгуль закончит со состояниями, и использую их

2022-06-23 10:16 UTC, KaterinaSolovyeva commented on src/bot.py
> +    bot_app.add_handler(CommandHandler("start", start))
подожду, когда Айгуль закончит с состояниями и внесу туда. А пока вынесла всё в отдельный файл.
кнопка меню формируется при /start

2022-06-23 10:16 UTC, KaterinaSolovyeva commented on src/bot.py
> +    bot_app.add_handler(MessageHandler(filters.LOCATION, get_timezone))
согласна, поправлю после мерджа с кодом Айгуль, где она пишет состояния и диалог

2022-06-28 07:42 UTC, closed without merging