Feature/logs
Studio-Yandex-Practicum/ask_nenaprasno_bot pull request #196
Opened 2022-10-26 05:42 UTC by 4u3o

Логирование работы бота
[Notion](https://www.notion.so/DEBUG-be7b241326524ccc9e24e70272824586)

2022-10-26 18:11 UTC, cianoid requested changes
Надо вмержить develop в ветку и допилить

2022-10-26 18:11 UTC, cianoid commented on src/bot.py
> +        logger.debug("Remove %s from queue", job.__name__)
Возможно, я хочу избыточности, но мне кажется, что нужно вот так
```        
logger.debug("About to remove job %s from queue", job.__name__)
job.schedule_removal()
logger.debug("Job %s removed from queue", job.__name__)
```

То есть, мы сначала пишем намерение что-то сделать, а затем делаем и после этого пишем, что сделано. Если что-то посередине будет сыпать в лог, то понятно почему.
Если команда уронит бот наглухло (к примеру), то последнее сообщение в логе нам расскажет, что бот сделал

2022-10-26 18:11 UTC, cianoid commented on src/bot.py
> +    logger.debug("Set webhook. App url: %s", config.APPLICATION_URL)
Аналогично предыдущему сообщению. 
![изображение](https://user-images.githubusercontent.com/46224693/198099494-1eda41d3-4ebb-4fbc-bb1f-d060f64e0c35.png)
На картинке пример лога. Я сделал два кейса: поломал имя урла и текущая версия ничего не написала в лог. Во втором кейсе я добавил логирование до запуска вебхука, он в лог и попал.

Как всегда, открыт к дискуссии

2022-10-26 18:11 UTC, cianoid commented on src/decorators/logger.py
>  def async_error_logger(name):
Если ниже тайпингов понаписал, то и здесь можно)

2022-10-26 18:11 UTC, cianoid commented on src/decorators/logger.py
> +        logger.debug("Run %s", func.__name__)
Подпиши, что это джоба, чтобы проще искать было в логе

2022-10-26 22:59 UTC, 4u3o commented on src/bot.py
> +        logger.debug("Remove %s from queue", job.__name__)
Так можно очень далеко зайти, код читать будет не возможно.

2022-10-26 23:07 UTC, 4u3o commented on src/decorators/logger.py
> +        logger.debug("Run %s", func.__name__)
Утилита ищет по отдельным словам или по фрагментам слова тоже?

2022-10-27 01:00 UTC, 4u3o commented on src/bot.py
> +        logger.debug("Remove %s from queue", job.__name__)
Не понимаю, какая может возникнуть проблема с удалением найденной джобы из очереди?
Запуск хендлера done_bill_callback_handler будет в логе
```
2022-10-27 10:57:35,895 DEBUG core.logger:      User 306514684 run done_bill_callback_handler
2022-10-27 10:57:35,896 DEBUG core.logger:      Remove send_306514684_bill_until_complete from queue
```

2022-10-27 01:24 UTC, 4u3o commented on src/bot.py
> +    logger.debug("Set webhook. App url: %s", config.APPLICATION_URL)
Мне кажется трейсбэк в консоли довольно красноречиво скажет, в чем проблема. А что нам даст лишняя строчка в логах?

2022-10-27 03:17 UTC, cianoid commented on src/decorators/logger.py
> +        logger.debug("Run %s", func.__name__)
Что хочешь ищет. Я понял о чем ты. Но это справедливо, если в названии джобы есть слово job. А если нет?
`# man grep`

2022-10-27 03:19 UTC, cianoid commented on src/bot.py
> +    logger.debug("Set webhook. App url: %s", config.APPLICATION_URL)
Трейсбек будет в консоли контейнера, которые перезапустят и потеряют все что было в консоле. Конечно, конкретно в этом случае - по-барабану, так как бот вообще не запустится. Но есть же и другие варианты возникновения ошибок

2022-10-27 03:25 UTC, cianoid commented on src/bot.py
> +        logger.debug("Remove %s from queue", job.__name__)
Тут согласен. В тех местах, где ничего 100% не может случится, можно не делать избытычность

Кстати как понять по логу, что это джоба?

2022-10-27 03:42 UTC, 4u3o commented on src/bot.py
> +        logger.debug("Remove %s from queue", job.__name__)
по кодстайлу в названии джобы должно быть слово job

2022-10-28 09:54 UTC, 4u3o commented on src/bot.py
> +    logger.debug("Set webhook. App url: %s", config.APPLICATION_URL)
Теперь трейсбек будет в логах

2022-11-04 08:20 UTC, cianoid approved these changes

2022-11-05 01:19 UTC, AntonZelinsky approved these changes
Сложно, конечно, ничего не понимаю, но вроде как должно работать

2022-11-05 01:19 UTC, AntonZelinsky commented on src/core/config.py
> +LOG_PATH = BASE_DIR / ".." / "logs" / "bot.log"
```suggestion
LOG_PATH = BASE_DIR.parent / "logs" / "bot.log"
```

2022-11-05 01:19 UTC, AntonZelinsky commented on src/decorators/logger.py
> +                logger.debug("User %s run %s", update.effective_user.id, func.__name__)
А почему бы не получать апдейт в трае? Вдруг упадёт?

2022-11-08 19:26 UTC, merged