Added synchronize option to pull request trigger to trigger on commit…
Studio-Yandex-Practicum/ask_nenaprasno_bot pull request #199
Opened 2022-11-01 13:58 UTC by malyshevadv

…(s) pushed to the pull request

2022-11-02 12:23 UTC, AntonZelinsky approved these changes

2022-11-02 12:23 UTC, AntonZelinsky commented on .github/workflows/bot_productivity.yaml
> +      - [ opened, synchronize ]
А что это значит?

2022-11-02 13:32 UTC, malyshevadv commented on .github/workflows/bot_productivity.yaml
> +      - [ opened, synchronize ]
Это означает, что воркфлоу будет запускаться для ПР, когда кто-то пушит в него коммит, посмотрела описание вот тут: https://frontside.com/blog/2020-05-26-github-actions-pull_request/
synchronize:	commit(s) pushed to the pull request
Выглядит как раз как наш случай, когда мы хотим, чтобы воркфлоу работал при каждом внесении изменения в ПР, а не только по его открытию

2022-11-02 15:58 UTC, cianoid requested changes
Не работает
https://github.com/Studio-Yandex-Practicum/ask_nenaprasno_bot/actions/runs/3369973030

2022-11-02 16:02 UTC, cianoid commented on .github/workflows/bot_productivity.yaml
> +      - [ opened, synchronize ]
Тут можно 
```
types:
  - opened
  - synchronize

```
или
```
types: [opened, synchronize]
```

2022-11-02 16:35 UTC, malyshevadv commented on .github/workflows/bot_productivity.yaml
> +      - [ opened, synchronize ]
Есть какое то предпочтение по форматингу?

2022-11-02 17:38 UTC, cianoid commented on .github/workflows/bot_productivity.yaml
> +      - [ opened, synchronize ]
Мне предпочтителен первый вариант

2022-11-03 04:37 UTC, cianoid approved these changes

2022-11-04 08:18 UTC, merged