Исправлена обработка зоны UTC и все связанные с этим баги
Studio-Yandex-Practicum/ask_nenaprasno_bot pull request #205
Opened 2022-11-11 18:20 UTC by malyshevadv

Fixed processing of the UTC timezone; corrected message when the timezone is set via location.
Notion: 
[[Баг] Не приходят уведомления, связанные с таймзонами, при выставленной UTC +00:00](https://www.notion.so/UTC-00-00-beb661e287fa4ddca29d59bca83a554a)
[[Баг] При расшаривании геолокации выходит сообщение "Вы настроили часовой пояс UTC +0300 ..." - не хватает двоеточия](https://www.notion.so/UTC-0300-7fa8938a32664d2f8c9d574df19b2bee)
[[Баг] Можно выставить таймзоны UTC -13 и UTC -14](https://www.notion.so/UTC-13-UTC-14-6768f39bd4bf4b08bfad9c693627602a)
[[Баг] При выставлении UTC +00:00 неверно отображается текущая таймзона в строке меню "Настроить часовой пояс(сейчас UTC XX:XX). Вместо 00:00 там таймзона, которая была выставлена до этого](https://www.notion.so/UTC-00-00-UTC-XX-3069ab84e68a4a19af1cd36e46fd7486)

2022-11-12 01:53 UTC, AntonZelinsky approved these changes

2022-11-13 18:33 UTC, cianoid requested changes
Блин, написал коммент, а не сабмитнул(((

Кажется, стоит учесть эти часовые пояса. В любом случае, есть еще пояса с минутами. Стоит нам заморчиваться и валидировать каждый? Вопрос.

2022-11-13 18:33 UTC, cianoid commented on src/get_timezone.py
> +    tz_pattern = r"^(UTC)?(?P<sign>[-+]?)(?P<hours>(0?[0-9])|(1[0-2]))?(:(?P<minutes>0{1,2}|30|45))?$"
Есть часовые пояса +14, +13

2022-11-14 08:20 UTC, malyshevadv commented on src/get_timezone.py
> +    tz_pattern = r"^(UTC)?(?P<sign>[-+]?)(?P<hours>(0?[0-9])|(1[0-2]))?(:(?P<minutes>0{1,2}|30|45))?$"
Тут немного спорно - технически, такие часовые пояса конечно существуют, но также у нас в сообщении обозначено, что мы ожидаем часовые пояса, которые имеют место на территории России...
Кроме того, часовые пояса +13 и +14 это чисто для островов Тихого Океана... Я, конечно, могу все вернуть, но не уверена, насколько они нам нужны :)

2022-11-14 08:54 UTC, cianoid commented on src/get_timezone.py
> +    tz_pattern = r"^(UTC)?(?P<sign>[-+]?)(?P<hours>(0?[0-9])|(1[0-2]))?(:(?P<minutes>0{1,2}|30|45))?$"
Спорно, согласен. Но мы же не можем врачу провести консультации с личного острова в тихом океане...
Честно, я не знаю как лучше сделать

2022-11-14 09:14 UTC, malyshevadv commented on src/get_timezone.py
> +    tz_pattern = r"^(UTC)?(?P<sign>[-+]?)(?P<hours>(0?[0-9])|(1[0-2]))?(:(?P<minutes>0{1,2}|30|45))?$"
Поправила, добавив небольшую проверку. Пусть доктора помогают и с личных островов!

2022-11-14 09:22 UTC, cianoid approved these changes

2022-11-14 09:22 UTC, merged