Added context model with pydantic
Studio-Yandex-Practicum/ask_nenaprasno_bot pull request #210
Opened 2022-11-18 16:32 UTC by malyshevadv

Notion: [Переделать модель ClosedConsultationModel на pydantic](https://www.notion.so/ClosedConsultationModel-pydantic-c2066d9d85cd4d2fab8c3b7b061ec3e6)

Открываю PR для обсуждения.
Я не уверена, что правильно поняла поставленную задачу. 
Класс реализовала в файле  /src/api/context_models.py, изменила в [https://github.com/Studio-Yandex-Practicum/ask_nenaprasno_bot/blob/93d04860fcf0f494e4ff6850b160ba939347e5f5/src/run_webhook_api.py#L135](https://github.com/Studio-Yandex-Practicum/ask_nenaprasno_bot/blob/93d04860fcf0f494e4ff6850b160ba939347e5f5/src/run_webhook_api.py#L135)

Однако, изменения не позволяют избавиться от ранее используемой функции deserialize - она заменяется на async def request_to_context - в этой функции идет преобразование из объекта Request (https://www.starlette.io/requests/) в json-объект и далее в контекст (можно это вынести, но не вижу смысла) + проверки, что преобразование происходит нормально.

2022-11-18 16:39 UTC, malyshevadv commented on src/run_webhook_api.py
> +async def request_to_context(request: Request, context):
Эта функция заменяет функцию выше [deserialize](https://github.com/Studio-Yandex-Practicum/ask_nenaprasno_bot/blob/34f9a7a94552bcfd5d28c643f817cf53835b29bf/src/run_webhook_api.py#L87) -  в этой функции идет преобразование из объекта Request (https://www.starlette.io/requests/) в json-объект и далее в контекст + проверки и логгирование, что преобразование происходит нормально или не нормально. Не уверена, есть ли смысл вынести эту функцию - я думала, что в принципе ее можно перенести в файл [/src/api/context_models.py](https://github.com/Studio-Yandex-Practicum/ask_nenaprasno_bot/pull/210/files#diff-4b6fab70dd4d3d5e95fdedc38550b6e548c2a31b1b2b12d47121249f5102a846), но тогда туда утягиваются получаемые данные в формате объекта Request (https://www.starlette.io/requests/), что выглядит не слишком корректно

2022-11-18 16:41 UTC, malyshevadv commented on .pylintrc
> +extension-pkg-whitelist=pydantic
Добавдлено из-за "pylint: No name 'BaseModel' in module 'pydantic' (no-name-in-module) " - см. https://github.com/pydantic/pydantic/issues/1961

2022-11-18 16:55 UTC, AntonZelinsky approved these changes

2022-11-18 16:55 UTC, AntonZelinsky commented on src/api/context_models.py
> +# pylint: disable=R0903
А разве это не делает то же самое что и `extension-pkg-whitelist=pydantic`. По ссылке что ты прислала написано, что вроде как та штука решает эту проблему

2022-11-18 16:55 UTC, AntonZelinsky commented on src/run_webhook_api.py
>          return Response(status_code=httpx.codes.BAD_REQUEST)
Мне кажется, это не нужно делать, так как ты проглатываешь ошибку и клиент апи никогда не узнает почему упало.
И BadRequestError сам же должен преобразовываться в ошибку со статусом httpx.codes.BAD_REQUEST, нет?

2022-11-18 16:55 UTC, AntonZelinsky commented on src/run_webhook_api.py
> +async def request_to_context(request: Request, context):
Я считаю, что как временный хак это сойдёт, когда мы переделаем так все апишки, мы сразу мигрируем на fastapi, который будет делать это уже под капотом.
Вообще, можно подумать над заменой этой функции на декоратор для методов, чтобы на вход приходила уже готовая модель контекста, но вообще, можно не заморачиваться, через неделю мигрируем на файт апи

2022-11-18 17:04 UTC, malyshevadv commented on src/api/context_models.py
> +# pylint: disable=R0903
Она решает для самой модели, но не для class Config, который является подклассом модели - pylint на него ругается  без этого отключения

2022-11-18 17:12 UTC, malyshevadv commented on src/run_webhook_api.py
>          return Response(status_code=httpx.codes.BAD_REQUEST)
В request_to_context ошибки ловятся и записываются в лог, поэтому информация о сути ошибки будет как минимум на стороне бота. 

Здесь мы просто возвращаем ответ Starlette и его нужно возвращать, если его не возвращать, то выпадает ошибка и сервер отвечает HTTP/1.1 500 Internal Server Error. 
Возможно, в Starlette можно что-то дополнительно сделать, чтобы BadRequestError сам превращался в Response вида BAD_REQUEST, но это тема отдельной задачи

2022-11-18 17:24 UTC, AntonZelinsky commented on src/run_webhook_api.py
>          return Response(status_code=httpx.codes.BAD_REQUEST)
Можно [добавить глобальный перехватчик](https://www.starlette.io/exceptions/). Предлагаю так и сделать. Возвращай респонс с кодом бэд реквеста и всю инфомрацию из самой ошибки

2022-11-19 14:54 UTC, malyshevadv commented on src/run_webhook_api.py
>          return Response(status_code=httpx.codes.BAD_REQUEST)
Сделала, и благодаря такому изменению у нас уходит использование собственного Exception из https://github.com/Studio-Yandex-Practicum/ask_nenaprasno_bot/blob/0e66e9f0f97ed82888eefab29d1c80706adc47a9/src/core/exceptions.py#L13

2022-11-22 04:55 UTC, cianoid commented
Там в первой строчке src/run_webhook_api.py стоит комментарий: `# pylint: disable=W0612`
Предлагаю его убрать и закоментировать те места, где он срабатывает. У меня сработал на строчках 52 и 161

2022-11-22 05:10 UTC, cianoid requested changes

2022-11-22 05:10 UTC, cianoid commented on src/api/context_models.py
> +# pylint: disable=R0903
Предлагаю перенести исключение. От глобальных исключения для pylint лучше избавляться. А то потом, оно само может уйти, но мы не обратим внимание на это, потому что неизвестно для чего оно было применено

2022-11-22 05:10 UTC, cianoid commented on src/api/context_models.py
> +    class Config:
```suggestion
    class Config:  # pylint: disable=R0903
```

2022-11-22 05:10 UTC, cianoid commented on src/run_webhook_api.py
>  from service.models import (
Мы обсуждали, что лучше делать импорты модуля, а не его составляющих:

`from service import models`

2022-11-22 05:10 UTC, cianoid commented on src/run_webhook_api.py
> +async def request_to_context(request: Request, context):
**фаст** :D

2022-11-22 05:11 UTC, cianoid approved these changes

2022-11-22 16:51 UTC, malyshevadv commented
> ам в первой строчке src/run_webhook_api.py стоит комментарий: `# pylint: disable=W0612`
> Предлагаю его убрать и закоментировать те места, где он срабатывает. У меня сработал на строчках 52 и 161
У меня вообще не ругнулось, все прошло и без него. И в коде я не вижу неиспользуемых переменных, может это раньше было.

2022-11-22 17:42 UTC, cianoid approved these changes

2022-11-22 17:43 UTC, cianoid commented
Вообще странно, что не ругнулся - у меня вот ругнулся)
Может аффектнуть в будущем, но, действительно, не будет исключать варнинг пока pylint пропускет

2022-11-22 17:43 UTC, merged