Create separate file for routes
Studio-Yandex-Practicum/ask_nenaprasno_bot pull request #217
Opened 2022-12-14 12:53 UTC by KseniyaGurevich

2022-12-14 15:39 UTC, AntonZelinsky commented on pyproject.toml
> +constants = "^0.6.0"
А зачем это было добавлено? да и что-то я не вижу, где оно используется!

2022-12-15 04:28 UTC, cianoid requested changes
`ImportError: cannot import name 'routes' from partially initialized module 'api.routes' (most likely due to a circular import) (/Users/cianoid/Projects/YandexPracticum/ask_nenaprasno_bot/src/api/routes.py)
`
@KseniyaGurevich рекомендую сперва запустить бота у себя, а потом отправлять на ревью

2023-01-10 14:10 UTC, cianoid commented
@KseniyaGurevich резолвни пожалуйста конфликты и мосмотри мой прошлый Changes request - его надо отметить, что он сделан

2023-01-10 16:21 UTC, KseniyaGurevich commented
@cianoid Как отметить, что твой прошлый Changes request сделан?

2023-01-10 16:55 UTC, cianoid approved these changes

2023-01-10 16:56 UTC, cianoid commented
@KseniyaGurevich не нашел... нажал approve - но посмотрю код завтра еще утром

2023-07-21 12:03 UTC, Cyberboson approved these changes

2023-07-21 15:37 UTC, merged