added new entry point
Studio-Yandex-Practicum/ask_nenaprasno_bot pull request #221
Opened 2022-12-28 08:22 UTC by Sumchatyj

Добавил новую точку входа, сочетающую поллинг и апи. Код почти полностью копирует run_webhook, но мне кажется, что связывать точки входа будет не очень практично.

2022-12-29 00:26 UTC, AntonZelinsky requested changes
Так, вот второй файл в таком виде нам точно не нужен. Зачем в пустую дублировать код?
Вообще, давай сделаем флаг в .env и будем его проверять при запуске приложения и если там указано, что вебхук, то запускается на вебхуках, если пулинг, то на пулинге

2022-12-29 04:26 UTC, Sumchatyj commented
Смогу завтра сделать.
С флагом вроде понятно, а с кодом поллинг+апи что делать в итоге? Все возможное импортировать из run_webhook?

2022-12-29 21:35 UTC, AntonZelinsky commented
Давай попробуем сделать через флаг, если всё окей, то удаляем этот код, поскольку это костыль.

2022-12-30 01:18 UTC, Sumchatyj commented
Блин, оч сложно без созвонов)

Так, у нас в ПРе 3 реализации: поллинг, вебхук, поллинг+апи. Флаг, насколько я понимаю, подразумевает 2 состояния. Так как просто поллинг нам вроде не нужен - состояния будут следующими: вебхук и поллинг+апи, верно?

Если верно, то как лучше написать поллинг+апи? Он отличается от вебхука в функциях start и stop и в нем меньше роутов. Просто импортировать все, что можно из файла с вебхуком?

Надеюсь, смог понятно описать, что я не понял)

2022-12-30 07:15 UTC, AntonZelinsky commented
Значит устроим звонок, может сегодня, может после НГ.

Должно остаться 2 точки входа, просто бот, это скорее для тестов локально и апи+вебхук/пудинг режим, в зависимости от флага.
При запуске проверяется флаг и вызываются различные функции инициализации бота и если флаг вебхук, то добавляется дополнительно апи в роутер. Это моя идея.

А повтори ещё раз, в чём твоя идея?

2022-12-30 07:52 UTC, Sumchatyj commented
Да, давайте после НГ.

А моя идея была в том, что я тебя не понял), но теперь вроде все понятно стало, я приду в себя и вечером постараюсь реализовать твою идею и обновить PR!

2022-12-31 00:28 UTC, Sumchatyj commented
Смотри, я вроде сделал, как ты предлагал. Бот запускается файлом run_bot.py, и флагом run_webhook: bool = False. То бишь по умолчанию стартует в поллинге, если не указано обратное. Мне кажется так логичнее, потому что для поллинга не требуется APPLICATION_URL.

Но надо в любом случае менять настройки в докерфайле и workflows, я туда пока не лез.

2023-01-02 23:39 UTC, AntonZelinsky commented on src/bot/bot.py
> -    bot_app.run_polling()
Ты эту строку удалил, но нигде не добавил. То есть, пулигн не будет работать при вызове через эту функцию

2023-01-02 23:39 UTC, AntonZelinsky commented on src/run_bot.py
> +api = Starlette(
Давай пока оставим все эти изменения в том файле. а то вообще не понятно что ты изменил. + будет много конфликтов.

2023-01-02 23:56 UTC, Sumchatyj commented on src/bot/bot.py
> -    bot_app.run_polling()
У меня просто старт пулинга уехал в run_bot.py, но действительно лучше перенести в эту функцию все, сделаю.

2023-01-02 23:58 UTC, Sumchatyj commented on src/run_bot.py
> +api = Starlette(
Перенести все в файл run_webhook, чтоб все стартовало при старых настройках докера и воркфлоу?

2023-01-03 00:00 UTC, AntonZelinsky commented on src/run_bot.py
> +api = Starlette(
Да, по идее, всё взлетит без каких-то изменений в воркфловах, просто запустится на пулинге.

2023-01-03 04:34 UTC, Sumchatyj commented
Вроде бы все сделал, запускается)

2023-01-03 10:10 UTC, AntonZelinsky commented on src/bot/bot.py
> +    await bot_app.start()
А почему этих строк нет в функции init_polling выше? И в чём различие между этими двумя функциями?

При старте через вебхуки ты вызываешь их на уровне файла запуска, а эти тут.
Что вообще этих функций? и проверь в исходниках библиотеки бота, что при вызове старт пулинг они не вызываются, такое тоже возможно.
![image](https://user-images.githubusercontent.com/1431279/210336695-3e265953-2b86-4d9e-b176-80a4406a88d1.png)

2023-01-03 13:36 UTC, Sumchatyj commented on src/bot/bot.py
> +    await bot_app.start()
А можно тебе как-нибудь куда-нибудь набрать, так будет намного проще, мне кажется)

2023-01-18 16:38 UTC, AntonZelinsky approved these changes

2023-01-18 17:02 UTC, cianoid approved these changes
Есть еще один момент, который можно будет потом поправить: разобраться с файлами, а то запускаем run_webhook_api, но в поллинге - но это обсуждалось на звонке.

2023-01-18 17:02 UTC, cianoid commented on src/run_webhook_api.py
> +        await bot_app.start()
Может эти две строчки запихнуть в init_webhook?

2023-01-18 17:02 UTC, cianoid commented on src/run_webhook_api.py
> +    if not settings.run_webhook:
Стоит добавить логирование, что бот остановлен

2023-01-18 17:04 UTC, cianoid commented
Саш, еще стоит поправить сразу экшн bot_productivity

По идее, там должно быть что-то такое:

```
RUN_WEBHOOK=False python3 src/run_webhook_api.py & sleep 15 && pkill -9 python
RUN_WEBHOOK=True python3 src/run_webhook_api.py & sleep 15 && pkill -9 python

```

2023-01-18 17:23 UTC, malyshevadv approved these changes

2023-01-18 17:29 UTC, merged