Get timezone from menu button
Studio-Yandex-Practicum/ask_nenaprasno_bot pull request #24
Opened 2022-06-23 11:13 UTC by KaterinaSolovyeva

## Ticket - [Установка дефолтных кнопок для телеграма](https://www.notion.so/7d6d35f407814742a0cebea1e480bd4b?p=9f3edd440b0a4ffca5d77f5e695a2870)
добавлена кнопка Меню, из которой можно перейти в список доступных запросов либо установить часовой пояс

## Ticket - [Установка часового пояса + диалоги бота к нему](https://www.notion.so/7d6d35f407814742a0cebea1e480bd4b?p=599621be7b1f47e19470172398a5db7e)

При запросе на присвоение нового часового пояса появляются две кнопки объекта ReplyKeyboard:
'Отправить свою геолокацию для автоматической настройки часового пояса' - получает гелолокацию, по ней определяет таймзону. Передает по апи
'Напишу свою таймзону сам' - распознает введенный текст. Проверяет, существует ли такая таймзона. Если да, то передает её через апи. Если нет, то проверяет, не является ли введенный текст тем, на который отвечать не нужно. Просит пользователя ввести другую таймзону или выслать геолокацию.
После получения таймзоны кнопки ReplyKeyboard внизу исчезают

2022-06-23 14:22 UTC, MatMerd requested changes

2022-06-23 14:22 UTC, MatMerd commented on requirements.txt
> -anyio==3.6.1
А как так получилось, что requirements перезаписался?

2022-06-23 14:22 UTC, MatMerd commented on src/bot.py
> -from telegram import Update
Опять странно. Перезаписался целый файл, а должна была поменяться одна строка, насколько я вижу

2022-06-23 14:22 UTC, MatMerd commented on src/get_timezone.py
> +RHETORICAL_TEXT = ("Напишу свою таймзону сам", "Отправить свою геолокацию для автоматической настройки часового пояса")
Мне кажется, это должны быть две разные константы, а не кортеж

2022-06-23 14:22 UTC, MatMerd commented on src/get_timezone.py
> +async def get_timezone_from_location(update: Update, context: CallbackContext):
Это получается очень большая и громоздкая функция. Её можно разбить на три части, как минимум:
1. Основная, которая отвечает за отправку таймзоны в апи фронта
2. Функция, которая определяет тайм зону из местоположения
3. Функция, которая определяет таймзону из текста

2022-06-23 14:22 UTC, MatMerd commented on src/get_timezone.py
> +            if text not in RHETORICAL_TEXT and set("/").isdisjoint(text):
Не понимаю первую часть условия. Как текст может входить в этот кортеж?

2022-06-23 14:22 UTC, MatMerd commented on src/get_timezone.py
> +            zoneinfo.ZoneInfo(text)
В данном варианте получается, что человеку нужно четко знать, какая у него таймзона и как она пишется. Например, я понятия не имею, что напишу, если окажусь в Бразилии. Нужен более элегантный механизм получения часового пояса. Можно подумать в сторону того, что человек может вводить текущее время, мы находим разницу по часам с москвой (или с гринвичем) и от этого уже считаем часовой пояс. Формат времени у всех одинаковый

2022-06-23 14:22 UTC, MatMerd commented on src/get_timezone.py
> +        api = RealAPIService()
У нас есть реализация фейкового сервиса. Использование просто RealAPIService это черевато, пока он не готов. Посмотри как использовать разные реализации сервиса в src/service/__init__.py

2022-06-23 14:32 UTC, KaterinaSolovyeva commented on src/get_timezone.py
> +            if text not in RHETORICAL_TEXT and set("/").isdisjoint(text):
когда пользователь нажимает на вторую кнопку "Напишу свою таймзону сам", то бот читает ее как ответ и пишет: "Часового пояса "Напишу свою таймзону сам" нет. Попробуйте написать другой или передайте геолокацию для его автоматического определения". А нужно, чтобы просто пропустил эту фразу и мы могли ввести часовой пояс руками

2022-06-23 14:35 UTC, MatMerd commented on src/get_timezone.py
> +            if text not in RHETORICAL_TEXT and set("/").isdisjoint(text):
А можно же сделать так, что после "Напишу свою таймзону сам, пользователю отправляется сообщение "Введите таймзону в формате <format>" и только после этого ожидать ввода таймзоны?

2022-06-23 14:37 UTC, KaterinaSolovyeva commented on src/get_timezone.py
> +            zoneinfo.ZoneInfo(text)
по условию Александра Минаева: "У пользователя должен быть выбор или расшарить геолокацию или ввести руками таймзону"
Поэтому первая кнопка - это тот самый элегантный способ)) получаем геолокацию и по ней считается таймзона. 
Уточни, нужно ли переделывать второй вариант все-таки?

2022-06-23 14:38 UTC, KaterinaSolovyeva commented on src/get_timezone.py
> +        api = RealAPIService()
да, тестила на нем, думала для проверки отправить все-таки реальный. Ок, поправлю

2022-06-23 14:40 UTC, KaterinaSolovyeva commented on src/bot.py
> -from telegram import Update
не знаю, к сожалению
Мои шаги:
git checkout -b feature/menu_button_timezone
git add --all
git commit -m "Get timezone from menu button"
git push --set-upstream origin feature/menu_button_timezone

2022-06-23 14:43 UTC, KaterinaSolovyeva commented on requirements.txt
> -anyio==3.6.1
Для определения таймзоны по локации я установила pip install timezonefinder[numba], он устанавливает дополнительные зависимости. Чтобы ничего не потерять, я добавила их все к requirements
Почему весь файл перезаписался не знаю..

2022-06-23 14:44 UTC, KaterinaSolovyeva commented on src/bot.py
> -from telegram import Update
после команды комита показали ошибки пре-комита, повторила add и commit перед пушем.
Что я сделала не так?

2022-06-23 14:46 UTC, MatMerd commented on src/get_timezone.py
> +            zoneinfo.ZoneInfo(text)
Давай позовём сюда Сашу и Антона. Я думаю, что именно этот момент тебе сейчас и не нужно будет переделывать
@AntonZelinsky @veselij

2022-06-23 14:51 UTC, MatMerd commented on src/bot.py
> -from telegram import Update
Ощущение, что во время разработки, ты случайно перезаписала файл в другой. Или неудачно сделала merge

2022-06-23 14:55 UTC, MatMerd commented on requirements.txt
> -anyio==3.6.1
Вот тут сразу оговоримся. Давай не будем тянуть в проект numba. Эта зависимость не самая простая и требует бо́льших знаний о её использовании, чем у нас есть.

2022-06-23 15:06 UTC, KaterinaSolovyeva commented on src/get_timezone.py
> +RHETORICAL_TEXT = ("Напишу свою таймзону сам", "Отправить свою геолокацию для автоматической настройки часового пояса")
в кортеже текст, на который бот не должен реагировать как на вариант часового пояса от пользователя

2022-06-23 15:27 UTC, veselij commented on src/get_timezone.py
> +            zoneinfo.ZoneInfo(text)
мы изначально отказались почему то от текущего времени, всякие пограничные состояния наверное редко, но все же могут быть, типа реально время 17:55, а человеку лень писать и он такой хоп 18 отправил. и это и парсить сложно и на час промахнуться можно. я думал таймзону отправлять в формате UTC+3 UTC+4 и т.д. и это в примере написать можно и раскрасить легко

2022-06-23 15:30 UTC, veselij commented on requirements.txt
> -anyio==3.6.1
я у себя пробовал когда запустить, у меня не встало, пришлось руками ставить и встала numpy на m1

2022-06-23 15:55 UTC, KaterinaSolovyeva commented on src/get_timezone.py
> +            if text not in RHETORICAL_TEXT and set("/").isdisjoint(text):
А что если так: "Введите таймзону. Например: Europe/Moscow" и к этой строке инлайн кнопка: 
 "посмотреть список всех таймзон в Википедии" - [ссылка на википедию](https://en.wikipedia.org/wiki/List_of_tz_database_time_zones)

2022-06-23 15:58 UTC, MatMerd commented on src/get_timezone.py
> +            if text not in RHETORICAL_TEXT and set("/").isdisjoint(text):
А сама бы ты как отнеслась к такому сервису? Я бы , например, очень негодовал. Особенно когда ты врач и хочешь войти в систему по рабочим вопросам.

2022-06-23 16:00 UTC, KaterinaSolovyeva commented on src/get_timezone.py
> +            zoneinfo.ZoneInfo(text)
о, теперь поняла! сделаю )

2022-06-23 19:50 UTC, AntonZelinsky commented on src/bot.py
> -from telegram import Update
нет, не в другой, там по другому отображается название файла. Попробуй смержить к себе ветку девелоп, а потом сделай ребейз к ветке девелоп

2022-06-23 19:53 UTC, AntonZelinsky commented on src/get_timezone.py
> +RHETORICAL_TEXT = ("Напишу свою таймзону сам", "Отправить свою геолокацию для автоматической настройки часового пояса")
Да и вообще, помещай текст внутрь кнопки, пока не нужно выносить во вне

2022-06-23 19:56 UTC, AntonZelinsky commented on src/get_timezone.py
> +            zoneinfo.ZoneInfo(text)
Можно даже просто `+3`, `-5`, `+9`. Так же, добавь кнопку поделиться геолокацией, она была в примерах к нашей библиотеке (ищи примеры с конверсейшенами) и кнопку `+3`.
Сторонние библиотеки точно не будем тянуть.

2022-06-23 19:58 UTC, MatMerd commented on src/bot.py
> -from telegram import Update
Антон наверное хотел написать сделать pull ветки девелоп, а потом сделать ребейз из своей ветки

2022-06-23 19:59 UTC, AntonZelinsky commented on src/get_timezone.py
> +            if text not in RHETORICAL_TEXT and set("/").isdisjoint(text):
Блин, я понял, Катя сделала KeyboardButton, а это такие серые кнопки, при нажатии на которую отправляется сообщение от имени пользователя. Не, мы такие кнопки использовать точно не будем, мы используем только инлайновые кнопки. В примерах с конверсейшенами такие тоже есть

2022-06-23 20:01 UTC, AntonZelinsky commented on src/get_timezone.py
> +get_timezone_from_location_handler = MessageHandler(filters.TEXT | filters.LOCATION, get_timezone_from_location)
И для обработки трёх вариантов дейстивия пользователей (нажатие инлайновой кнопки, ввода текста и отправки локации) нужно использовать три разные хэндлена! Тогда везде будет очень простой код

2022-06-23 20:02 UTC, MatMerd commented on src/get_timezone.py
> +            if text not in RHETORICAL_TEXT and set("/").isdisjoint(text):
Точно!
Спасибо, Антон

2022-06-24 11:59 UTC, KaterinaSolovyeva commented on src/get_timezone.py
> +            if text not in RHETORICAL_TEXT and set("/").isdisjoint(text):
Именно через серые кнопки можно получить геолокацию пользователя. У пользователя всплывает окошко с запросом к нему на разрешение получения его геолокации. Поэтому я использовала именно их для этого.
[KeyboardButton('Отправить свою геолокацию для автоматической настройки часового пояса', **request_location=True**)]
Почему мы не будем использовать эти кнопки? Можно ли в данном случае сделать исключение?

2022-06-24 12:18 UTC, KaterinaSolovyeva commented on src/get_timezone.py
> +            zoneinfo.ZoneInfo(text)
просто цифрами, мне кажется, непонятно. Будут разницу с Москвой писать. сделала как: UTC+3
кнопку с геолокацией сделала через автоматический запрос к пользователю:
[KeyboardButton('Отправить свою геолокацию для автоматической настройки часового пояса', **request_location=True**)]
"она была в примерах к нашей библиотеке (ищи примеры с конверсейшенами)" - прошу прощения, эту часть вообще не поняла. Это что и где смотреть?

2022-06-24 14:02 UTC, MatMerd commented on src/get_timezone.py
> +            zoneinfo.ZoneInfo(text)
Это смотреть в telegram-bot-api. Там есть вики и примеры разного функционала.

2022-06-24 15:03 UTC, AntonZelinsky commented on src/get_timezone.py
> +            if text not in RHETORICAL_TEXT and set("/").isdisjoint(text):
Да, ты права. тут будет исключение, потому что по другому не получится запросить локацию.

2022-06-24 15:34 UTC, veselij commented on src/get_timezone.py
> +            zoneinfo.ZoneInfo(text)
я тоже не нашел, если мы хотим показать пользователю кнопку запросить локацию - то только так. онлайн кнопками такое не сделать. можно попросто написать сообщение "расширьте нам свою геолокацию через стандартную клавиатуру" и тогда мы его сможем отработать. Но тут сомнения все ли поймут, что мы просим. можно конечно в сообщении прям инструкцию написать или скрин отправить типа куда жать

2022-06-24 15:54 UTC, KaterinaSolovyeva commented on src/bot.py
> -from telegram import Update
поняла почему, кажется. Я неправильно мержу вручную. Но не знаю как правильно. Помогите!
после пула некоторые файлы имеют разногласия со строками <<<<<<<старый код======<<<<<<<'второй вариант кода===== 
Что я делаю: удаляю в файле часть кода, которая не рабочая, оставляю правильную. Когда сохраняю, то весь код записывается под моим именем, даже если я выбрала чужой код
Подскажите, пожалуйста, как правильно делать?

2022-06-28 07:43 UTC, closed without merging