Feature/add trello end point
Studio-Yandex-Practicum/ask_nenaprasno_bot pull request #25
Opened 2022-06-24 02:49 UTC by Danielseddian

Add endpoint and base function for trello webhook

2022-06-24 15:29 UTC, veselij requested changes
в целом ок, только пофикси замечания по пеп, чтобы можно было мержить.
и положи пример json файла, того что приходит от трелло и в readme добавь описание, что вот так запускаем бота, берем json пример и curlом отправляем его на слушающий энд Поинт. чтобы тот кто будет делать след задание по обработке этого json понимал как его получить и в каком он виде

2022-06-24 15:29 UTC, veselij commented on src/run_webhook_api.py
> +            await request.app.state.bot_app.bot.send_message(chat_id=config.CHAT_ID, text=message)
закоментируй пожалуйста эти строки, так как у нас в конфете CHAT_ID, напиши просто в качестве коммента пример отправки сообщения и эти две закоменченные строчки

2022-06-25 16:00 UTC, veselij approved these changes
поправь readme пожалуйста

2022-06-25 16:00 UTC, veselij commented on README.md
> +    "url": "https://trello.com/b/nC8QJJoZ/trello-development",
положи пожалуйста просто файл .json в папочку src/example, а тут ссылку на него

2022-06-25 16:29 UTC, Danielseddian commented on README.md
> +    "url": "https://trello.com/b/nC8QJJoZ/trello-development",
Ага, понял, поправил

2022-06-25 22:05 UTC, AntonZelinsky reviewed
[Суда по всему](https://developer.atlassian.com/cloud/trello/guides/rest-api/webhooks/), можно из нашего кода сообщать трелло, что мы подключаем вебхук и нужно на него слать запросы. И именно это нужно сделать, так как руками каждый раз это делать никто не будет.

2022-06-25 22:05 UTC, AntonZelinsky commented on src/run_webhook_api.py
> +    if request.method == "HEAD":
А для чего метод хэд используется? При инициализации трелло?Добавь кометарий об этом, можно даже в  докстринг.

2022-06-25 22:05 UTC, AntonZelinsky commented on src/run_webhook_api.py
> +    Route("/trelloCallback", trello_call_back, methods=["POST", "HEAD"]),
Давай немного переименуем методы и добавим это в документик с соглашением
```suggestion
    Route("/telegramWebhookApi", telegram_webhook_api, methods=["POST"]),
    Route("/healthcheck", healthcheck_api, methods=["GET"]),
    Route("/trelloWebhookApi", trello_webhook_api, methods=["POST", "HEAD"]),
```
что для всех апи нужно добавлять окончание _апи

2022-06-25 22:05 UTC, AntonZelinsky commented on src/run_webhook_api.py
> +    return Response("Something wrong", status_code=405)
Судя по ограничениям роутов, этот кейс никогда не будет выполнен.

2022-06-25 22:05 UTC, AntonZelinsky commented on README.md
> +response = requests.post(url, data=payload)
Что этот пример иллюстрирует и зачем он тут я не понял..

2022-06-25 22:05 UTC, AntonZelinsky commented on src/run_webhook_api.py
> +        #     await request.app.state.bot_app.bot.send_message(chat_id=config.CHAT_ID, text=message)
Сделай тогда уже получение из запроса каких-то данных, даже самой простой id, но это уже иллюстрацию работы. Просто я подозреваю, что `await request.json()` возвращает какие-то данные и они попадают в иф и всё, выходит, этот пример немного некорректный.
Добавь логер и логируй что-нибудь из запроса туда.

Следующим заданием для тебя будет написать дата классы, хотя бы 1-2 штуки из иерархии и десириализовать в них json, но только нужно сделать это нужно уже в другом ПРе, чтобы эту задачку быстрее двинуть вперёд.
Сторонние библиотеки хотелось бы не подключать если есть более-менее вменяемые способы сделать это без них

2022-06-26 11:12 UTC, veselij commented
> [Суда по всему](https://developer.atlassian.com/cloud/trello/guides/rest-api/webhooks/), можно из нашего кода сообщать трелло, что мы подключаем вебхук и нужно на него слать запросы. И именно это нужно сделать, так как руками каждый раз это делать никто не будет.

но это по идее отдельная задача? это же не в эндпоинт вебхука? там еще надо для этого запроса сделать переменные окружения с токенами, и делать этот запрос убедившись, что наш сервер поднят, так как трелло после получения запроса на активацию, проверяет HEAD запросом переданный ей URL, "рабочий" ли он

2022-06-26 11:29 UTC, AntonZelinsky commented
Окей, пусть будет отдельной задачей. Но это всё в рамках одной общей задачи делается, пусть и из двух подзадач. Так как одно не имеет смысла без другого.
@Danielseddian, в общем, мелочи поправь в этом ПРе, а то что по крупянее в следующую задачу выноси.

2022-06-26 17:15 UTC, Danielseddian commented
Очень интересно, завтра гляну, сегодня не дома

2022-06-27 13:05 UTC, veselij requested changes

2022-06-27 13:05 UTC, veselij commented on README.md
> +response = requests.post(url, data=payload)
Денис добавь прям пример как Curl отправить example json (тот что у нас в папке примеров лежит) на наш endpoint trello, чтобы просто копируешь отсюда команду в терминал и получаешь запрос на endoint

2022-06-27 19:40 UTC, veselij requested changes
поправь еще пожалуйста пару замечаний, и все таки надо запускать свой код перед отправкой PR

2022-06-27 19:40 UTC, veselij commented on src/run_webhook_api.py
>      chat_id = config.CHAT_ID
chat_id больше нет у нас, упадет же при запуске, сделай просто логирование в консоль

2022-06-27 19:40 UTC, veselij commented on src/run_webhook_api.py
> +        trello_model_id: int = dict(await request.json()).get("model", {}).get("id", 0)
как-то очень сложно в одну строку, получи сначала респонс, а потом просто выбери через [model][id]

2022-06-27 19:40 UTC, veselij commented on src/run_webhook_api.py
> +        logging.info(f"Got trello request, model id: {trello_model_id}" if trello_model_id else "Got empty request")
и просто залогируй без if else. это же для примера, не надо тут логику накручивать. это все десериализации на датакалассы будет

2022-06-27 19:40 UTC, veselij commented on src/run_webhook_api.py
> +    return Response("ok", status_code=200)
статус коды лучше писать через httpx.codes.OK - так как понятно что за код. с 200 то лего, а с каким то 401 надо вспоминать, что это. лучше когда явно и однообразно написано

2022-06-27 19:40 UTC, veselij commented on src/core/logger.py
> +)
логирование просто в консоль надо, файл не надо создавать

2022-06-28 09:51 UTC, veselij approved these changes

2022-06-28 10:18 UTC, merged