Dockerfile support added
Studio-Yandex-Practicum/ask_nenaprasno_bot pull request #30
Opened 2022-06-26 14:53 UTC by agamova

@MatMerd проверьте, пожалуйста

2022-06-26 14:58 UTC, MatMerd commented
Теперь всё отлично! Можно мерджить!

2022-06-26 18:59 UTC, AntonZelinsky approved these changes

2022-06-26 18:59 UTC, AntonZelinsky commented on Dockerfile
> +COPY . /code
```suggestion
COPY . .
RUN pip3 install -r requirements.txt --no-cache-dir
```
После этого уже не нужно будет делать второй копи, так как скопируется всё в папку код. И строкой ниже нет смысла указыать абсолютный путь, так как команда воркдир создала папку код и перешла в неё

2022-06-26 18:59 UTC, AntonZelinsky commented on Dockerfile
> +CMD gunicorn -b 0.0.0.0:8000 -k uvicorn.workers.UvicornWorker src.run_webhook_api:api
Ой, а тут какая-то путаница. 
uvicorn и gunicorn — это два разных сервера и использовать их для запуска одного приложения точно не стоит. Я предлагаю uvicorn как асинхронный вариант и рекомендуемый используемой нами библиотекой.

2022-06-26 20:06 UTC, agamova commented on Dockerfile
> +CMD gunicorn -b 0.0.0.0:8000 -k uvicorn.workers.UvicornWorker src.run_webhook_api:api
<img width="806" alt="image" src="https://user-images.githubusercontent.com/85135228/175831978-d790198c-6126-4cd7-9800-f93bc9ba82d4.png">

2022-06-26 20:08 UTC, agamova commented on Dockerfile
> +CMD gunicorn -b 0.0.0.0:8000 -k uvicorn.workers.UvicornWorker src.run_webhook_api:api
@MatMerd  поручил мне gunicorn использовать для запуска

2022-06-26 20:34 UTC, agamova commented on Dockerfile
> +COPY . /code
@AntonZelinsky 
в этом случае каждое минимальное изменение в коде влечет за собой постоянное выполнение pip install -r requirements, что заметно увеличивает время создания образа.

в моем случае pip install будет вызываться только если добавилась какая-то новая зависимость. Если поменялся только код без изменения зависимостей, то выполнятся только последние инструкции Dockerfile'а.

2022-06-27 07:44 UTC, MatMerd commented on Dockerfile
> +COPY . /code
Т.к докер образ стромтся с помощью наложения слоёв с данными друг на друга, то у Жени сделано правильно. Объясню почему:
Файл requirements меняется гораздо реже, нежели основной код. Поэтому пересобирать слой с зависимостями так же часто, как и основные сорцы - бессмысленно и увеличивает время билда для образа

2022-06-27 12:06 UTC, AntonZelinsky commented on Dockerfile
> +COPY . /code
Ого, я не знал про это. 
То есть, если скопировали все файлы и хотя бы один файл проекта поменялся, то будут стягиваться все зависимости? А если скопировать сначала файл реквайрменты и вызвать установку из него зависимостей, то если файл реквайрмента не менялся, то ничего устанавливаться не будет?

Я всё правильно понял? Добавьте, пожалуйста, комментарии в этом файле, чтобы все тоже узнали про это.

2022-06-27 13:14 UTC, MatMerd commented on Dockerfile
> +COPY . /code
Да, правильно понял. Могу даже скинуть про это видос обучающий)

2022-06-27 13:14 UTC, MatMerd commented on Dockerfile
> +COPY . /code
@agamova добавь пожалуйста описание, почему так разделено копирование

2022-06-27 13:16 UTC, MatMerd requested changes

2022-06-27 13:16 UTC, MatMerd commented on pyproject.toml
> +gunicorn = "^20.1.0"
Жень, тут нужно убрать эту зависимость

2022-06-27 13:16 UTC, MatMerd commented on pyproject.toml
> +gunicorn = "^20.1.0"
И во всех остальных местах, где добавляла, тоже

2022-06-27 17:20 UTC, agamova commented on pyproject.toml
> +gunicorn = "^20.1.0"
виновата, исправлю

2022-06-27 17:41 UTC, agamova commented on pyproject.toml
> +gunicorn = "^20.1.0"
готово

2022-06-27 18:31 UTC, MatMerd approved these changes

2022-06-27 20:59 UTC, merged