Refactoring
Studio-Yandex-Practicum/ask_nenaprasno_bot pull request #31
Opened 2022-06-26 15:52 UTC by zhss1983

Минимум изменений, никакого рефакторинга не работающих фрагментов и импортов.
- Вынести все константы из проекта в отдельную папку.
- В дополнительном разбиении по файлам в зависимости от назначения нужды не вижу, итак уже разделены.
- В именах констант использовать постфикс отображающий где используется константа. 
- Значение констант равно самим себе.
- Объединил файлы start_conversation и bot_menu
- Вынести все jobs из файла bots в новый отдельный файл jobs

2022-06-26 16:41 UTC, veselij requested changes
а зачем вынеc  папку констант из src?

2022-06-26 16:41 UTC, veselij commented on constants/command_constants.py
> +ALREADY_SEND_COMMAND = "already_send_command"  # Не используемая константа
а зачем нам неиспользуемые? удалит их тогда надо

2022-06-26 16:41 UTC, veselij commented on src/start_conversation.py
> +from core.config import URL_SERVICE_RULES
мне кажется вот это констант, а не конфиг параметр, поэтому должна лежать в константах, @AntonZelinsky  @MatMerd  как думаете?

2022-06-26 16:41 UTC, veselij commented on constants/command_constants.py
> +SKIP_TIMEZONE_COMMAND = "skip_timezone_command"
это же по факту не команды, а callback_data для диалогов. может т вынесем в отдельный файл callback_data.py @AntonZelinsky @MatMerd, команд то всего две "start" и "menu"?

2022-06-26 17:24 UTC, zhss1983 commented on constants/command_constants.py
> +ALREADY_SEND_COMMAND = "already_send_command"  # Не используемая константа
Я не знаю кто и для чего их создавал, может быть это часть будущего кода. Так можно много чего подчистить.
Эти я удалю, но часто были случаи когда какие-то изменения ложились на уже замердженые и в последствии другими людьми изменённые, появлялись ошибки. Так было у нас когда в команде работали.

2022-06-26 17:43 UTC, zhss1983 commented on src/start_conversation.py
> +from core.config import URL_SERVICE_RULES
Согласен, недосмотрел.

2022-06-26 18:02 UTC, zhss1983 commented on constants/command_constants.py
> +SKIP_TIMEZONE_COMMAND = "skip_timezone_command"
Сделал.
Вообще есть ещё "cansel", но её в константы вносить не стали. Я добавил по аналогии.

2022-06-26 18:44 UTC, AntonZelinsky commented on src/start_conversation.py
> +from core.config import URL_SERVICE_RULES
Сложно, с одной стороны я согласен с вами, а с другой стороны, чтобы изменить ссылку, нужно менять код приложения. Если она в конфиге будет лежать, то достаточно изменить инвайрмент переменную и перезапустить деплой — этого будет достаточно.
А даже если вы решили вынести в константы, то их нужно в обычный файл констант, а не создавать отдельный файл для одной константы constants/url_paths.py. 
И у меня такой же вопрос, как выше уже писал Саша: `а зачем вынеc папку констант из src?`?

2022-06-26 18:45 UTC, AntonZelinsky commented on constants/command_constants.py
> +SKIP_TIMEZONE_COMMAND = "skip_timezone_command"
`cancel` нужно вообще удалить. Это плохой копипаст из примеров.

2022-06-26 18:55 UTC, zhss1983 commented on src/start_conversation.py
> +from core.config import URL_SERVICE_RULES
То есть лучше в config щставить, но сделать так что бы подгружалось из .env?

2022-06-26 18:59 UTC, zhss1983 commented on src/start_conversation.py
> +from core.config import URL_SERVICE_RULES
а зачем вынеc папку констант из src? - В задании чёрным по белому написано: Вынести все константы из проекта в отдельную папку. Я вынес. Судя по вопросам не верно понял? Судя по всему формулировка имелась ввиду "Перенести все константы проекта находящиеся не в файлах констант в файлы с константами."

2022-06-26 19:03 UTC, zhss1983 commented on constants/command_constants.py
> +SKIP_TIMEZONE_COMMAND = "skip_timezone_command"
Он используется в start_conversation, параметр fallbacks=[cancel_command_handler]. Если удаляем, то он за собой тянет и соответствующий метод: async def cancel(update: Update, context: ContextTypes.DEFAULT_TYPE)

2022-06-26 19:08 UTC, veselij commented on src/start_conversation.py
> +from core.config import URL_SERVICE_RULES
Да, русский язык подвёл. Имелось ввиду просто все константы проекта. Верни пожалуйста под src

2022-06-26 19:13 UTC, zhss1983 commented on src/start_conversation.py
> +from core.config import URL_SERVICE_RULES
Выполнил.

2022-06-26 19:20 UTC, zhss1983 commented on constants/command_constants.py
> +SKIP_TIMEZONE_COMMAND = "skip_timezone_command"
Ставлю fallbacks=[]
Далее выпиливаю всё связанное с cansel.
Бот запускается.

2022-06-26 19:22 UTC, zhss1983 commented on constants/command_constants.py
> +SKIP_TIMEZONE_COMMAND = "skip_timezone_command"
Ещё не плохо было бы переименовать command_constants просто в commands. Что скажете?

2022-06-26 19:41 UTC, AntonZelinsky commented on src/start_conversation.py
> +from core.config import URL_SERVICE_RULES
Это более правильный вариант.

2022-06-26 20:15 UTC, zhss1983 commented on constants/command_constants.py
> +SKIP_TIMEZONE_COMMAND = "skip_timezone_command"
По всей видимости это не требуется.

2022-06-26 20:18 UTC, AntonZelinsky approved these changes

2022-06-26 20:18 UTC, AntonZelinsky commented on src/constants/command_constants.py
> +MENU_COMMAND = "menu"
У нас будут всего две команды и для их нет смысла делать отдельный файл с константами. Если очень хочется, то можно сделать константу на уровне файл в котором они используются, но и от этого нет смысла. Ищем баланс в гибкости, целесообразности,  поддерживаемости и удобстве использования.

2022-06-26 20:18 UTC, AntonZelinsky commented on src/constants/callback_data.py
> +NOT_EXPERT_CALLBACK = "not_expert_command"
Подожди, тут колбэки или команды? Из содержимого видно, что это команда. А если в отладчике увидишь переменную которую передали куда-то в другое место то никогда и не догадаешься что там находится всё ровно и наоборот.
В обычной жизни с этим не сталкнёшься, но если отлавливаешь баг, то это будет полный крах. Я однажды дебажил эту библиотеку часа 4, пытаясь понять почему работает не так как должно, и правильные имена и содержимое очень помогали это сделать. Если бы не они, то наверно пришлось бы всё переделывать на правильные имена и заняло бы поиск проблемы и решения не 4 часа, а намного больше..

Эти штуки используются в инлайновых кнопках и самих колбэк хэндлерах:
```
NOT_EXPERT_CALLBACK = "not_expert_command"
InlineKeyboardButton("Нет", callback_data=callback.NOT_EXPERT_CALLBACK),
CallbackQueryHandler(not_expert_callback, pattern=callback.NOT_EXPERT_CALLBACK),
```
Для кнопки он нужен для того, чтобы передать какую-то информацию нашей системе, куда происходит переход. То есть, по сути это команда, для того чтобы сделать этот переход (если представлять, что была нажата какая-то кнопка), я со скрипом согласен на паттерн или колбэк_паттерн, но никак ни на колбэк. К тому же, у тебя везде одинаковые названия, у функций и констант. 

колбэк — это всегда метод вызываемый при каком-то событии.

2022-06-26 20:18 UTC, AntonZelinsky commented on src/start_conversation.py
> +menu_command_handler = CommandHandler(cmd_const.MENU_COMMAND, callback=menu)
Если эти штуки нигде не переиспользуются, то нет смысла выносить их в отдельные переменные, пусть как CallbackQueryHandler создаются прямо в структуре ConversationHandler

2022-06-26 20:18 UTC, AntonZelinsky commented on src/start_conversation.py
> +callback_menu_handler = CallbackQueryHandler(handling_menu_button_click_callback)
Не нашёл где это используется

2022-06-26 20:27 UTC, zhss1983 commented on src/constants/command_constants.py
> +MENU_COMMAND = "menu"
Дак может ну их вовсе, оставить просто текст в коде? Он по всему применятся будет только в одном месте?

2022-06-26 20:31 UTC, zhss1983 commented on src/start_conversation.py
> +menu_command_handler = CommandHandler(cmd_const.MENU_COMMAND, callback=menu)
Выше вопрос задавал. Снимаю.

2022-06-26 20:39 UTC, zhss1983 commented on src/start_conversation.py
> +callback_menu_handler = CallbackQueryHandler(handling_menu_button_click_callback)
А оно и не используется. Это фрагмент из файла bot_menu.py Он предполагает вызов меню. Я даже добавлял его в код так что бы меню вызывалось, но тот код вы забраковали. Оставил как есть. Для чего нужен будет или для чего применялся надо наверное у Андрея спрашивать.

2022-06-26 20:42 UTC, zhss1983 commented on src/constants/command_constants.py
> +MENU_COMMAND = "menu"
Удалил, вместо констант прописал их значения.

2022-06-26 20:43 UTC, zhss1983 commented on src/start_conversation.py
> +menu_command_handler = CommandHandler(cmd_const.MENU_COMMAND, callback=menu)
Сделано.

2022-06-26 21:13 UTC, zhss1983 commented on src/constants/callback_data.py
> +NOT_EXPERT_CALLBACK = "not_expert_command"
То что в значении применяется постфикс command, а в названии постфикс callback - это мой косяк. Я переименовал названия констант в соответствии с файлом в который и поместил, но забыл про сами значения.
Теперь непосредственно с именами. Я понимаю что такое колбэк, но не понимаю какие имена требуются для констант. В моём понимании если в качестве параметра требуется callback, то и передавать надо callback. И названия у констант и сами они должны быть соответствующие.

2022-06-26 21:51 UTC, zhss1983 commented on src/constants/callback_data.py
> +NOT_EXPERT_CALLBACK = "not_expert_command"
"К тому же, у тебя везде одинаковые названия, у функций и констант." А в чём тут проблема?

2022-06-27 07:35 UTC, zhss1983 commented on src/constants/callback_data.py
> +NOT_EXPERT_CALLBACK = "not_expert_command"
Последние изменения корректны? Или я опять всё не верно понял?

2022-06-27 07:37 UTC, zhss1983 commented on src/start_conversation.py
> +callback_menu_handler = CallbackQueryHandler(handling_menu_button_click_callback)
Изменил код таким образом что бы меню можно было вызвать по команде. Изменения минимальны.

2022-06-27 07:42 UTC, zhss1983 commented on src/start_conversation.py
> +callback_menu_handler = CallbackQueryHandler(handling_menu_button_click_callback)
Теперь меню вызывается по команде /menu. Я не автор этой части, старался минимизировать вмешательство в чужой код.

2022-06-27 07:58 UTC, veselij approved these changes

2022-06-27 07:59 UTC, veselij commented on src/start_conversation.py
> +callback_menu_handler = CallbackQueryHandler(handling_menu_button_click_callback)
там толькло теперь надо сделать чтобы меню переводило в стейт меню, чтобы callback  нажатия кнопок меню отрабатывал

2022-06-27 08:01 UTC, zhss1983 commented on src/start_conversation.py
> +callback_menu_handler = CallbackQueryHandler(handling_menu_button_click_callback)
Ок.

2022-06-27 12:43 UTC, merged

2022-06-27 12:50 UTC, AntonZelinsky commented on src/constants/callback_data.py
> +NOT_EXPERT_CALLBACK = "not_expert_command"
Всё окей. Сергей, добавь, пожалуйста, в файлик с соглашениями и хорошими практиками информацию о том, как нужно именовать переменные в боте.
Например:

- `menu_command_handler = CommandHandler("menu", menu)` — для команд хэндлеров добавляем постфикс `_command_handler`
- `menu_callback_handler = CallbackQueryHandler(handling_menu_button_click_callback)` — `_callback_handler`
- `InlineKeyboardButton("Да", callback_data=callback.CALLBACK_REGISTR_AS_EXPERT_COMMAND),` для колбэк даты ...
- состояния сюда же.
Про то где и в каком файле должно быть. Это позволит всем придерживаться одного стиля