Feature/refactoring the service api
Studio-Yandex-Practicum/ask_nenaprasno_bot pull request #32
Opened 2022-06-26 16:36 UTC by AndreyMurysev

Поправил все, кроме "APIService переименовать в AbstractAPIService и убрать из него получение значения из конфига" единственное значение из конфига это SITE_API_URL и он хранится в конфиге

2022-06-26 17:22 UTC, veselij requested changes
после того как правки сделаешь запусти сервис, и попробуй curl-ом или postmanом отправить данные (с эмулировать трелло) и посмотри как у тебя отработает

2022-06-26 17:22 UTC, veselij commented on src/service/api_client/base.py
>      def __init__(self):
а почему не убрал то из абстрактного класса? надо убрать __init__

2022-06-26 17:22 UTC, veselij commented on src/service/api_client/base.py
> +from models import BillStat, MonthStat, MyMonthStat, MyWeekStat, UserData, WeekStat
а services.api_client развне не надо дописать в начале? так не импортируется

2022-06-26 17:22 UTC, veselij commented on src/service/api_client/__init__.py
> +    ConreateAPIService = ShemasAPIService
как то названия не очень, задаем там слово схемы. 
```suggestion
    APIService = MockAPIService
else:
    APIService = SiteAPIService
```

файлы с api сервисами тоже переименовать в mock_api_service и site_api_service

2022-06-26 17:22 UTC, veselij commented on src/service/api_client/__init__.py
> +from service.api_client.hemas import ShemasAPIService
опечатка в импорте, ты не запускал код?

2022-06-26 17:22 UTC, veselij commented on src/service/api_client/base.py
> +    async def get_my_week_stat(self, telegram_id: int) -> MyWeekStat:
my -> user
я писал, что telegram_id поменялся на telegram_name везде
https://docs.google.com/spreadsheets/d/1ul1fCjuQeBiYlC7-n_x1929o3NXk4kUiu-ucxbHeahc/edit#gid=429815105

аналогично для методов ниже

2022-06-26 17:22 UTC, veselij commented on src/service/api_client/models.py
> +class UserWeekStat:
UserWeekStat  -> WeekStat
MyWeekStat -> UserWeekStat

аналогично для месячной

2022-06-26 17:22 UTC, veselij commented on src/service/api_client/models.py
> +    user_timezone: str
надо добавить telegram_name

2022-06-26 17:22 UTC, veselij commented on src/service/api_client/models.py
> +    user_ticket_resolve_avg_time: str
float

2022-06-26 17:22 UTC, veselij commented on src/service/api_client/models.py
> +    last_week_user_tickets_expired: str
int

2022-06-26 17:22 UTC, veselij commented on src/service/api_client/models.py
> +    user_tickets_closed: str
int

2022-06-26 17:22 UTC, veselij commented on src/service/api_client/models.py
> +    user_tickets_closed: str
int

2022-06-26 17:22 UTC, veselij commented on src/service/api_client/models.py
> +    user_ticket_resolve_avg_time: str
float

2022-06-26 17:22 UTC, veselij commented on src/service/api_client/models.py
> +    last_week_user_tickets_expired: str
int

2022-06-26 17:22 UTC, veselij commented on src/service/api_client/models.py
> +class WeekStat:
UsersWeekStat

2022-06-26 17:22 UTC, veselij commented on src/service/api_client/models.py
> +class MonthStat:
а зачем нам еще один датакласс. Достаточно использовать list[MonthStat]. аналогично для недель

2022-06-26 17:22 UTC, veselij commented on src/service/api_client/shemas.py
> +        url = f"{self.site_url}tgbot/bill"
```suggestion
        url = f"{self.site_url}/tgbot/bill"
```

2022-06-26 17:22 UTC, veselij commented on src/service/api_client/shemas.py
>              response = response.json()
```suggestion
            response = await response.json()
```

2022-06-26 17:22 UTC, veselij commented on src/service/api_client/shemas.py
> +            return BillStat(response["telegram_id"])
id->name

2022-06-26 17:22 UTC, veselij commented on src/service/api_client/shemas.py
> +            return WeekStat(response["week_stat"])
так не будет работать, надо из response листа сформировать нужный лист датаклассов и отдать его
аналогично ниже

2022-06-26 17:22 UTC, veselij commented on src/service/api_client/mock_shemas.py
> +AUTH_RETURN = UserData("Bob", "UTC+3", "24")
при создании экземпларов, если много полей, то надо использовать именование параметры field1 = xxx
так как сейчас абсолютно, не читается, что есть что

2022-06-26 17:22 UTC, veselij commented on src/service/api_client/mock_shemas.py
> +        return BillStat(GET_BILL_RETURN)
тут можно не прожить константы. было бы более читаемо прям в return создать с именованными параметрами. Аналогично по всем методам ниже

2022-06-26 17:22 UTC, veselij commented on src/service/api_client/mock_shemas.py
> +        # return None
тут и без коментов понятна суть, либо данные юзера либо ничего

2022-06-26 20:33 UTC, AntonZelinsky commented on src/service/api_client/__init__.py
> +    ConreateAPIService = ShemasAPIService
А откуда взялось `Shemas`?? и что оно значит?
Гугл мне сказал, что шемас это какой-то чувак занимающийся вреслингом 
![image](https://user-images.githubusercontent.com/1431279/175832650-c71d2845-4833-4133-bff9-844fdc103aaf.png)

Если задумка была написать `Schemas`, то я ещё могу понять и то с трудом, так как это ни разу не упрощает понимание, а скорее наоборот.

2022-06-26 20:38 UTC, AntonZelinsky commented on src/service/api_client/mock_shemas.py
> +        return BillStat(GET_BILL_RETURN)
на 100% согласен. Когда смотришь метод, приходится ещё идти вверх и искать эту константу и разбираться что находится внутри её. 
ПРИЧЁМ, для каждой константы ты выделил место в памяти, посоздавал экземпляры и хранишь там данные, даже если этот класс не будет использоваться в продакшене, эти переменные будут храниться в оперативной памяти

2022-06-27 19:04 UTC, AndreyMurysev commented on src/service/api_client/models.py
> +    user_tickets_closed: str
В примере "user_timizone": "UTC+3", оставил как str

2022-06-27 20:56 UTC, veselij requested changes
обнови пожалуйста свою ветку до последних изменений в develop

2022-06-27 20:56 UTC, veselij commented on src/bot.py
> +
обнови свою ветку из develop. эти функции уехали в другой файл уже

2022-06-27 20:56 UTC, veselij commented on src/service/api_client/__init__.py
> +    ConreateAPIService = MockAPIService
```suggestion
    APIService = MockAPIService
```

2022-06-27 20:56 UTC, veselij commented on src/service/api_client/__init__.py
> +    ConreateAPIService = SiteAPIService
```suggestion
    APIService = SiteAPIService
```

2022-06-27 20:56 UTC, veselij commented on src/service/api_client/base.py
> +    site_url: str = config.SITE_API_URL
это надо в конструкт SiteAPIService перенести. нам же в MockAPI не нужен этот аттриубут.

2022-06-27 20:56 UTC, veselij commented on src/service/api_client/base.py
> +    async def get_week_stat(self) -> WeekStat:
```suggestion
    async def get_week_stat(self) -> list[WeekStat]:
```

2022-06-27 20:56 UTC, veselij commented on src/service/api_client/base.py
> +    async def get_month_stat(self) -> MonthStat:
```suggestion
    async def get_month_stat(self) -> list[MonthStat]:
```

2022-06-27 20:56 UTC, veselij commented on src/service/api_client/mock_api_service.py
> +                last_week_user_tikets_closed=10,
```suggestion
                last_week_user_tickets_closed=10,
```

2022-06-27 20:56 UTC, veselij commented on src/service/api_client/mock_api_service.py
> +                last_week_user_tikets_closed=5,
```suggestion
                last_week_user_tickets_closed=5,
```

2022-06-27 20:56 UTC, veselij commented on src/service/api_client/mock_api_service.py
> +    async def get_use_week_stat(self, telegram_name: str) -> UserWeekStat:
```suggestion
    async def get_user_week_stat(self, telegram_name: str) -> UserWeekStat:
```

2022-06-27 20:56 UTC, veselij commented on src/service/api_client/models.py
> +    last_week_user_tikets_closed: int
```suggestion
    last_week_user_tickets_closed: int
```

2022-06-27 20:56 UTC, veselij commented on src/service/api_client/models.py
> +    last_week_user_tikets_closed: int
```suggestion
    last_week_user_tickets_closed: int
```

2022-06-27 20:56 UTC, veselij commented on src/service/api_client/site_api_service.py
> +from http import HTTPStatus
в httpx есть httpx.codes

2022-06-27 20:56 UTC, veselij commented on src/service/api_client/site_api_service.py
> +    async def get_bill(self) -> BillStat:
надо добавить init и в нем ту срочку с чтением url из config

2022-06-27 20:56 UTC, veselij commented on src/service/api_client/site_api_service.py
> +            return WeekStat(response["telegram_name"])
тебе же надо вернуть BillStat, надо из так 
```suggestion
            return BillStat(telegram_name=response["telegram_name"])
```

2022-06-27 20:56 UTC, veselij commented on src/service/api_client/site_api_service.py
> +            return WeekStat(response["week_stat"])
```suggestion
            return [
                      WeekStat(
                                   telegram_name=week_stat ["telegram_name"],
                                   user_timezone=week_stat ["user_timezone"],
                                   ....
                                   
                                     ) for week_stat in response              
                       ]
```

2022-06-27 20:56 UTC, veselij commented on src/service/api_client/site_api_service.py
> +            return WeekStat(response["month_stat"])
аналогично недельной

2022-06-27 20:56 UTC, veselij commented on src/service/api_client/site_api_service.py
> +            return WeekStat(response["week_stat"])
```suggestion
            return WeekStat(
                                   user_timezone=week_stat ["user_timezone"],
                                   ....
                                   
                                     )
```

2022-06-27 20:56 UTC, veselij commented on src/service/api_client/site_api_service.py
> +            return WeekStat(response["month_stat"])
аналогично

2022-06-27 20:56 UTC, veselij commented on src/service/api_client/site_api_service.py
> +            return UserData(response["username"], response["user_timezone"], response["user_name_in_trello"])
надо добавить имена параметров

2022-06-27 21:56 UTC, AntonZelinsky commented on src/service/api_client/__init__.py
> +    ConreateAPIService = MockAPIService
Блин, ... 
![image](https://user-images.githubusercontent.com/1431279/176042485-cee6e259-ac37-4cf8-b2dc-439724f44076.png)

2022-06-27 21:59 UTC, AntonZelinsky commented on src/service/api_client/site_api_service.py
> +            return WeekStat(response["week_stat"])
А я говорил, не нужно реализовывать это! Если читали статью про антипаттерны которую я скинул, там про это как раз говорилось, что это разработка неподдерживаемого кода.
Закоментируйте всё содержимое этих методов и всё! КОгда появятся какие-то апи, тогда и будут реализовываться.

но кто слушает старого деда, все хотят набить шишек сами

2022-06-27 22:00 UTC, AntonZelinsky commented on src/service/api_client/site_api_service.py
> +            return WeekStat(response["week_stat"])
Тут нужно разработать один просто механизм отправки запросов и мапинга, это будет в одной функции, сейчас, пока что, ничего не получится такое сделать, пока нет куда слать запросы

2022-06-29 20:24 UTC, veselij requested changes
смерджи пожалуйста последние изменения из develop и убери закоментированный код в SiteAPIService

2022-06-29 21:24 UTC, veselij approved these changes

2022-06-29 21:34 UTC, merged