Feature/pre commit
Studio-Yandex-Practicum/ask_nenaprasno_bot pull request #33
Opened 2022-06-26 22:55 UTC by zhss1983

Добавил в игнор ошибку возникающую из-за слишком большого количества переменных указанных в dataclass (у нас использовано 8, максимум разрешенных 7).

2022-06-27 13:03 UTC, AntonZelinsky approved these changes

2022-06-27 13:03 UTC, AntonZelinsky commented on .pre-commit-config.yaml
> +      args: [-j=0, --max-line-length=120, --disable=W0613, --disable=W0611, --disable=E0401, --disable=R0902]
[А где у нас такая проблема R0902?](http://pylint-messages.wikidot.com/messages:r0902)

И [тут E0401](http://pylint-messages.wikidot.com/messages:r0902) ?
[И эта W0611](https://vald-phoenix.github.io/pylint-errors/plerr/errors/variables/W0611.html)
Мне кажется, эти ошибки не нужно игнорить, а переделать чуть-чуть код. 
Я бы и [эту W0613 тоже](https://vald-phoenix.github.io/pylint-errors/plerr/errors/variables/W0613.html) убрал из игнора, но на начальных стадиях разработки может быть оправдано

2022-06-27 13:04 UTC, AntonZelinsky commented on .pre-commit-config.yaml
> +      args: [-j=0, --max-line-length=120, --disable=W0613, --disable=W0611, --disable=E0401, --disable=R0902]
Окей, я прочитал про датаклассы, но может добавить игнор на уровне файла? Это решит проблему и не даст раздуваться коду

2022-06-28 06:04 UTC, zhss1983 commented on .pre-commit-config.yaml
> +      args: [-j=0, --max-line-length=120, --disable=W0613, --disable=W0611, --disable=E0401, --disable=R0902]
Я исправил код для того что бы не ловить E0401. Это привело к выползанию ещё нескольких ошибок которые были внесены до появления .pre-commit-config.yaml файла. Их пришлось тоже решать.

2022-06-28 06:15 UTC, zhss1983 commented on .pre-commit-config.yaml
> +      args: [-j=0, --max-line-length=120, --disable=W0613, --disable=W0611, --disable=E0401, --disable=R0902]
В результате добавил в config одну константу, изменил строку в send_message, добавил игнор на конкретный dataclass одну ошибку R0902, исправил во многих местах импорты и убрал из pre-commit-config игнорирование ошибок W0611, E0401 и R0902.

2022-06-28 08:47 UTC, veselij requested changes

2022-06-28 08:47 UTC, veselij commented on src/core/config.py
> +CHAT_ID = env.get("CHAT_ID")  # ID Чата пользователя телеграмм бота, применяется для webhook.
вот это лишнее, давно удалили

2022-06-28 08:47 UTC, veselij commented on src/bot.py
> +from src.start_conversation import start_conversation
мы же договрились в чате удлать __init.py из src и не писать префикс тогда src.

2022-06-28 08:47 UTC, veselij commented on src/service/api_client_dataclasses.py
> +# pylint: disable=R0902
а надо декоратором нельзя напсиать? не будет работать так?

2022-06-28 08:55 UTC, zhss1983 commented on src/core/config.py
> +CHAT_ID = env.get("CHAT_ID")  # ID Чата пользователя телеграмм бота, применяется для webhook.
Тем не менее в ветке develop по прежнему этот параметр читается из config и требуется для любого commit-а если задеть файл run_webhook_api.py

2022-06-28 08:55 UTC, zhss1983 commented on src/bot.py
> +from src.start_conversation import start_conversation
Это обсуждалось с другим человеком, думал это будет в его PR. Внесу соответствующие изменения.

2022-06-28 08:56 UTC, zhss1983 commented on src/bot.py
> +from src.start_conversation import start_conversation
Строки 29-30

2022-06-28 09:37 UTC, zhss1983 commented on src/service/api_client_dataclasses.py
> +# pylint: disable=R0902
Будет.

2022-06-28 10:00 UTC, zhss1983 commented on src/core/config.py
> +CHAT_ID = env.get("CHAT_ID")  # ID Чата пользователя телеграмм бота, применяется для webhook.
Удалил через GitHub.

2022-06-28 10:03 UTC, AntonZelinsky approved these changes

2022-06-28 10:03 UTC, AntonZelinsky commented on src/start_conversation.py
> +from constants import callback_data as callback
`callback` — это функция, а в этом файле лежат константы. Поэтому, лучше не добавляй алиас `callback`, оставь как есть, чтобы не путало

2022-06-28 10:28 UTC, zhss1983 commented on src/start_conversation.py
> +from constants import callback_data as callback
Оставил.

2022-06-28 10:31 UTC, AntonZelinsky commented on src/start_conversation.py
> +from constants import callback_data as callback
Ой, я имел в виду, оставить оригинальное название `callback_data`

2022-06-28 10:40 UTC, zhss1983 commented on src/start_conversation.py
> +from constants import callback_data as callback
Я извиняюсь, мой косяк. Я понял что имелось ввиду, но умудрился не на ту ветку переключиться.

2022-06-28 16:03 UTC, merged