Feature/sending statistics
Studio-Yandex-Practicum/ask_nenaprasno_bot pull request #34
Opened 2022-06-28 06:23 UTC by kapkaevandrey

## Ticket - [Сreate a mailing service](https://www.notion.so/358f328a66444461ae5012d232011cb9).
Add file sending_mailing.py to the directory services.  
 - Two functions have been added for monthly and weekly mailing lists. The function defines message templates in which dataclasses attributes are used..  
-  The send_message function has been modified. An optional parse_mode attribute has been added to it for the ability to use markup when sending a message.
- Fixed grammatical errors in the example.env file
- Added logging in case of an unsuccessful API request.

2022-06-28 10:00 UTC, veselij requested changes

2022-06-28 10:00 UTC, veselij commented on src/jobs.py
> +        pass
добавь логирование в терминал пока

2022-06-28 10:00 UTC, veselij commented on src/service/send_mailing.py
> +    except Exception as error:
а должны ли мы тут ловить исключение, более правильно ловить в сервисе API конкретное исключение и логировать его там (или пытаться делать перезапрос).

2022-06-28 10:00 UTC, veselij commented on src/service/send_mailing.py
> +async def send_week_statistic(
по мне копи-паст антипатерн получился, @AntonZelinsky @MatMerd  посмотрите пожалуйста. Может стоит в jobе создать экземпляр сервиса и получить там статистику и передать ее уже start_mailing_statistic. а у датаклассов вызвать сообщение get_message внутри которого используется нужный template?
или может другие идеи есть?

2022-06-28 10:15 UTC, AntonZelinsky commented on src/service/send_mailing.py
> +            text=template_message.substitute(**user_statistic.__dict__),
`template_message.substitute(**user_statistic.__dict__),` вычислять до вызова этой функции. Сюда передавать только текст. По крайней мере, не вижу смысла делать это тут. В функцию передавать id и само сообщение и кнопки, хотя скорее всего, что и кнопки тут будут добавляться, так как, скорее всего, они одинаковые 

parse_mode установить в функции send_message по умолчанию и использовать не строку, а константу из библиотеки

2022-06-28 10:15 UTC, AntonZelinsky commented on src/service/send_mailing.py
> +async def send_week_statistic(
Давайте пока избавимся от этого файла чтобы было проще. 
А в функцию `start_mailing_statistic` предлагаю перенести к `send_message`. Только имя дать нормальное ей нужно

2022-06-28 12:28 UTC, kapkaevandrey commented on src/service/send_mailing.py
> +    except Exception as error:
Тогда вопрос как мы поймём, что рассылка прошла успешно,  или всю эту логику скинуть в API? Я уберу, но мне кажется так логика начинает размазываться и становится не совсем ясное где и что ловить и как это перезапускать.

2022-06-28 12:32 UTC, kapkaevandrey commented on src/service/send_mailing.py
> +            text=template_message.substitute(**user_statistic.__dict__),
Я могу так сделать, но у нас получится одноразовая переменная. Мы можем передавать и parse_mode всё таки сообщение может быть передано с разной разметкой или без таковой вообще имея ввиду что символы * это именно звёздочки, а \<br\> это именно текст. Я думаю универсальней оставить None и прокидывать нужное значение.

2022-06-28 13:40 UTC, veselij commented on src/service/send_mailing.py
> +    except Exception as error:
мы должны отлавливать конкретную ошибку, ошибка которая нам все ломает это HTTP error нет ответа, или нет body или оно не парсится и т.п. Это все делается в api, получается api упадет, а мы тут ошибку api поймаем, причем не поняв ее тип - как раз размыта логика. а если мы ее обработаем там, то тогда во первых мы понимаем что конрктно мы должно отлавливать и во вторых можем как то на это реагировать помимо логирования. сюда же мы передадим или значение или ничего (например) и ты это проверишь (но позже). или возможно мы там зарайзим кастомный эксепшен - типа api не доступен - и вот тогда ты тут конкретно его будещь отлавливать. Но пока просто - считаем все работает

2022-06-28 13:48 UTC, kapkaevandrey commented on src/service/send_mailing.py
> +    except Exception as error:
Я понимаю, просомтрел все ошибки которые могут появиться при запросе там их очень много. Большая часть унаследована от HTTPError, но так же там InvalidURL, CookieConflict, StreamError. Може я тогда буду опираться на возвращаемое значение, если будет ошибка метод вернёт None и я могу поймать это и залогировать предупреждение. Или могу вообще всё это убрать и из jobs Тоже. Я ни в коем случае не критикую, просто предлагаю варианты. Try я здесь поставил потому что в API его не было.

2022-06-28 16:07 UTC, AntonZelinsky commented on src/service/send_mailing.py
> +            text=template_message.substitute(**user_statistic.__dict__),
А почему мы не можем согласовать и принять на уровне проекта тип разметки сообщений? Два разных точно не будем поддерживать, чем больше используемых или неиспользуемых возможностей, тем больше мест для ошибок!
Приведи примеры где используется один, а где другой и давай думать какой лучше. 
Я за MARKDOWN, так как он проще и понятнее для пользователей, особенно для тех, кто не знает html

2022-06-28 17:11 UTC, kapkaevandrey commented on src/service/send_mailing.py
> +            text=template_message.substitute(**user_statistic.__dict__),
Я к сожалению не могу привести примера. Сделаю как скажете, но мне кажется, что уход от универсальности решения. И так же что делать если мы хотим чтобы символы разметки Markdown были просто символами, в частности в самой функции отправки сообщения модуля Telegram prase_mode по умолчанию None, на мой взгляд единообразие параметров и схожее поведение функций близких по сущности облегчает работу с проектом.

2022-06-28 17:12 UTC, kapkaevandrey commented on src/service/send_mailing.py
> +            text=template_message.substitute(**user_statistic.__dict__),
Если не убедил установливаю Markdown по умолчанию. Ни в коем случае не критикую просто это моё мнение.

2022-06-28 18:12 UTC, veselij requested changes

2022-06-28 18:12 UTC, veselij commented on src/service/send_mailing.py
> +            text=template_message.substitute(**user_statistic.__dict__),
насчет парс мода-дак оставляй его в параметрах. только не none а значение по умолчанию parse_mode=ParseMode.XXX
у тебя в джобе будет определенна переменная message_template = Template(), потом ты там же вызываешь message = message_template.substitute(key=value,...) и вызваешь start_mailing_statistic.
потом мы унесем message_template в файлы локализации доступные для редактиварония админу.
и у тебя останется формирование сообщения и его отправка

2022-06-28 18:12 UTC, veselij commented on src/service/send_mailing.py
> +    except Exception as error:
Сейчас цель сделать чтобы базово бот работал. Потом добавим все это

2022-06-28 18:12 UTC, veselij commented on src/core/send_message.py
> +            chat_id=user_statistic.telegram_id,
бот не может отправить юзеру. может только в чат юзера. или я что-то пропустил? надо узнать какой chat_id у юзера и юзер будет не telegram_id.

2022-06-28 18:12 UTC, veselij commented on src/core/send_message.py
> +            text=template_message.substitute(**user_statistic.__dict__),
мне не нравиться, то что мы используем __атрибут и полагаемся на то, что имена должны сойтись в темплейте и в дикте. Mypy такое скорее всего пропустит, если будет несоответствие имен и мы можем получить баг. поэтому мы хотели передавать сюда готовый текст сразу. т.е. мы приходим к тому, что надо просто в Джобе получить список статистик и пройтись по нему и сформировать сообщение и отправить через функцию send_message

2022-06-29 15:49 UTC, veselij approved these changes

2022-06-29 15:49 UTC, veselij commented on src/start_conversation.py
> +        context.bot_data["username_to_id"] = {}
думаю стоит добавить после создания бота сразу, чтобы вызвыалось один раз при запуске бота

2022-06-29 15:57 UTC, veselij requested changes

2022-06-29 15:57 UTC, veselij commented on src/bot.py
> +    bot_app.bot_data["username_to_id"] = {}
ну тоже с if надо проверить, а то перезапишешь, если бот из персистанс файла уже загрузил этот дикт

2022-06-29 17:33 UTC, AntonZelinsky commented on src/service/send_mailing.py
> +            text=template_message.substitute(**user_statistic.__dict__),
Давай только маркдаун.

2022-06-29 18:45 UTC, AntonZelinsky approved these changes

2022-06-29 18:45 UTC, AntonZelinsky commented on src/jobs.py
> +        message = pre_message.substitute(
Давай это вынесем в отдельную функцию, которая будет принимать строковый шаблон и параметры для подтавновки в этот метод. Их через kwargs достань потом

2022-06-29 18:45 UTC, AntonZelinsky commented on src/jobs.py
> +    for user_statistic in mont_statistic_obj.month_stat:
Функцию рассылки сделай лежащую рядом с функцией send_message. В себя она должна принимать список  статистик и делать по ним рассылку. Если в текущей версии тебе ещё нужен контекст, то передавай его туда. Завтра скорее всего выпилим его. Но отрефайторить нужно уже сейчас

2022-06-29 22:13 UTC, AntonZelinsky commented on src/jobs.py
> +        message = pre_message.substitute(
Это так и не было исправлено..( 
После исправления можешь смержить ПР

2022-06-30 08:01 UTC, veselij approved these changes
Dockerfile только не надо переписывать, у тебя видимо не последняя версия

2022-06-30 08:37 UTC, merged