Get timezone and menu button
Studio-Yandex-Practicum/ask_nenaprasno_bot pull request #35
Opened 2022-06-28 07:33 UTC by KaterinaSolovyeva

Ticket - [Установка дефолтных кнопок для телеграма](https://www.notion.so/7d6d35f407814742a0cebea1e480bd4b?p=9f3edd440b0a4ffca5d77f5e695a2870)

добавлена кнопка Меню, из которой можно перейти в список доступных запросов

Ticket - [Установка часового пояса + диалоги бота к нему](https://www.notion.so/7d6d35f407814742a0cebea1e480bd4b?p=599621be7b1f47e19470172398a5db7e)

При запросе на присвоение нового часового пояса появляются две кнопки объекта ReplyKeyboard:
'Отправить свою геолокацию для автоматической настройки часового пояса' - получает гелолокацию, по ней определяет таймзону. Передает по апи
'Напишу свою таймзону сам' - распознает введенный текст. Проверяет, существует ли такая таймзона. Если да, то передает её через апи. Если нет, то проверяет, не является ли введенный текст тем, на который отвечать не нужно. Просит пользователя ввести другую таймзону или выслать геолокацию.
После получения таймзоны кнопки ReplyKeyboard внизу исчезают

2022-06-28 08:18 UTC, MatMerd requested changes, later dismissed

2022-06-28 08:18 UTC, MatMerd commented on src/get_timezone.py
> +            utc = int(list(filter(None, text.split("UTC")))[0])
Такие однострочники это конечно прикольно, но в действительности они чаще всего сложно поддерживаемые.
Почему нельзя сделать просто int(text.lstrip("UTC"))?
Да и вообще, "UTC" - это хардкод и лучше это выносить в константы, чтоб мы в любой момент могли поменять.
И ещё момент. На вики можно увидеть, что таймзоны бывают не только целыми, но и +3:30 например. С этим тоже надо как-то работать.

2022-06-28 08:27 UTC, KaterinaSolovyeva commented on src/get_timezone.py
> +            utc = int(list(filter(None, text.split("UTC")))[0])
может, тогда передавать не часы, а минуты по апи?

2022-06-28 08:29 UTC, MatMerd commented on src/get_timezone.py
> +            utc = int(list(filter(None, text.split("UTC")))[0])
Нет. Можно передавать часы дробью. 3.5 - это 3:30. 3.75 - 3:45.

2022-06-28 08:30 UTC, KaterinaSolovyeva commented on src/get_timezone.py
> +            utc = int(list(filter(None, text.split("UTC")))[0])
ок

2022-06-28 08:42 UTC, veselij commented on src/get_timezone.py
> +            utc = int(list(filter(None, text.split("UTC")))[0])
я извиняюсь я просил изначально тайм-зону числом. давайте отсавим пока str UTC+3.75. и так и будем сохранять в БД, там тоже сейчас str. а потом в функции расчета времени отправки по ТЗ будем уже высчитывать

2022-06-28 08:44 UTC, KaterinaSolovyeva commented on src/get_timezone.py
> +            utc = int(list(filter(None, text.split("UTC")))[0])
хорошо

2022-06-28 10:22 UTC, KaterinaSolovyeva commented on src/get_timezone.py
> +            utc = int(list(filter(None, text.split("UTC")))[0])
такие выводы подойдут или обязательно с плюсом? 
UTC09:30
UTC-3:00

2022-06-28 10:25 UTC, AntonZelinsky commented on src/get_timezone.py
> +            utc = int(list(filter(None, text.split("UTC")))[0])
Ой, а что за таймзона `UTC+3.75`? Первый раз слышу, да и гугл такую не нашёл! И на википедии такой статьи не нашёл..(

Предлагаю написать регулярку проверяющую на два формата `UTC+3` и просто `+5`. `UTC` не хочется заставлять добавлять потому что нужно будет переключаться каждый раз на другую клавиатуру и велики шансы ошибок, которые нужно уметь обрабатывать.
Что делать, если кто-то всё  же додумается написать +3.5? Я считаю, что нужно отбросить то, что после точки или запятой и всё.

2022-06-28 10:26 UTC, AntonZelinsky commented on src/get_timezone.py
> +            utc = int(list(filter(None, text.split("UTC")))[0])
+ обязателен

2022-06-28 10:27 UTC, KaterinaSolovyeva commented on src/get_timezone.py
> +            utc = int(list(filter(None, text.split("UTC")))[0])
Australia/Darwin +9:30

2022-06-28 10:27 UTC, KaterinaSolovyeva commented on src/get_timezone.py
> +            utc = int(list(filter(None, text.split("UTC")))[0])
https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

2022-06-28 10:29 UTC, MatMerd commented on src/get_timezone.py
> +            utc = int(list(filter(None, text.split("UTC")))[0])
Я уже думал про регулярку. Но если таймзона составная, регулярка становится сильно не удобной. И тоже. Писать её локально в коде - не круто. Хапдкод получается

2022-06-28 13:04 UTC, KaterinaSolovyeva commented on src/get_timezone.py
> +            utc = int(list(filter(None, text.split("UTC")))[0])
Вопросы: 
1. что в итоге передавать?
Так: UTC+02:00, UTC-02:30
Или так: UTC+2, UTC-2.5?
2. что просим ввести пользователя?
Так: UTC+02:00, UTC-02:30, UTC+2, +2, -2:30 ?
Или иначе?

Уточните задачу, пожалуйста

2022-06-28 16:11 UTC, AntonZelinsky commented on src/get_timezone.py
> +            utc = int(list(filter(None, text.split("UTC")))[0])
Ой, мне кажется,  тут регулярка будет очень простой. 
Матвей, подскажи кейсы которые тебя смущают?

2022-06-30 14:22 UTC, veselij requested changes

2022-06-30 14:22 UTC, veselij commented on src/get_timezone.py
>  from service.api_client_fake import FakeAPIService
там сейчас поменялось после рефакторинг

2022-06-30 14:22 UTC, veselij commented on src/get_timezone.py
>      api = FakeAPIService()
надо теперь использовать просто api_service = APIService()

2022-06-30 14:22 UTC, veselij commented on src/get_timezone.py
> +        hours, minutes = divmod(utc * 60, 60)
тут какая-то магия, не могу понять, ты же уже перевела в часы, а потом опять в минуты.

2022-06-30 14:22 UTC, veselij commented on src/get_timezone.py
> +        pass
давай сюда место pass напишем в чат, что "вы установили таймзону X"

2022-06-30 15:00 UTC, KaterinaSolovyeva commented on src/get_timezone.py
> +        hours, minutes = divmod(utc * 60, 60)
мне нужны часы и минуты, чтобы записать в виде hours:minutes.
Мне показалось, что это самый простой и наглядный способ
строчка 53 высчитывает сколько часов(не округляя) например: 3.15
54 - разбивает это значение на часы и минуты. Например 3 часа 9 минут

2022-06-30 15:08 UTC, KaterinaSolovyeva commented on src/get_timezone.py
> +        hours, minutes = divmod(utc * 60, 60)
сделать так?:
```
utc = float(time_zone.utcoffset(utc_time).total_seconds() / 60)
        hours, minutes = divmod(utc, 60)
```

2022-06-30 15:08 UTC, veselij approved these changes

2022-06-30 15:09 UTC, merged

2022-06-30 15:09 UTC, MatMerd commented on src/get_timezone.py
> +        hours, minutes = divmod(utc * 60, 60)
Ну по факту , это действительно самый лёгкий способ

2022-06-30 15:11 UTC, MatMerd commented on src/get_timezone.py
> +        hours, minutes = divmod(utc * 60, 60)
@KaterinaSolovyeva да, сделай так, как указала в последнем сообщении