imports did not work, added PYTHONPATH
Studio-Yandex-Practicum/ask_nenaprasno_bot pull request #38
Opened 2022-06-28 20:13 UTC by agamova

2022-06-28 20:17 UTC, agamova commented
после очередного pull'а ветки develop в контейнере перестали работать импорты типа from bot import init_bot.
Гуглеж помог решить проблему добавлением PYTHONPATH

2022-06-29 15:39 UTC, veselij requested changes
не, трогать pythonpath точно не надо
посмотри тут
https://practicum-students.slack.com/archives/C03JFJG1N9Z/p1656166999769889

2022-06-29 15:39 UTC, veselij commented on Dockerfile
>  CMD uvicorn src.run_webhook_api:api --host 0.0.0.0 --port 8000 --reload
попробуй так сделать
```suggestion
CMD uvicorn run_webhook_api:api --host 0.0.0.0 --port 8000 --reload
```

2022-07-01 11:06 UTC, veselij approved these changes

2022-07-01 11:19 UTC, merged