Feature/trello_data_deserialization
Studio-Yandex-Practicum/ask_nenaprasno_bot pull request #40
Opened 2022-06-29 17:56 UTC by IPfa

Написан десирилизатор данных Трелло. На данный момент при создании карточки/назначении врача из Трелло берется только параметр url. При необходимости можно расширить датакласс и функцию для получения других параметров.

Десирилизатор добавлен в функцию trello_webhook_api.

2022-06-29 20:40 UTC, veselij requested changes
у тебя весь файл переписался, не понятно, где твои изменения. Поправь пожалуйста.

вот, что нам надо будет отправить эксперту:

"Ура! Вам назначена новая заявка **номер заявки** 
Посмотреть заявку на сайте (**cсылка на заявку в Просто спросить**)
----
В работе количество  заявок
Истекает срок у количество заявок

Открыть Trello (ссылка на доску в trello с отфильтрованными заявками по эксперту)
"

соответственно нам еще надо будет номер заявки и ссылку на сайт вытащить (но пока мы их не знаем - займемся позже), ссылку на доску ты вытащил, чтобы отфильтровать еще надо вытащить id назначенного специалиста на карточку. и надо проверить что было именно действие по назначению ответственного на карточку, т.е.   "action":{
      "id":"62af0955f14bde44b5ec2787",
и если да то тогда запускать свою функцию

   "action":{
      "id":"62af0955f14bde44b5ec2787",
      "idMemberCreator":"553743398a7633ddfa752831",
      "data":{
         "idMember":"553743398a7633ddfa752831",
         "card":{
            "id":"62af064216efb9139fd6b6b7",
            "name":"test card",
            "idShort":171,
            "shortLink":"FtTNIarf"
         },
         "board":{
            "id":"57973d3b0edae8e231b2eaba",
            "name":"Common",
            "shortLink":"8Nxdr2iD"
         },
         "member":{
            **"id":"553743398a7633ddfa752831",**
            "name":"Александр Минаев"
         }
      },

2022-06-30 09:20 UTC, AntonZelinsky commented
Предлагаю для дессиарилизации json в dataclass добавить библиотеку [Dataclasses Json](https://pypi.org/project/dataclasses-json/) или [Marshmallow Dataclass](https://pypi.org/project/marshmallow-dataclass/). Первая, конечно будет по проще.

2022-06-30 09:42 UTC, veselij commented
> Предлагаю для дессиарилизации json в dataclass добавить библиотеку [Dataclasses Json](https://pypi.org/project/dataclasses-json/) или [Marshmallow Dataclass](https://pypi.org/project/marshmallow-dataclass/). Первая, конечно будет по проще.
> 
> 

А ты хочешь всю портянку ответа от трелло в датакласс с кучей полей записать или только нужные нам поля?

2022-06-30 11:34 UTC, AntonZelinsky commented
Ну, для начала точно только нужные поля

2022-07-01 21:03 UTC, AntonZelinsky approved these changes
А вообще, давайте свойства сделаем для дата-класса, чтобы всё мапилось, эти данные же не меняются, а так, всё будет хорошо выглядеть.
МОжно даже не в этом ПРе это сделать. Пофикси коменты и запуш, а потом принимайся за датаклассы. Успеешь до мержа, супер, нет, то даже лучше, всё в одном ПРе уйдёт

2022-07-01 21:03 UTC, AntonZelinsky commented on requirements.txt
> +marshmallow==3.17.0; python_version >= "3.7"
В твоём коде эта библиотека не используется, только добавляется зависимость

2022-07-01 21:03 UTC, AntonZelinsky commented on src/run_webhook_api.py
> +        if "action" in response_json.keys():
Судя по примеру который приложили в [наш код](https://github.com/Studio-Yandex-Practicum/ask_nenaprasno_bot/blob/develop/src/example/trello_request.json), там есть и экшен и модель, поэтому, тебе нужно сразу после получения json десериализовать его и уже работать с датаклассом, а не с ключами. И тут как раз половина кода перепишется, как я и писал раньше.

2022-07-01 21:03 UTC, AntonZelinsky commented on src/run_webhook_api.py
> +            return Response("Got trello request.", status_code=httpx.codes.OK)
Трелло не нужно знать что мы получили что-то и что с этим делаем, им просто окей прислать. Но комментарий у ифа будет не лишним, очень упростит другим разработчикам понимание

2022-07-03 20:51 UTC, closed without merging