create function to check or create webhook to trello
Studio-Yandex-Practicum/ask_nenaprasno_bot pull request #48
Opened 2022-07-01 17:42 UTC by K3llar

Была создана функция для создания и проверки вебхука в трелло.
На данный момент она никак не прикручена к старту сервера так как я не понял как лучше это выполнить.

В config добавлены новые переменные необходимые для работы функции.

Сделал рефактор функции trello_webhook_api.
В старом варианте функции при входе в нее не json-объекта она ожидаемо падала с JSONDecodeError.
Также ушел от проверки на KeyError путем метода .get() словаря.
Есть вопрос по return. В базовом варианте он находился в блоке finally и на него ругался pylint с ошибкой
"W0150: return statement in finally block may swallow exception (lost-exception)".
Есть ли вообще необходимость в данном случае в блоке finally?

Плюс мелкие изменения isort и black в других файлах.

Также заметил что должным образом не работает логгер, но в сути не разбирался.

2022-07-02 08:03 UTC, veselij requested changes
по поводу как запускать, надо подумать можно ли это встроить как то в запуск старлет или же сделать отданный скрипт

2022-07-02 08:03 UTC, veselij commented on src/core/config.py
> +TRELLO_TOKEN = env.get("TRELLO_TOKEN")  # токен для доступа к TRELLO
надо также добавить в файл .example

2022-07-02 08:03 UTC, veselij commented on src/create_trello_webhook.py
> +        "callbackURL": f"{config.WEBHOOK_URL}/trelloWebhookApi",
сделай пожалуйста в .env.example и в config отдельную переменную для WEBHOOK_URL_TRELLO и там полный путь, а существующий WEBHOOK_URL переименуй в WEBHOOK_URL_TELEGRAM

2022-07-02 08:03 UTC, veselij commented on src/create_trello_webhook.py
> +    data = (await response.aread()).decode("utf-8")
лучше сделать так 
```
        async with httpx.AsyncClient() as client:
            response = await client.get(url)
            response = await response.json()
```

2022-07-02 10:00 UTC, K3llar commented on src/core/config.py
> +TRELLO_TOKEN = env.get("TRELLO_TOKEN")  # токен для доступа к TRELLO
выполнено

2022-07-02 10:02 UTC, K3llar commented on src/create_trello_webhook.py
> +        logging.info(f"Trello webhook id: {response['id']}")
конструкция с try except необходима потому, что при ответе с имеющимся webhook_id в качестве ответа приходит просто text.

2022-07-02 10:03 UTC, K3llar commented on src/create_trello_webhook.py
> +        logging.info(response.text)
конструкция с try except необходима потому, что при ответе с имеющимся webhook_id в качестве ответа приходит просто text.

2022-07-02 10:04 UTC, K3llar commented on src/create_trello_webhook.py
> +        "callbackURL": f"{config.WEBHOOK_URL}/trelloWebhookApi",
выполнено, проведена замена имени переменной в файлах проекта

2022-07-02 10:12 UTC, K3llar commented
Исправил замечания.
И хочу внести предложение чтобы при слиянии веток feature с develop выполнять squash and merge, а не просто merge. Я не вижу смысла в сохранении истории разработки фичи при сохранении ветки в которой она была разработана, а история разработки выглядит гораздо более презентабельно и легко возвращаться к нужному состоянию проекта

2022-07-02 10:16 UTC, veselij commented
> по поводу как запускать, надо подумать можно ли это встроить как то в запуск старлет или же сделать отданный скрипт

@AntonZelinsky  @MatMerd как думаете? может стоит просто отдельный скрипт запускать в докере?

2022-07-02 10:29 UTC, veselij approved these changes
а ты не пробовал в startup положить create_trello_webhook?

2022-07-02 10:30 UTC, K3llar commented
Пробовал, все падает

2022-07-02 10:45 UTC, veselij commented on src/create_trello_webhook.py
> +from core.logger import logging
import logger нужен

2022-07-02 10:50 UTC, veselij commented on src/create_trello_webhook.py
> +        logging.info(response.text)
у тебя все падает, так как там json в ответе приходит, если что-то не так, но не обязательно 200 код, может быть и 502 и при этом в json нет id и падает с KeyError

2022-07-02 13:45:18,317 INFO core.logger:	Trello webhook id: {'message': 'URL (https://6ebc-77-105-154-181.eu.ngrok.io/trelloWebhookApi) did not return 200 status code, got 502', 'error': 'ERROR'}

надо в нутри try просто легировать response

2022-07-02 11:03 UTC, K3llar commented on src/create_trello_webhook.py
> +        logging.info(response.text)
Добавил логирование ошибки

2022-07-02 11:13 UTC, K3llar commented
Исправил использование лога
При ошибке (например неправильном url) логирую message из полученного json.

2022-07-02 11:15 UTC, K3llar commented on src/create_trello_webhook.py
> +from core.logger import logging
исправил

2022-07-02 11:39 UTC, K3llar commented
Надо ли по всему проекту сделать правильное использование логгера?
Он везде используется через logging

2022-07-02 11:56 UTC, K3llar commented
> Надо ли по всему проекту сделать правильное использование логгера? Он везде используется через logging

логгер неправильно использовался только в run_webhook_api.py.

**Исправлено**

2022-07-02 12:58 UTC, AntonZelinsky commented on src/run_webhook_api.py
> +        response_json: dict = dict(await request.json())
А зачем ты влазишь в приём веб хуков, это же другая задача. Для её даже [ПР](https://github.com/Studio-Yandex-Practicum/ask_nenaprasno_bot/pull/40/files) есть

2022-07-02 12:58 UTC, AntonZelinsky commented on src/create_trello_webhook.py
> +    await create_trello_webhook()
И что, это нельзя запустить в файле запуска веб апи? Мне кажется можно. Плюс, у библиотеки старлет есть функция запуска параллельно «асинхронного потока» от основного приложения. Но я не вижу проблемы с тем, чтобы просто дёрнуть этот запрос и продолжить запуск сервера. Всё должно взлететь без проблем
![image](https://user-images.githubusercontent.com/1431279/177001045-399c46a8-075d-4d92-837c-01e7036bc034.png)

2022-07-02 12:58 UTC, AntonZelinsky commented on .env.example
> +TRELLO_URL = https://api.trello.com/1/webhooks/ # адрес для обращения к api trello
Нет смысла делать переменную, она никогда не поменяется, а если вдруг поменяется, то нужно будет всё приложение переделывать

2022-07-02 12:58 UTC, AntonZelinsky commented on .env.example
>  HOST=127.0.0.1 # host для доступа к uvicorn серверу, по умолчанию localhost или 127.0.0.1
Видил что Саша писал что-то такое, но не понимаю зачем это. У нас есть хост с нашим доменом, следовательно, дублировать его два раза не стоит, так как велика вероятность ошибки. Просто подставлять хост туда куда нужно.
Потом, роут для телеграма и трелло у нас не динамический и меняться он никогда не будет, поэтому выносить его в переменные точно не стоит.
Я даже не вижу смысла выностить его в константы, так как он используется только для установки роута всего в двух местах. пусть будет хардкод и переменная из конфига с хостом + хардкод

2022-07-02 13:02 UTC, veselij commented on src/run_webhook_api.py
> +        response_json: dict = dict(await request.json())
Он там просто падал. В случае если ответ строка

2022-07-02 13:04 UTC, veselij commented on src/create_trello_webhook.py
> +    await create_trello_webhook()
> И что, это нельзя запустить в файле запуска веб апи? Мне кажется можно. Плюс, у библиотеки старлет есть функция запуска параллельно «асинхронного потока» от основного приложения. Но я не вижу проблемы с тем, чтобы просто дёрнуть этот запрос и продолжить запуск сервера. Всё должно взлететь без проблем
> 
> ![image](https://user-images.githubusercontent.com/1431279/177001045-399c46a8-075d-4d92-837c-01e7036bc034.png)
> 
> 

Так не будет работать. Так как, до того как выполнился startup сервер не будет отвечать на запросы. А трелло, после получения запроса на активацию хука, делает проверку рабочий ли endpoint который ему прислали. И в итоге мы шлем запрос в трелло, но не запущен еще сервер. И трело не получив 200 ответ. Не активирует хук

2022-07-02 13:06 UTC, veselij commented on .env.example
>  HOST=127.0.0.1 # host для доступа к uvicorn серверу, по умолчанию localhost или 127.0.0.1
В нас в одном из PR мы как раз поправили роуты и забыли во всех остальных местах. Поэтому я переинжинирил. Но согласен такое не должно больше по идее повторяться и можно захардкожить. Просто быть внимательными когда роуты переименуем

2022-07-02 16:53 UTC, K3llar commented on src/run_webhook_api.py
> +        response_json: dict = dict(await request.json())
В коде указанном в ПР до сих пор не учтен вариант того, что на вход придет head запрос без тела. Расположение JSONDecodeError до которого нельзя дойти никогда.
Я лишь привел функцию к минимальному работоспособному состоянию.

2022-07-02 16:54 UTC, K3llar commented on .env.example
> +TRELLO_URL = https://api.trello.com/1/webhooks/ # адрес для обращения к api trello
исправлю url в функции

2022-07-02 16:56 UTC, K3llar commented on .env.example
>  HOST=127.0.0.1 # host для доступа к uvicorn серверу, по умолчанию localhost или 127.0.0.1
Правильно ли я понимаю что webhook_url_telegram/trello будет задаваться в config и из него вызываться? Просто уберем лишние константы из .env?

2022-07-02 17:01 UTC, K3llar commented on .env.example
>  HOST=127.0.0.1 # host для доступа к uvicorn серверу, по умолчанию localhost или 127.0.0.1
На этапе разработки бота не хотелось бы вносить адрес из ngrok в двух разных местах, лучше в одном. По моему лучше оставить одну переменную webhook_url, а в местах вызова дописывать нужный endpoint

2022-07-02 17:31 UTC, veselij commented on .env.example
>  HOST=127.0.0.1 # host для доступа к uvicorn серверу, по умолчанию localhost или 127.0.0.1
> На этапе разработки бота не хотелось бы вносить адрес из ngrok в двух разных местах, лучше в одном. По моему лучше оставить одну переменную webhook_url, а в местах вызова дописывать нужный endpoint

да, так и надо. поправь пожалуйста

2022-07-03 20:16 UTC, veselij approved these changes

2022-07-03 20:16 UTC, veselij commented on src/create_trello_webhook.py
> +asyncio.run(main())
вот это нам уже не надо

2022-07-03 20:16 UTC, veselij commented on src/create_trello_webhook.py
> +async def main():
может как-то более информативно назвать и тогда не придётся переименовывать после импорта в файле запуска севера

2022-07-04 03:03 UTC, K3llar commented on src/create_trello_webhook.py
> +asyncio.run(main())
Думал оставить чтобы можно было в качестве скрипта вызывать.

2022-07-04 03:04 UTC, K3llar commented on src/create_trello_webhook.py
> +async def main():
Переменную сегодня вечером.
После коммита можно мерджить?

2022-07-04 15:07 UTC, merged