Trello Data Deserializer Ver.4
Studio-Yandex-Practicum/ask_nenaprasno_bot pull request #49
Opened 2022-07-03 20:33 UTC by IPfa

Создан новый PR для сервиса десериализации данных от trello. Предыдущий PR необходимо удалить.

2022-07-03 20:57 UTC, veselij requested changes
надо постараться, чтобы файлы больше не переписывались, иначе конфликты будут

2022-07-03 20:57 UTC, veselij commented on src/service/trello_data_deserializer.py
> +class TrelloModel:
названия моделей надо поменять немного, чтобы в каждой заканчивалось на Model, и отображало суть, что это данные карточки

2022-07-03 20:57 UTC, veselij commented on src/service/trello_data_deserializer.py
> +    doctor_id: str = field(metadata=config(field_name="id"))
user_id лучше

2022-07-03 20:57 UTC, veselij commented on src/service/trello_data_deserializer.py
> +    action: TrelloAction
вот тут не понятно, что это, модель чего, карточки или доски?

2022-07-03 20:57 UTC, veselij commented on src/run_webhook_api.py
> +        logging.info("Got not trello or empty request.")
ошибку тоже надо логировать, и текст может в заблуждение вводить, так как могут быть другие причины, лучше описать в чем проблема, а не что могло быть причиной

2022-07-03 20:57 UTC, veselij commented on src/run_webhook_api.py
> +        logging.info(f"New case assigned to the doctor. {trello_data}.")
тут не только назначения будут

2022-07-03 20:57 UTC, veselij commented on src/run_webhook_api.py
> +        return Response("New case assigned to the doctor.", status_code=httpx.codes.OK)
трелло просто надо код отправить - без сообщения

2022-07-05 12:16 UTC, veselij approved these changes

2022-07-05 15:49 UTC, K3llar commented on src/run_webhook_api.py
> +        trello_data: TrelloDeserializerModel = TrelloDeserializerModel.from_dict(await request.json())
На вход этой функции может прийти не json, а пустой head-запрос.
По логике await request.json() упадет с JSONDecodeError, который не прописан в except.
Прошу рассмотреть данный момент.

2022-07-05 16:10 UTC, veselij commented on src/run_webhook_api.py
> +        trello_data: TrelloDeserializerModel = TrelloDeserializerModel.from_dict(await request.json())
да все верно, надо добавить @IPfa

2022-07-05 21:08 UTC, veselij requested changes

2022-07-05 21:08 UTC, veselij commented on src/run_webhook_api.py
> +        return Response(status_code=httpx.codes.BAD_REQUEST)
тут надо 200 отправить трелло. иначе она хук не примет

2022-07-06 07:43 UTC, veselij approved these changes

2022-07-06 07:44 UTC, merged