Feature/injected api token
Studio-Yandex-Practicum/ask_nenaprasno_bot pull request #50
Opened 2022-07-04 09:39 UTC by Xewus

Основная задача: [Авторизация на сервере API через токен](https://www.notion.so/API-701d083489be4954801afd11a16cf3de)
Дополнительно упростил в функции запроса строку с формированием URL, так как httpx при осуществлении запроса всё равно делает `base_url` + 'url`.
Также убрал `from typing import Optional` , так как в Python 3.10 это не нужно.
Дополнительно `isort` при коммите поправил импорта в затронутых мной файлах.

2022-07-04 10:07 UTC, AntonZelinsky approved these changes
Почему первые 2 файла полностью зелёные?

2022-07-04 10:07 UTC, AntonZelinsky commented on src/service/api_client/site_api_service.py
> +        self.site_url: str = config.SITE_API_URL
А в REQUEST_ATTRS зачем `base_url`?

2022-07-04 10:11 UTC, Xewus commented on src/service/api_client/site_api_service.py
> +        self.site_url: str = config.SITE_API_URL
Я в описание давал объяснение.
httpx в любом случае делает `base_url + url`, так как бот будет обращаться к одному ресурсу, можно общую часть вынести аргумент, а не формироватьв каждом запросе строку вида `f'{site_url}/url'

2022-07-04 10:16 UTC, Xewus commented on src/service/api_client/site_api_service.py
> +        self.site_url: str = config.SITE_API_URL
Блок из httpx:
merge_raw_path = self.base_url.raw_path + merge_url.raw_path.lstrip(b"/")
return self.base_url.copy_with(raw_path=merge_raw_path)

2022-07-04 10:31 UTC, Xewus commented
> Почему первые 2 файла полностью зелёные?

Предполагаю, что при комиите встроенные проверки там что-то делали.
Хотя визуальных отличий нет, кроме добавленной строки с константой.
Сравнение произвольных строк тоже не выявило изменений.
Сделал ещё коммит с переименованием константы - третий файл тоже позеленел.
Я не знаю почему так.

2022-07-04 13:13 UTC, AntonZelinsky commented on src/service/api_client/site_api_service.py
> +        self.site_url: str = config.SITE_API_URL
Не нужно усложнять. base_url — это часть этого класса, без него они всё не имеет смысла, поэтмоу, от туда удалить. То же относится и к хиедрам!

2022-07-04 13:15 UTC, AntonZelinsky commented
Больше не нужно схлопывать и форспушить свои комиты. Я поставлю ограничение на это на уровне гитхаба. Сделай, пожалуйста, объявление в общем канале, что больше схлопывать и пушить комиты нельзя и такой код не получится смержить

2022-07-04 16:43 UTC, Xewus commented on src/service/api_client/site_api_service.py
> +        self.site_url: str = config.SITE_API_URL
Перенёс `headers` в атрибуты класса.
Стоит отметить, что инициализация экземпляра класса - жёсткая.

2022-07-05 12:10 UTC, veselij approved these changes

2022-07-05 13:40 UTC, veselij requested changes
Владислав, обнови смерди последние изменения из develop и тогда файлы не должны будут перезаписываться

2022-07-05 14:37 UTC, Xewus commented
> Владислав, обнови смерди последние изменения из develop и тогда файлы не должны будут перезаписываться

Сделал повторный rebase, что-то обновилось,
> Из github.com:Studio-Yandex-Practicum/ask_nenaprasno_bot
>  ab890b5..3b55c5e  develop    -> origin/develop

 но там видимо файлы, с которыми я работал, не затронуты, потому коммит и пуш не осуществился.
 ПС. Проблема полностью зеленого кода в разнице "окончания строк". Окончания строк исправляются сами каким-то линтером во время проверки коммита.
 Доказательство. Если добавить  в url `?w=1` , то эту разницу не будет показывать.

2022-07-05 14:52 UTC, veselij commented
> > Владислав, обнови смерди последние изменения из develop и тогда файлы не должны будут перезаписываться
> 
> Сделал повторный rebase, что-то обновилось,
> 
> > Из github.com:Studio-Yandex-Practicum/ask_nenaprasno_bot
> > [ab890b5](https://github.com/Studio-Yandex-Practicum/ask_nenaprasno_bot/commit/ab890b5ccf498b829a74d4987cd8cea264fd6fa9)..[3b55c5e](https://github.com/Studio-Yandex-Practicum/ask_nenaprasno_bot/commit/3b55c5eb0ae309804289565433117cc943d6c89e)  develop    -> origin/develop
> 
> но там видимо файлы, с которыми я работал, не затронуты, потому коммит и пуш не осуществился. ПС. Проблема полностью зеленого кода в разнице "окончания строк". Окончания строк исправляются сами каким-то линтером во время проверки коммита. Доказательство. Если добавить в url `?w=1` , то эту разницу не будет показывать.

@zhss1983 подскажи насчет настроек окончания строк, я помню, ты менял вроде? Владислав а pre-commit настроен у тебя по ридми?

2022-07-05 16:20 UTC, Xewus commented
> Владислав а pre-commit настроен у тебя по ридми?

По readme даже `poetry` поставить не вышло, делал по оф. инструкции.
Тем не менее, при коммите там происходят некие автоматические действия проверок и также автоматически изменяются некоторые строки в файлах.
Результат этих действий выводится в терминал в разукрашенном виде, где и было замечено сообщение об изменении EOL. Вот так выглядит.
`trim trailing whitespace.............................(no files to check)Skipped
fix end of files.....................................(no files to check)Skipped
check yaml...........................................(no files to check)Skipped
check for merge conflicts............................(no files to check)Skipped
mixed line ending....................................(no files to check)Skipped
don't commit to branch...................................................Passed
trim trailing whitespace.............................(no files to check)Skipped
black................................................(no files to check)Skipped
isort................................................(no files to check)Skipped
pylint...............................................(no files to check)Skipped
Export DEVELOPMENT requirements.txt..................(no files to check)Skipped
Export PRODUCTION requirements.txt...................(no files to check)Skipped
`

А вот так выглядит изменение концов строк

`mixed line ending........................................................Failed 
- hook id: mixed-line-ending
- it code: 1
- files were modified by this hook
`

2022-07-05 23:14 UTC, AntonZelinsky commented
Если не получилось установить пи инструкции, то добавить изменения в файл ридми и опиши узкие места которые там не описаны

2022-07-06 06:32 UTC, Xewus commented
> Если не получилось установить пи инструкции, то добавить изменения в файл ридми и опиши узкие места которые там не описаны.

Честно говоря, уже прошло больше недели, сильно углубляться в проблему для её решения не пришлось, то и не помню нюансы. Можно, ради эксперимента, удалить poetry и повторить...
Единственно, для запуска приложения мне нужно внедрять слово `python`, то есть `poetry run python src/run_bot.py 
` , а так как использовать `poetry` начал в последних рядах и никто до этого не объявлял о проблеме, то решил, что у других, наверное, всё работает согласно `readme` .

> И в чём сейчас проблема? Из лога же видно, что файлы были изменены автокорректером

Я не знаю. Претензия была, что "весь файл зелёный", причина сего найдена.
На данный момент мне показывает, что слияние заблокировано Александром.

2022-07-06 07:40 UTC, veselij commented
> > Если не получилось установить пи инструкции, то добавить изменения в файл ридми и опиши узкие места которые там не описаны.
> 
> Честно говоря, уже прошло больше недели, сильно углубляться в проблему для её решения не пришлось, то и не помню нюансы. Можно, ради эксперимента, удалить poetry и повторить... Единственно, для запуска приложения мне нужно внедрять слово `python`, то есть `poetry run python src/run_bot.py ` , а так как использовать `poetry` начал в последних рядах и никто до этого не объявлял о проблеме, то решил, что у других, наверное, всё работает согласно `readme` .
> 
> > И в чём сейчас проблема? Из лога же видно, что файлы были изменены автокорректером
> 
> Не знаю. Претензия была, что "весь файл зелёный", причина сего найдена. На данный момент мне показывает, что слияние заблокировано Александром.

проблема в том, что из-за того что поменял файл config - не изменив ничего в нем, то сейчас получил конфликт с другим PR, где отрефакторили config. разреши пожалуйста конфликт и смерджим

2022-07-06 10:06 UTC, zhss1983 commented
> > Владислав а pre-commit настроен у тебя по ридми?
> 
> По readme даже `poetry` поставить не вышло, делал по оф. инструкции. Тем не менее, при коммите там происходят некие автоматические действия проверок и также автоматически изменяются некоторые строки в файлах. Результат этих действий выводится в терминал в разукрашенном виде, где и было замечено сообщение об изменении EOL. Вот так выглядит. `trim trailing whitespace.............................(no files to check)Skipped fix end of files.....................................(no files to check)Skipped check yaml...........................................(no files to check)Skipped check for merge conflicts............................(no files to check)Skipped mixed line ending....................................(no files to check)Skipped don't commit to branch...................................................Passed trim trailing whitespace.............................(no files to check)Skipped black................................................(no files to check)Skipped isort................................................(no files to check)Skipped pylint...............................................(no files to check)Skipped Export DEVELOPMENT requirements.txt..................(no files to check)Skipped Export PRODUCTION requirements.txt...................(no files to check)Skipped `
> 
> А вот так выглядит изменение концов строк
> 
> `mixed line ending........................................................Failed
> 
> * hook id: mixed-line-ending
> * it code: 1
> * files were modified by this hook
>   `

Я тоже столкнулся с такой проблемоцй. При добавлении через poetry библиотеки он применил другой тип конца строки (нежели установленный по умолчанию). Пришлось в PyCharme дважды конвертировать строки из одного формата в другой.
После этого всё прошло.

2022-07-06 10:29 UTC, Xewus commented
Конфликт появился из-за того, что смёрджили вчера ПР Антона. Сделал ребейз ещё раз. Попутно запитонил функцию `get_bool`  в `config.py` .

2022-07-06 10:30 UTC, zhss1983 commented
Конец строки был выбран как CRLF по какой-то причине, не с потолка. Но если честно - сейчас не помню что меня сподвигло именно на него. Замечал что гит по своему конвертит окончания для некоторых файлов. Может быть в этом проблема.

2022-07-06 10:35 UTC, veselij commented
> Конец строки был выбран как CRLF по какой-то причине, не с потолка. Но если честно - сейчас не помню что меня сподвигло именно на него. Замечал что гит по своему конвертит окончания для некоторых файлов. Может быть в этом проблема.

Вот мне кажется лучше в прехуках убрать все манипуляции с окончанием строк, чтобы то что пришло с гита то и осталось. А не переписывалось

2022-07-06 10:37 UTC, Xewus commented
> Конец строки был выбран как CRLF по какой-то причине, не с потолка. Но если честно - сейчас не помню что меня сподвигло именно на него. Замечал что гит по своему конвертит окончания для некоторых файлов. Может быть в этом проблема.

Для эксперимента изменял вчера на один символ произвольный файл, при `git commit` также появляется сообщение об изменение концов... На гитхаб, конечно не пихал его, чтоб проверить - позеленеет или нет. А с другой стороны, никто ж вроде пока не попадал на этом.

2022-07-06 10:59 UTC, veselij commented
> > Конец строки был выбран как CRLF по какой-то причине, не с потолка. Но если честно - сейчас не помню что меня сподвигло именно на него. Замечал что гит по своему конвертит окончания для некоторых файлов. Может быть в этом проблема.
> 
> 
> 
> Для эксперимента изменял вчера на один символ произвольный файл, при `git commit` также появляется сообщение об изменение концов... На гитхаб, конечно не пихал его, чтоб проверить - позеленеет или нет. А с другой стороны, никто ж вроде пока не попадал на этом.

Есть ощущение у многих прехук не настроен был поэтому они не попадали.

2022-07-07 07:33 UTC, veselij approved these changes

2022-07-07 07:33 UTC, merged