Feature/refactor env
Studio-Yandex-Practicum/ask_nenaprasno_bot pull request #52
Opened 2022-07-05 14:33 UTC by Andrey-oss-ai

2022-07-05 16:07 UTC, veselij requested changes

2022-07-05 16:07 UTC, veselij commented on src/core/config.py
>  )
а в чем отличие, перенеси значение в .env и env.example а тут функцию const_str используй

2022-07-05 16:07 UTC, veselij commented on src/core/config.py
> +IS_FAKE_API = get_const_string(
надо сделать еще функцию bool и тут ее использовать

2022-07-05 19:26 UTC, enclosser commented on src/core/config.py
> +IS_FAKE_API = get_const_string(
Новую функцию добавил

2022-07-05 23:19 UTC, AntonZelinsky approved these changes

2022-07-05 23:19 UTC, AntonZelinsky commented on src/core/config.py
> +def get_const_string(setting: str) -> str:
`const` везде удали из названий функций

2022-07-05 23:19 UTC, AntonZelinsky commented on src/core/config.py
> +    return env.get(setting)
Чем это функция отличается от get_const_string?

2022-07-05 23:38 UTC, Andrey-oss-ai commented on src/core/config.py
> +def get_const_string(setting: str) -> str:
Да согласен названия мне самому не понравились, поправим

2022-07-05 23:39 UTC, Andrey-oss-ai commented on src/core/config.py
> +    return env.get(setting)
Не заметил по сути ничем))) 
ну тогда только если вот так будет актуально?

def get_bool(setting: str) -> bool:
    if setting == "True":
        return True
    else:
        return False

2022-07-06 00:37 UTC, Andrey-oss-ai commented on src/core/config.py
> +    return env.get(setting)
Ничем исправил)

2022-07-06 07:35 UTC, veselij approved these changes

2022-07-06 07:36 UTC, merged