Updated healthcheck function
Studio-Yandex-Practicum/ask_nenaprasno_bot pull request #55
Opened 2022-07-06 23:25 UTC by firepanda70

Обновил функцию-заглушку healthcheck. Так как по тз эндпоинт к апи базы данных для проверки работоспособности будет добавлен потом, использовал функцию get_bill.

2022-07-07 21:38 UTC, AntonZelinsky commented on src/run_webhook_api.py
> +        "Database_is_avaliable": False,
Создай модельку и её экземпляр, а при проверке устанавливай значения в тру. 
Трелло можно не проверять, похоже, мы от него избавимся. 
Ожидать прилёта исключения плохой подход, апишка скорее всего не упадёт никогда, а вернёт null. 
Но в принципе, для первой версии сойдёт, потом переделаем

2022-07-08 04:20 UTC, firepanda70 commented
Добавил новый файл с моделью для сериализации, поле для трелло убрал

2022-07-09 09:41 UTC, veselij requested changes

2022-07-09 09:41 UTC, veselij commented on src/run_webhook_api.py
> +        api_service.get_bill()
забыл await

2022-07-09 09:41 UTC, veselij commented on src/run_webhook_api.py
> +    health = HealthSerializerModel()
а зачем нам сериалайзер какой то создавать? не лучше использовать 2 локальные переменные? и отдать JSONResponse просто дикт?

2022-07-10 02:30 UTC, firepanda70 commented on src/run_webhook_api.py
> +    health = HealthSerializerModel()
Дак выше Антон написал, что надо модель сделать. У меня  так изначально и было

2022-07-10 14:32 UTC, veselij commented on src/run_webhook_api.py
> +    health = HealthSerializerModel()
ok, не заметил

2022-07-10 14:34 UTC, veselij approved these changes

2022-07-11 11:57 UTC, AntonZelinsky approved these changes

2022-07-11 11:57 UTC, AntonZelinsky commented on .env.example
> +WEBHOOK_URL=http://example.url# адрес сервера, где будет запущен бот
Это какое-то издветельство, в одном ПРе добавляется проблем перед коментарием, в другом удаляется и так уже 3 раза видел! @veselij @MatMerd определитесь какому правилу следуем и примите как стандарт. И нужно в линтеры занести, чтобы у всех было одинаково. 
На мой взгляд, с пробелом код читаемее

2022-07-11 11:57 UTC, AntonZelinsky commented on src/conversation/menu.py
> +@async_error_logger(name="conversation.requests.button_statistic_month_callback", logger=logger)
@veselij @MatMerd обратите внимание, что logger всегда один и тот же импортируется и нет смысла передавать его каждый раз в этот декоратор. Просто там импортировать и использовать. Рефакторинг для другого ПРа

2022-07-11 11:57 UTC, AntonZelinsky commented on src/conversation/authorization.py
> +        parse_mode=ParseMode.MARKDOWN,
@veselij @MatMerd Вот про это я и говорил, что каждый раз будет передаваться бесполезный параметр маркдауна, хотя он принят у нас как стандарт. Тоже в отдельной задаче...

СТОП, тут же редактирование. 
Это я перепутал. Для редактирования нужно тоже сделать отдельную функцию рядом с функцией отправки. Передавать в неё текущее сообщение и всё как в другой функции.
Хотя ещё раз СТОП!) Тут не редактирование, а ответ на сообщение. Не уверен, что тут должен быть ответ, точно не редактирование?
В любом случае для ответов тоже нужно сделать отдельную функцию.
Зачем? Для того чтобы наши сообщения не проглатывались телеграмом когда их будет больше чем 30 в секунду, а этот порог легко будет перепрыгнут при рассылке. Эту штуку нам предстоит ещё написать.

Но тоже, эти задачи для отдельных ПРов

2022-07-11 11:57 UTC, AntonZelinsky commented on src/service/healthcheck_serializer.py
> +@dataclass_json
Тут не нужен этот dataclass_json, поскольку ты его никак не используешь. 
В этой папке есть файл десириалайзер, а вот появился и файл сериалайзер, для того, чтобы ещё больше раскочегарить наш ад!
Создай файл models и положи туда этот класс. Даже  переименуй на `HealthCheckResponseModel`, так, из названия будет понятно для чего он предназначен.

2022-07-11 11:57 UTC, AntonZelinsky commented on src/core/config.py
> +URL_SITE = "https://ask.nenaprasno.ru/"
Добавь перед этими 4-мя строчками комментарий, что следующий блок используется в сообщениях отправляемыми пользователю. Ну, или как-то по красивее описать. 
А то у нас очень много настроек и сложно понять к чему и что относится



```
############################################################
### Настройки ипользуются в сообщениях отправляемых пользователю
############################################################
```


И кстати, а почему конфиги не берутся из .env файла?

2022-07-11 11:57 UTC, AntonZelinsky commented on .github/workflows/bot_productivity.yaml
> +name: Check bot productivity
[Этот файл уже есть в основной ветке](https://github.com/Studio-Yandex-Practicum/ask_nenaprasno_bot/blob/develop/.github/workflows/bot_productivity.yaml),  как бы проблем тут не было

2022-07-11 12:15 UTC, veselij commented on .env.example
> +WEBHOOK_URL=http://example.url# адрес сервера, где будет запущен бот
что то мне кажется это лезет из-за кривых мердежей, я смотрю PR в VS у меня там только в 2х файлах показывается изменения, а тут аж 11 файлов. это все предыдущие комиты чьи-то похоже...

2022-07-11 12:22 UTC, veselij commented on src/conversation/authorization.py
> +        parse_mode=ParseMode.MARKDOWN,
я задачки записал. но это опять из дргоуго PRа все...

2022-07-11 12:22 UTC, veselij commented on src/conversation/menu.py
> +@async_error_logger(name="conversation.requests.button_statistic_month_callback", logger=logger)
записал

2022-07-11 12:25 UTC, veselij commented on src/core/config.py
> +URL_SITE = "https://ask.nenaprasno.ru/"
это опять другой PR, задачу расписать коменты к настройкам завел, из env решили не брать, так как это будет крайне малоизменяемая информация. и сейчас все эти env дополнительно усложняют отладку. потом можно будет вынести в env или куда там дальше решим- чтобы не программисты могли менять

2022-07-11 13:52 UTC, firepanda70 commented
Что было ко мне, то поправил. Файл .yaml вроде  тоже не в моей стези.

2022-07-12 10:03 UTC, veselij requested changes

2022-07-12 10:03 UTC, veselij commented on src/run_webhook_api.py
> +    return JSONResponse(content=health.to_dict())
а разве есть такой методу to_dict у dataclass? тебе надо импортировать asdict из dataclasses и потом asdict(health)

2022-07-12 12:18 UTC, AntonZelinsky commented on src/run_webhook_api.py
> +    return JSONResponse(content=health.to_dict())
Такой метод наверняка есть у @dataclass_json, но я попросил его убрать, так как не подумал, что он может тут использоваться.
Если он там есть, то тогда лучше вернуть этот декоратор

2022-07-12 16:01 UTC, veselij approved these changes

2022-07-12 16:01 UTC, merged