Проверка workflow
Studio-Yandex-Practicum/ask_nenaprasno_bot pull request #56
Opened 2022-07-07 10:03 UTC by AigulParamonova

Задача - Проверка приложения на работоспособность в каждом ПРе

2022-07-08 08:10 UTC, veselij requested changes

2022-07-08 08:10 UTC, veselij commented on .github/workflows/bot_productivity.yaml
> +          echo "::stop-commands::${{ env.TELEGRAM_TOKEN }}"
это оказалось немного не для того - можно удалить

2022-07-08 08:10 UTC, veselij commented on .github/workflows/bot_productivity.yaml
> +          python3 src/run_bot.py
я не придумал варианта кроме как грохать процесс. @AntonZelinsky  @MatMerd  есть другие идеи?
```suggestion
          python3 src/run_bot.py & sleep 5 && pkill -9 python
```

2022-07-08 08:10 UTC, veselij commented on .github/workflows/bot_productivity.yaml
> +      -develop
пробела не хватает

2022-07-08 08:10 UTC, veselij commented on .github/workflows/bot_productivity.yaml
> +          pip install black==22.3.0
вот это лишнее, мы же не делаем в этой такске этого

2022-07-08 23:45 UTC, AntonZelinsky commented on .github/workflows/bot_productivity.yaml
> +          python3 src/run_bot.py
Нет.. других идей. 

Только запускать бот нужно скорее всего через веб хуки, так как там большая часть приложения. Вопрос только в том, что писать во все секреты. Окей, пусть будет так, а когда будет готов деплой на сервер и понятно что можно захардкодить, а что нужно в инвайрмент переменную загнать, то поправим и тут.


А вообще, смысл в проверки в том, чтобы запустить и проверить, что приложение запустилось. [Тут есть пример проверки](https://stackoverflow.com/questions/14447997/running-a-python-script-within-shell-script-check-status) на то, что вернёт скрипт. Может это поможет. Нужно где-то сломать код и проверить, что мы получаем ошибку.
Вообще, можно передавать флаг внутрь нашего приложения и если он был передан, то самозавершиться через 3 секунды перед этим проверив, что бот запустился. А завершаясь вернуть код, а по коду можно будет понять, всё ли хорошо.

2022-07-09 06:52 UTC, veselij commented on .github/workflows/bot_productivity.yaml
> +          python3 src/run_bot.py
я запускал так работает. если код сломан, то тетс падает. про bash скрипт тоже думал, но такой варинат проще показался, так как в одну строку.

мы можем оба запуска тестировать, надо просто еще добавить строку 


python3 src/run_bot.py & sleep 5 && pkill -9 python
python3 src/run_webhook_api.py & sleep 5 && pkill -9 python

2022-07-09 06:53 UTC, veselij requested changes
Добавь еще пожалуйста команду python3 src/run_webhook_api.py & sleep 5 && pkill -9 python

2022-07-09 07:49 UTC, AigulParamonova commented on .github/workflows/bot_productivity.yaml
> +          python3 src/run_bot.py
у меня почему то без sudo не сработало: `sudo pkill -9 python`

2022-07-09 07:53 UTC, veselij commented on .github/workflows/bot_productivity.yaml
> +          python3 src/run_bot.py
а что не сработало? там еще есть два процесса питона - они без судо не убиваются, но их и не недо убивать.

пможешь принт скинуть, вот как должно быть

![image](https://user-images.githubusercontent.com/23584808/178097044-fc70bc7e-12da-4aac-b426-9e54539ba1a0.png)

2022-07-09 07:59 UTC, AigulParamonova commented on .github/workflows/bot_productivity.yaml
> +          python3 src/run_bot.py
да, точно такая же у меня была, подумала что не срабатывает команда.

2022-07-09 09:36 UTC, veselij requested changes

2022-07-09 09:36 UTC, veselij commented on .github/workflows/bot_productivity.yaml
> +      - feature/check_bot_productivity
мы же договорились на develop тут поменять

2022-07-09 09:40 UTC, AigulParamonova commented on .github/workflows/bot_productivity.yaml
> +      - feature/check_bot_productivity
сейчас исправлю, может из-за этого не срабатывает триггер push, не понимаю

2022-07-09 09:43 UTC, AigulParamonova commented on .github/workflows/bot_productivity.yaml
> +      - feature/check_bot_productivity
В моём тестовом боте работает на pus
![2022-07-09_12-41-08](https://user-images.githubusercontent.com/85585713/178100445-493aca5d-44f7-40b8-afab-0df52c6e01be.png)
h

2022-07-09 10:10 UTC, veselij approved these changes

2022-07-09 10:10 UTC, merged