Feature/button for requesting monthly statistics
Studio-Yandex-Practicum/ask_nenaprasno_bot pull request #58
Opened 2022-07-07 18:50 UTC by AndreyMurysev

Добавил в job функцию user_monthly_stat_job, запустил через обработчик menu_conversation, все работает. Единственное убрал изменения в menu_conversation т.к. посчитал, что добавление моей в функции в обработчик уже другая задача.

2022-07-07 19:19 UTC, veselij requested changes
серверная проверка PEP не прошла и есть конфликты

2022-07-07 19:19 UTC, veselij commented on src/jobs.py
> +async def user_monthly_stat_job(update: Update, context: ContextTypes.DEFAULT_TYPE):
видел твой вопрос в чате, к сожалению не было врмени днем ответить, надо сделать функцию обработчик для коллбэка в меню. написать ее в файле меню. см ниже и заменить для этого callback в меню
https://github.com/Studio-Yandex-Practicum/ask_nenaprasno_bot/blob/895f53fb2ad83d89a3574e9b6b4d0fb6f90910f1/src/conversation/menu.py#L62

2022-07-07 19:19 UTC, veselij commented on src/jobs.py
> +        await update.callback_query.edit_message_text(text="Ошибка авторизации")
а почему ошибка авторизации? там по интефейсу None не может вернуться. Может вернуться пустая статистика только

2022-07-07 19:19 UTC, veselij commented on src/jobs.py
> +        return states.UNAUTHORIZED_STATE
состояни точно менять не надо

2022-07-07 19:19 UTC, veselij commented on src/jobs.py
> +    alias_dict = dict(
а какой смысл тут так делать, не проше подставить просто из модели поля?

2022-07-08 08:26 UTC, veselij approved these changes
поправь пожалуйста там два момента в сообщении, остальное ок

2022-07-08 08:26 UTC, veselij commented on src/conversation/menu.py
> +        f"✅Среднее время ответа - {user_statistic.user_ticket_resolve_avg_time}\n\n"
добавь пожалуйста форматирование, чтобы был 1 знак после запятой. там поле float и мы точно не знаем, что нам фронт пришлет, может там будет 3.333333333.

2022-07-08 08:26 UTC, veselij commented on src/conversation/menu.py
> +        f"Открыть [Trello](https://trello.com)\n\n"
тут нам надо открыть доску трелло с фильтром по юзеру трелло. Юзера трелло мы сохраняли в бота при авторизации - можно его достать теперь и "собрать" url так чтобы доска с фильтром по юзеру открылась. вот пример "https://trello.com/b/8Nxdr2iD/?filter=member:xxx". место xxx надо подставить имя юзера в трелло. 8Nxdr2iD - идентификатор борды - сделай его в конфиге и забирай оттуда

2022-07-08 13:10 UTC, veselij approved these changes

2022-07-08 13:19 UTC, AntonZelinsky approved these changes

2022-07-08 13:19 UTC, AntonZelinsky commented on src/conversation/menu.py
> +            ),
Раньше строка была на 111 символов, но ты её на 3 строки разделил, почему? у нас же 120 символов стандарт.
У тебя точно настроены прекомиты?

2022-07-08 13:19 UTC, AntonZelinsky commented on src/core/config.py
> +TRELLO_BORD = get_string("TRELLO_BORD")  # доска в TRELLO
Лучше TRELLO_BORD_ID, так, более говорящее название

2022-07-08 13:19 UTC, AntonZelinsky commented on src/conversation/authorization.py
> +    context.user_data["user_name_in_trello"] = user_data.user_name_in_trello
Эта штука не будет работать при старте джоб, так как user_data доступна только при запросах пользователя, но ладно, мы всё равно тут немного переделаем

2022-07-08 13:29 UTC, veselij commented on src/conversation/authorization.py
> +    context.user_data["user_name_in_trello"] = user_data.user_name_in_trello
а тут запрос от пользователя как раз, он же статистику зарпашивает

2022-07-08 14:18 UTC, AndreyMurysev commented on src/conversation/menu.py
> +            ),
Теперь на 124, поменять наименование функции (button_statistic_month) или оставить?

2022-07-08 16:48 UTC, merged