Create functionality of delay button
Studio-Yandex-Practicum/ask_nenaprasno_bot pull request #6
Opened 2022-06-16 05:27 UTC by 1kovalevskiy

## Ticket - [Кнопка напомнить через час](https://www.notion.so/17722b26746942aaa7e4b081ca723f65)

- Add new folder `service` for bot components

- Add task creator that starts job with 1 hour delay

- Add message repeater that repeat delayed message with all inline key

2022-06-16 21:17 UTC, MatMerd approved these changes
Функции написаны, всё отлично

2022-06-16 22:37 UTC, AntonZelinsky reviewed
После нажатия на кнопку «напомни мне», у старого сообщения должна пропадать эта кнопка. 

Плюс, добавь, пожалуйста, пример добавления кнопок. Можешь сделать отдельную команду /statistics при вызове которой будет появляться моковый текст с кнопкой,  и при нажатии на неё, придёт напоминание через час.
Сейчас, просто сложно представить как этот код работает. 
Меня беспокоит, что должен быть простой способ добавить эту кнопку к любому сообщению.

2022-06-16 22:37 UTC, AntonZelinsky commented on src/service/delay.py
> +async def repeat_message(
Для функций которые выполняются джобами, нужно добавлять в конце приставку `_job`. Это поможет легче понимать код.
Раз уж я это написал, значит тебе выпадает честь начать писать документацию с хорошими практиками. Для примера, можешь [глянуть этот файл](https://github.com/Studio-Yandex-Practicum/Lubimovka_backend/blob/develop/docs/codestyle.md). Размести такой же файл с таким же расположением и добавь туда пару строк о том, что я описал выше и приведи пример. А как напишешь, сделай пост в общий канал и объяви об этой практике именования.

2022-06-17 11:43 UTC, 1kovalevskiy commented on src/service/delay.py
> +async def repeat_message(
Я до воскресенья уехал, так что не смогу написать раньше

2022-06-19 14:58 UTC, 1kovalevskiy commented
@AntonZelinsky @MatMerd @veselij

2022-06-19 15:04 UTC, veselij commented on src/service/delay.py
> +    await query.edit_message_text(text=data.text_markdown_v2_urled)
а почему не так await query.delete_message()?

2022-06-19 15:08 UTC, 1kovalevskiy commented on src/service/delay.py
> +    await query.edit_message_text(text=data.text_markdown_v2_urled)
Потому что попросили оставить сообщение и просто убрать кнопки

2022-06-19 15:31 UTC, 1kovalevskiy commented on src/service/delay.py
> +async def repeat_message(
Я сделал в notion codestyle страничку, которую удобно смотреть и просто дополнять

2022-06-19 15:44 UTC, AntonZelinsky approved these changes
Ещё одного бота не нужно создавать, интегрируй в созданный бот, как его использовать если он подключен непонятно куда. Файл пример удалить, когда я говорил пример, я подразумевал встроить в общее приложение, а не добавить что-то новое

2022-06-19 15:44 UTC, AntonZelinsky commented on src/service/delay.py
> +async def delay_message_for_1_hour(
```suggestion
async def delay_message_for_1_hour_сallback(
```

2022-06-19 15:44 UTC, AntonZelinsky commented on src/example/delay_function_example.py
> +        [InlineKeyboardButton("repeat after minute", callback_data="repeat")],
Саму кнопку перенеси в файл делэй, чтобы её нужно было только импортировать и использовать. И текст кнопки на русском языке должен быть.

2022-06-19 15:44 UTC, AntonZelinsky commented on src/service/delay.py
> +        reply_markup=data.reply_markup
Тут уже кнопка никаких не будет, поскольку ты выше удалил их. Тут нужно добавлять кнопку отложить ещё на час

2022-06-19 15:51 UTC, 1kovalevskiy commented on src/example/delay_function_example.py
> +        [InlineKeyboardButton("repeat after minute", callback_data="repeat")],
@AntonZelinsky 
Так саму кнопку сделал Андрей Капкаев
Она уже есть, PR заапрувлен, но не слито с develop, чтобы я мог конкретно ее использовать

2022-06-19 15:55 UTC, 1kovalevskiy commented on src/service/delay.py
> +        reply_markup=data.reply_markup
Андрей рассказывал, что у него две клавиатуры: из одной кнопки "отложить на час"; три кнопки 
Как я понял, после нажатия кнопки "отложить на час" - у оригинального сообщения удаляется клавиатура
А когда сообщение приходит через час, то у него опять должна быть клавиатура, чтобы можно было еще раз отложить на час
Так как клавиатуры две, то я просто беру клавиатуру из исходного сообщения и ее подцепляю к новому сообщению, ведь я не должен знать, какому сообщению какую кнопку добавлять

2022-06-19 16:09 UTC, 1kovalevskiy commented
> Ещё одного бота не нужно создавать, интегрируй в созданный бот, как его использовать если он подключен непонятно куда. Файл пример удалить, когда я говорил пример, я подразумевал встроить в общее приложение, а не добавить что-то новое

@AntonZelinsky 
У нас вчера созвон был, где решили, что надо сделать отдельную папку example и складывать туда примеры использования наших тасок, чтобы туда можно было обратиться к ним.
Кроме того, я не очень за то, чтобы делать этот пример сразу в приложении, потому что тогда он перекроет несколько тасок, которые уже почти выполнены, что тоже порицалось на вчерашнем созвоне.

2022-06-19 18:38 UTC, AntonZelinsky commented on src/service/delay.py
> +async def delay_message_for_1_hour(
Тут [создали файлик с хорошими практиками](https://www.notion.so/codestyle-e8de810f6a994c13ac97677dacf12f5a) в ноушен, добавь, пожалуйста, туда это правило и сделай пост в общий канал, чтобы всех уведомить об обновлении и об этом правиле

2022-06-19 18:40 UTC, AntonZelinsky commented on src/example/delay_function_example.py
> +        [InlineKeyboardButton("repeat after minute", callback_data="repeat")],
Ой, не знаю кто и зачем делал кнопку, но она должна создаваться в этом ПРе и находиться в сервисе откладывания, чтобы её можно было использовать не только в примерах, но и в основном проекте. Кнопка должна быть одна, и во всех остальных местах переиспользовать её.

2022-06-20 10:54 UTC, veselij requested changes
сделай пожалуйста кнопку у себя, из другого задания ее удалили

2022-06-20 10:54 UTC, veselij commented on src/example/delay_function_example.py
> +        [InlineKeyboardButton("repeat after minute", callback_data="repeat")],
ту кнопку удалили, @1kovalevskiy создай тут пожалуйста нужную кнопку

2022-06-20 11:37 UTC, 1kovalevskiy commented on src/example/delay_function_example.py
> +        [InlineKeyboardButton("repeat after minute", callback_data="repeat")],
@AntonZelinsky @veselij 
Кнопку сделал в том же файле, что и логику. Пока не представляю, куда ее можно в другое место перенести, чтобы структура была понятнее.

2022-06-20 11:38 UTC, 1kovalevskiy commented
> сделай пожалуйста кнопку у себя, из другого задания ее удалили

Все сделано

2022-06-20 16:41 UTC, veselij approved these changes

2022-06-21 00:40 UTC, merged