Copied changes from previous branch, function for authorization, message text in constants
Studio-Yandex-Practicum/ask_nenaprasno_bot pull request #65
Opened 2022-07-10 10:26 UTC by firepanda70

Добавил функцию для авторизации. Сообщения теперь отправляются отдельно в функции start и is_expert_callback, поэтому вынес текст в константы. Не знаю, где планируется в дальнейшем все сроки держать, так что оставил в этом же файле.

2022-07-10 18:03 UTC, veselij requested changes

2022-07-10 18:03 UTC, veselij commented on src/conversation/authorization.py
> +)
а есть ли смысл в этом сообщении. Достаточно BOT_GREETINGS_MESSAGE сообщения

2022-07-10 18:03 UTC, veselij commented on src/conversation/authorization.py
> +async def autorize_callback(update: Update, context: CallbackContext):
этот не callback же, а просто функция авторизаации. место update можно просто туда user_id передать.
логгер надо убрать, так как мы там все экспешены ловим только от телеграмма

2022-07-10 18:03 UTC, veselij commented on src/conversation/authorization.py
> +        )
можно убрать

2022-07-10 18:03 UTC, veselij commented on src/conversation/authorization.py
> +    await menu_button(context, COMMANDS)
а зачем убрал
 await update.callback_query.answer()

2022-07-10 18:03 UTC, veselij commented on src/conversation/authorization.py
> +        .format(user_name=user_data.user_name)
можно убрать

2022-07-11 01:50 UTC, firepanda70 commented on src/conversation/authorization.py
> +    await menu_button(context, COMMANDS)
Потому что там сообщение редактируется и инлайн кнопки исчезают, answer и не нужен получается

2022-07-11 09:47 UTC, veselij requested changes

2022-07-11 09:47 UTC, veselij commented on src/conversation/authorization.py
> +    return user_data
мы переименовали поля, поменяй их тут тоже пожалуйста

2022-07-11 09:47 UTC, veselij commented on src/conversation/authorization.py
> +        await update.callback_query.answer()
можно поднять над if user_data, и тогда убрать 147 строку. этот вызов у юзера прогресс бар просто останавливает

2022-07-11 10:28 UTC, veselij approved these changes

2022-07-11 11:23 UTC, AntonZelinsky approved these changes

2022-07-11 11:24 UTC, merged