Added 2 funcs in api_client. Used DRY in dataclasses
Studio-Yandex-Practicum/ask_nenaprasno_bot pull request #67
Opened 2022-07-12 13:22 UTC by Xewus

[Разбить в api service недельную статистику пользователя на 2 отдельных метода - активные и просроченные заявки](https://www.notion.so/api-service-2-62a04c5843ca42e5a5355f48eecdb7ad)

- Функция `get_user_week_stat()` удалена, вместо неё вписаны две функции. В `site_api_service.py`, как заглушки, в моках с возвращаемыми данными.
- Также обслуживающий dataclass разбит на два. Применён принцип DRY, сильно режут глаза повторы.
- Так как `pre-commit/pylint` не пропускал, жалуясь на повторы тел функций в базовом классе и наследниках, в `site_api_service.py` заменил в телах функций `pass` на `...`. Полагаю, это не так уж плохо, так как `Ellipsis` подразумевают, что вместо них обязательно нужно что-то написать.

2022-07-12 13:27 UTC, Xewus commented on src/service/api_client/base.py
> +    async def set_user_timezone(self, telegram_id: int, user_time_zone: str) -> HTTPStatus:
Это функция, очевидно, вытянулось в одну строку прекоммитом.

2022-07-12 13:29 UTC, Xewus commented on src/service/api_client/base.py
> +        pass
Это функция, очевидно, вытянулась в одну строку прекоммитом. Изменений в ней не делал.

2022-07-12 13:54 UTC, veselij requested changes
а почему файлы полносью переписаны, я не могу понять, что на что меняется. DRY в датаклассах привет к ошибкам, которые даже откоментировать сложно. логика к сожалению вся нарушилась. я не могу такой PR принять, проще заново сделать, чем теперь откоментировать, что вернуть и как поправить

2022-07-12 14:02 UTC, Xewus commented on src/core/config.py
> +
Нижележащая функция может вызвать ошибку `AttributeError: 'NoneType' object has no attribute 'split'`

2022-07-12 14:19 UTC, Xewus commented
> а почему файлы полносью переписаны, я не могу понять, что на что меняется. DRY в датаклассах привет к ошибкам, 

"Полностью зелёные файлы" уже обсуждались. Это прекоммит меняет концы строк.

Почему наследование в датаклассах приведёт к ошибкам?

2022-07-12 14:32 UTC, Xewus commented
Датаклассы снова расписаны по отдельности...

2022-07-12 16:28 UTC, veselij requested changes
так как у нас пока не устроканились поля группировать их преждевренно. при любом изменении все плывет.

2022-07-12 16:28 UTC, veselij commented on src/service/api_client/models.py
> +class UserWeekActiveStat:
давай назовем UserActiveConsultations

2022-07-12 16:28 UTC, veselij commented on src/service/api_client/models.py
> +    consultations_in_work: int
тут поля надо сделать как в файле 1в1 (добавить новых полей и переименовать) и соответвенно по всем датаклассам проверить и поменять если надо. consultation_active->active_consultation тоже надо менять
https://docs.google.com/spreadsheets/d/1ul1fCjuQeBiYlC7-n_x1929o3NXk4kUiu-ucxbHeahc/edit#gid=429815105
так же надо проверить и поменять во всех участках кода (если эти поля где то используются)

2022-07-12 16:28 UTC, veselij commented on src/service/api_client/models.py
> +class UserWeekExpiredStat:
UserExpiredConsultations

2022-07-12 16:28 UTC, veselij commented on src/service/api_client/models.py
> +    consultations_expired: int
тоже поля поменять по файлу

2022-07-12 16:28 UTC, veselij commented on src/service/api_client/base.py
> +    async def get_user_week_active_stat(self, telegram_id: int) -> UserWeekActiveStat:
get_user_active_consultations

2022-07-12 16:28 UTC, veselij commented on src/service/api_client/base.py
> +    async def get_user_week_expired_stat(self, telegram_id: int) -> UserWeekExpiredStat:
get_user_expired_consultations

2022-07-12 16:40 UTC, Xewus commented
Пока проверять не надо. Борюсь с зеленью.

2022-07-12 19:21 UTC, veselij requested changes
у нас в проекте есть места где используютя поля которые ты переименовал. в методе рассылки месячной стаистики точно есть

2022-07-12 19:21 UTC, veselij commented on src/core/config.py
> +    return env.get(setting) or default
не надо дефалт, так как мы там будем выбор из os.geten

2022-07-12 19:21 UTC, veselij commented on src/service/api_client/models.py
> +class MonthStat:
вот тут можно отнаследоваться от UserMonthStat

2022-07-12 19:30 UTC, Xewus commented on src/core/config.py
> +    return env.get(setting) or default
Тогда в Git Secrets нужно добавить `LOG_NAME` иначе падает workflow.

2022-07-13 16:29 UTC, Xewus commented
1. Добавлен `.gitattributes` с настройкой концов строк независимо от локальных настроек пользователя и уклонения его от использования прекоммита.
Побочный эффект - у линуксо- маководов будет предупреждение, что `LF` будет заменён на `CRLF`, если у пользователя не установлено иное.
2. Атрибуты дата-классов скопированы из предоставленного документа. В документе есть ещё `фича`  - "Установка часового пояса", датакласса под это нет (если он нужен).
 3. Добавлена строка в `README` (из официальной документации) для запуска бота через `poetry`, так как с написаной там - не работает. Тем не менее старую удалять не стал. Жалоб на неё не было - может тоже рабочий метод...
 4. Влияние изменённых файлов `api-client/` удалось обнаружить только в одном месте.
 5. Как итог - полностью зелёный только один файл.

2022-07-14 06:58 UTC, veselij approved these changes
в целом все ок, вот тут надо поправить еще и мерджим
https://github.com/Studio-Yandex-Practicum/ask_nenaprasno_bot/blob/6e514d96d39cef1cf66ba0b43d12e0cc101eeebc/src/jobs.py#L14
https://github.com/Studio-Yandex-Practicum/ask_nenaprasno_bot/blob/6e514d96d39cef1cf66ba0b43d12e0cc101eeebc/src/jobs.py#L44

2022-07-14 07:24 UTC, Xewus commented
> в целом все ок, вот тут надо поправить еще и мерджим
> 
> https://github.com/Studio-Yandex-Practicum/ask_nenaprasno_bot/blob/6e514d96d39cef1cf66ba0b43d12e0cc101eeebc/src/jobs.py#L14
> 
> 
> https://github.com/Studio-Yandex-Practicum/ask_nenaprasno_bot/blob/6e514d96d39cef1cf66ba0b43d12e0cc101eeebc/src/jobs.py#L44

Неясно, что поправить, в указанных функциях атрибуты верные...

2022-07-14 07:55 UTC, veselij commented
> > в целом все ок, вот тут надо поправить еще и мерджим
> > https://github.com/Studio-Yandex-Practicum/ask_nenaprasno_bot/blob/6e514d96d39cef1cf66ba0b43d12e0cc101eeebc/src/jobs.py#L14
> > 
> > https://github.com/Studio-Yandex-Practicum/ask_nenaprasno_bot/blob/6e514d96d39cef1cf66ba0b43d12e0cc101eeebc/src/jobs.py#L44
> 
> Неясно, что поправить, в указанных функциях атрибуты верные...

        "Закрыто заявок - *$**consultations_closed***\n"
        "В работе *$consultations_in_work* заявок  за неделю\n\n"
        "Истекает срок у *$consultations_expiring заявок*\n"
        "У *$consultations_expired* заявок срок истек\n\n"
        "Открыть [Trello](https://trello.com)\n\n"
        "Мы рады работать в одной команде :)\n"
        "*Так держать!*"
    )
    alias_dict = dict(
        consultations_closed="**consultations_closed**",
        consultations_in_work="consultations_in_work",
        consultations_expiring="consultations_expiring",
        consultations_expired="consultations_expired",

2022-07-14 08:00 UTC, Xewus commented
Ах, блин, они так похожи.

2022-07-14 08:06 UTC, merged