Hide import logger to decorator
Studio-Yandex-Practicum/ask_nenaprasno_bot pull request #72
Opened 2022-07-19 15:20 UTC by knightsdd

2022-07-20 04:08 UTC, zhss1983 commented on src/decorators/logger.py
> +                error_message = f"The error: '{str(err)}' after command: '{name}'"
Можно применить вот такую конструкцию: logger.error(("The error: %s after command: %s", str(err), name))
Но это не принципиально на мой взгляд.

Почитать об этом можно здесь: https://blog.pilosus.org/posts/2020/01/24/python-f-strings-in-logging/
И здесь: https://discuss.dizzycoding.com/pylint-message-logging-format-interpolation/
pylint error: https://vald-phoenix.github.io/pylint-errors/plerr/errors/logging/W1202.html

2022-07-20 04:52 UTC, zhss1983 commented on src/decorators/logger.py
> +                error_message = f"The error: '{str(err)}' after command: '{name}'"
Добавь в ревьюеры @MatMerd или @veselij. В зависимости от того к кому тебя распределили.

2022-07-20 06:53 UTC, knightsdd commented on src/decorators/logger.py
> +                error_message = f"The error: '{str(err)}' after command: '{name}'"
Сергей, спасибо! Полезная статья про оптимизацию логирования! Обязательно учту это

2022-07-20 07:34 UTC, veselij requested changes

2022-07-20 07:34 UTC, veselij commented on src/decorators/logger.py
> +                error_message = f"The error: '{str(err)}' after command: '{name}'"
давайте без f стринг сделаем, вот так
logger.exception("Exception after command: %s", name )

2022-07-20 08:12 UTC, zhss1983 approved these changes

2022-07-20 08:23 UTC, veselij requested changes
если мы логируем через эксепшен, то сам эксепшен будет автоматом проброшен

2022-07-20 08:23 UTC, veselij commented on src/decorators/logger.py
> +                logger.error("The error: %s after command: %s", str(err), name)
```suggestion
                logger.exception("The error after command: %s", name)
```

2022-07-20 08:24 UTC, zhss1983 approved these changes

2022-07-20 08:28 UTC, zhss1983 commented on src/decorators/logger.py
> +                logger.error("The error: %s after command: %s", str(err), name)
Согласен, так лучше гораздо.
```
2022-07-20 13:18:42,137 ERROR core.logger:	The error: exceptions must derive from BaseException after command: conversation.authorization.start
```
vs
```
2022-07-20 13:25:32,524 ERROR core.logger:	The error after command: conversation.authorization.start
Traceback (most recent call last):
  File "C:\Dev\ask_nenaprasno_bot\src\decorators\logger.py", line 11, in wrapper
    return await func(*args, **kwargs)
  File "C:\Dev\ask_nenaprasno_bot\src\conversation\authorization.py", line 31, in start
    raise "test exception"
TypeError: exceptions must derive from BaseException
```

2022-07-20 08:34 UTC, veselij commented
линтер не прошел codestyle - надо поправить и будет ок

2022-07-21 21:47 UTC, Xewus commented on src/decorators/logger.py
> +                error_message = f"The error: '{str(err)}' after command: '{name}'"
Небольшое уточнение. При текущих настройках пре-коммит ( `pylint` ) не пропустит  f-строку в логгировании.
А раз это строка здесь, то можно сделать определённые выводы...
П.С. Я и сам писал так :)

2022-07-23 03:55 UTC, veselij approved these changes

2022-07-23 03:58 UTC, merged