Кнопка запроса просроченных заявок
Studio-Yandex-Practicum/ask_nenaprasno_bot pull request #73
Opened 2022-07-19 15:28 UTC by Andromaril

Сделана кнопка запроса просроченных заявок по аналогии с копкой запроса месячной статистики.

2022-07-20 04:14 UTC, zhss1983 commented on src/conversation/menu.py
> +@async_error_logger(name="conversation.requests.button_overdue_requests_callback", logger=logger)
В PR уже висит задача в которой такой стиль логирования изменён. аргумент logger=logger более не требуется для декоратора логирования. Если его примут раньше, придётся менять. Имей ввиду.

2022-07-20 04:15 UTC, zhss1983 commented on src/conversation/menu.py
> +@async_error_logger(name="conversation.requests.button_overdue_requests_callback", logger=logger)
https://github.com/Studio-Yandex-Practicum/ask_nenaprasno_bot/pull/72

2022-07-20 04:41 UTC, zhss1983 commented on src/conversation/menu.py
> +async def button_overdue_requests_callback(update: Update, context: ContextTypes.DEFAULT_TYPE) -> None:
Мария, название не соответствует методу. Название - колбэк запрос просроченных, а возвращается статистика и для просроченных и для текущих. Я могу ошибаться, но метод не в полной мере соответствует задаче. @MatMerd  или @veselij, поправьте меня если я не прав.

2022-07-20 07:43 UTC, Andromaril commented on src/conversation/menu.py
> +@async_error_logger(name="conversation.requests.button_overdue_requests_callback", logger=logger)
Ага, ну это уже по ходу принятия PR поправлю

2022-07-20 07:45 UTC, Andromaril commented on src/conversation/menu.py
> +async def button_overdue_requests_callback(update: Update, context: ContextTypes.DEFAULT_TYPE) -> None:
Верное замечание, в принципе кнопка "в работе" отвечает за инфу о текущих задачах и истекающих, так что можно и убрать тут статистику о истекающих, что бы не дублировать

2022-07-20 07:55 UTC, veselij requested changes

2022-07-20 07:55 UTC, veselij commented on src/conversation/menu.py
> +async def button_overdue_requests_callback(update: Update, context: ContextTypes.DEFAULT_TYPE) -> None:
кнопка и функция у нас просроченных заявок. Но текст сообщения действительно в конце содержит преписку кол-во активных и истекащих заявок, поэтому мы далем второй вызов. думаю название подходит

2022-07-20 07:55 UTC, veselij commented on src/conversation/menu.py
> +        f"Открыть [Trello](https://trello.com/{TRELLO_BORD_ID}/?filter=member:{username_trello})\n\n"
вот такой текст надо:
```
"Время и стекло 😎
 У вас количетсво заявок просрочено
Верим и ждем.

Посмотреть заявки на сайте (cсылка на каждую просроченную заявку в Просто спросить)

----
В работе количество  заявок
Истекает срок у количество заявок

Открыть Trello (ссылка на доску в trello с отфильтрованными просроченными заявками по эксперту)
"
```

2022-07-20 07:55 UTC, veselij commented on src/conversation/menu.py
> +    username_trello = context.user_data["username_trello"]
он приходит от API, надо отуда брать. из контекста мы его уберем

2022-07-20 08:14 UTC, Andromaril commented on src/conversation/menu.py
> +    username_trello = context.user_data["username_trello"]
У нас же сменился формат ответа сервера. Поменять UserExpiredConsultations в mock_api_service.py?

2022-07-20 08:16 UTC, Andromaril commented on src/conversation/menu.py
> +        f"Открыть [Trello](https://trello.com/{TRELLO_BORD_ID}/?filter=member:{username_trello})\n\n"
Поняла, поменяю

2022-07-22 03:55 UTC, zhss1983 commented on src/conversation/menu.py
> +    link_neneprasno = [f"{URL_SITE}client/consultation/{i}" for i in list_of_ids]
Лично мне без разницы, но на курсе ревьеры постоянно придирались к однобуквенным переменным. Они не информативны.

2022-07-22 03:56 UTC, zhss1983 commented on src/conversation/menu.py
>          f"Время и стекло 😎\n"
Что-то мне подсказывает что человек просто опечатался, не вижу смысла перетаскивать опечатку в код.

2022-07-23 04:26 UTC, veselij requested changes

2022-07-23 04:26 UTC, veselij commented on src/conversation/menu.py
> +@async_error_logger(name="conversation.requests.button_overdue_requests_callback", logger=logger)
да, надо поправить теперь

2022-07-23 04:26 UTC, veselij commented on src/conversation/menu.py
> +    link_neneprasno = [f"{URL_SITE}client/consultation/{i}" for i in list_of_ids]
можно в один цикл все сделать, сразу собрать ссылки в тект. посмотри как в кнопке активных заявок сделали

2022-07-23 04:26 UTC, veselij commented on src/conversation/menu.py
> +    user_statistics_expiring_consultations = await service.get_user_active_consultations(telegram_id=telegram_id)
user_statistics_ можно опустить, а то очень раздуто получается

2022-07-23 04:26 UTC, veselij commented on src/conversation/menu.py
>          f"Время и стекло 😎\n"
да, надо поправить

2022-07-23 04:26 UTC, veselij commented on src/conversation/menu.py
> +        f"{user_statistics_expired_consultations.username_trello})\n\n"
надо зарегистрироваться в трелло и посмотреть как собрать фильтр на именно просроченные заявки. т.е. фильтр на 2 условия - username и просроченные карточки именно

2022-07-23 04:26 UTC, veselij commented on src/service/api_client/models.py
> +    expired_consultations_data: list[UserExpiredConsultationsIds]
давай тут просто сделаем list[dict[str,str]]

2022-07-26 08:38 UTC, veselij approved these changes

2022-07-26 08:38 UTC, merged