Добавил новые комментарии в config.py
Studio-Yandex-Practicum/ask_nenaprasno_bot pull request #75
Opened 2022-07-20 10:58 UTC by lukart80

Дописал недостающие комментарии в конфигах

2022-07-21 21:59 UTC, Xewus commented on src/core/config.py
>  HOST = get_string("HOST")  # host для доступа к uvicorn серверу, по умолчанию localhost или 127.0.0.1
По умолчание здесь будет `None` . Вполне, возможно, что где-то дальше установлено это, но не здесь.
По всем остальным - может удобнее расставить комментарии над переменными, а не вытягивать в одну длинную строку, начинающуюся на разных позициях?

2022-07-23 04:08 UTC, veselij requested changes
давай сгруппируем немного, нет смысла в такой детализации, из названий переменных суть понятна в рамках общего скопа. сделать надо примерно так

# параметры локального веб сервера
HOST
PORT
....

# параметры еженедельных рассылок бота
WEEKLY....
...

# параметры трелло
TRELLO_BOARD_ID
....

...

2022-07-26 08:45 UTC, veselij requested changes

2022-07-26 08:45 UTC, veselij commented on src/core/config.py
> +# Параметры локального сервера
```suggestion
# Параметры локального сервера принимающего обновления от телеграм
```

2022-07-26 08:45 UTC, veselij commented on src/core/config.py
>  MONTHLY_RECEIPT_REMINDER_TIME = get_datetime(
тут лучше разделить - рассылки статистики и рассылки чеков

2022-07-26 08:45 UTC, veselij commented on src/core/config.py
> +# Параметры для апи
тут не соответствует описанию, внизу смешено сразу 3 вида настроек:
- файл куда бот сохраняет свои данные и его токена
- настройка отладки 
- настройка урла сайта для запросов через API

надо разделить все и добавить соответсвующие коменты

2022-07-27 03:44 UTC, veselij approved these changes

2022-07-27 05:26 UTC, merged