Add functions for edit and reply of message to bot
Studio-Yandex-Practicum/ask_nenaprasno_bot pull request #77
Opened 2022-07-20 22:18 UTC by sdvkam

2022-07-21 22:06 UTC, AntonZelinsky requested changes

2022-07-21 22:06 UTC, AntonZelinsky commented on src/core/send_message.py
> +            settings["parse_mode"] = ParseMode.HTML
А зачем это всё? почему решили ещё html поддерживать?

2022-07-21 22:06 UTC, AntonZelinsky commented on src/core/send_message.py
> +            settings["parse_mode"] = ParseMode.HTML
Странный код! Если в этой переменной не макрдаун, то там будет html, так как дургие значения не поддерживаются телеграмом. 
И зачем записывать в сетинги опять?
Предлагаю удалить вообще поддержку html, оставить только маркдаун. То есть, захардкодить в функции edit_message_text. `parse_mode=ParseMode.MARKDOWN`

2022-07-21 22:06 UTC, AntonZelinsky commented on src/core/send_message.py
> +    parse_mode: str = ParseMode.HTML,
Почему??? И если тут поменяли, тогда нужно все сообщения переделывать, так как у нас много де использовался маркдаун

2022-07-21 22:41 UTC, sdvkam commented on src/core/send_message.py
> +    parse_mode: str = ParseMode.HTML,
При проверке как работают функции, попытка переслать parseMode = Markdown вызывало ошибку

2022-07-21 22:42 UTC, sdvkam commented on src/core/send_message.py
> +            settings["parse_mode"] = ParseMode.HTML
У меня в функции получилось 6 аргументов и начал ругаться pylint

2022-07-22 02:51 UTC, sdvkam commented on src/core/send_message.py
> +    parse_mode: str = ParseMode.HTML,
Я оказывается пытался переслать текст=test_new.
Markdown не воспринимает '_', надо было экранировать символ '\\_'

2022-07-22 23:58 UTC, AntonZelinsky commented on src/core/send_message.py
> +    parse_mode: str = ParseMode.HTML,
Из параметров функции забыл удалить. Удали и во всех других функциях этого класса, чтобы было однообразно.

2022-07-23 00:07 UTC, AntonZelinsky approved these changes

2022-07-23 00:07 UTC, AntonZelinsky commented on src/core/send_message.py
> +            message_id=message_id,
Выглядит так, что для редактирования эти параметры передавать не нужно. Смотри пример https://github.com/ProCharity/ProCharity_bot/blob/develop/bot/handlers/feedback_handler.py#L40

2022-07-23 00:07 UTC, AntonZelinsky commented on src/core/send_message.py
> +        logging.exception(("The error editing the message to the chat: %s", chat_id), error)
Почитай статью и в других местах тоже поправь https://realpython.com/python-f-strings/

2022-07-23 04:40 UTC, veselij requested changes

2022-07-23 04:40 UTC, veselij commented on src/core/send_message.py
> +        logging.exception(("The error editing the message to the chat: %s", chat_id), error)
Антон, для логов тут все правильно сделано, f string не подходит, так как он в определенных случаях медленнее для логов, чем через нативное форматирование. 
https://blog.pilosus.org/posts/2020/01/24/python-f-strings-in-logging/

2022-07-23 04:40 UTC, veselij commented on src/core/send_message.py
> +        logging.exception(("The error editing the message to the chat: %s", chat_id), error)
только %s на %d надо поменять

2022-07-23 04:40 UTC, veselij commented on src/core/send_message.py
> +async def reply_message(
аналогичные комментарии как выше

2022-07-23 07:36 UTC, sdvkam commented on src/core/send_message.py
> +            message_id=message_id,
Мне не понятно, как будет использоваться функция редактирования:
1. Возможность редактирования любого сообщения в чате (тогда данные: chat_id, message_id - нужны)
2. Реакция на определенное событие

2022-07-23 18:37 UTC, AntonZelinsky commented on src/core/send_message.py
> +        logging.exception(("The error editing the message to the chat: %s", chat_id), error)
Интересно, спасибо за статью

2022-07-26 08:54 UTC, veselij requested changes

2022-07-26 08:54 UTC, veselij commented on src/core/send_message.py
> +        await context.bot.send_message(
тут должно быть await update.message.reply_text

2022-07-26 08:54 UTC, veselij commented on src/core/send_message.py
> +            reply_to_message_id=reply_to_message_id,
это не надо

2022-07-26 08:54 UTC, veselij commented on src/core/send_message.py
> +    reply_to_message_id: int,
не надо

2022-07-26 08:54 UTC, veselij commented on src/core/send_message.py
> +        logging.exception(("The error sending the message to the chat: %d", chat_id), error)
сюда error не надо передавать, стэк вызов с текстом ошибки и так залогируется

2022-07-27 03:55 UTC, veselij approved these changes

2022-07-27 03:55 UTC, merged