Feature/create site api service
Studio-Yandex-Practicum/ask_nenaprasno_bot pull request #78
Opened 2022-07-25 20:35 UTC by t0nyhat

Реализованы API запросы к сайту:
- Активных заявок
- Просроченных заявок
- Месячной статистики по запросу
- Получении данных о пользователе
- Установке таймзоны пользователя
Для теста развернул mock server в [postman](https://a3d4bd8a-d0e7-4021-867e-e6f4a6f15cb4.mock.pstmn.io) и переводил флаг IS_FAKE_API в False для вызова функций для api сайта.

2022-07-26 09:07 UTC, veselij requested changes

2022-07-26 09:07 UTC, veselij commented on src/service/api_client/models.py
> +    average_user_answer_time: str
а почему тип поменялся?

2022-07-26 09:07 UTC, veselij commented on src/service/api_client/site_api_service.py
> +            return response.json()
тут надо await

2022-07-26 09:07 UTC, veselij commented on src/service/api_client/site_api_service.py
> +                return None
если вернешь None то функции выше упадут при формировании датаклассов.
а точно везде 200 мы ждем, какие еще кода есть? если только 200ка, то нет смысла ее проверять. если есть еще только non autotized, тогда надо залакировать это выкинуть исключение.
Дальше в функциях реагировать на этот эксепшен. Например возвращать датакласс сформированный с дефолтными параметрами, 
так же надо проверить, что json не упадет с ошибкой jsondecodeerror

2022-07-26 11:06 UTC, t0nyhat commented on src/service/api_client/models.py
> +    average_user_answer_time: str
В [доке](https://api.ask.nenaprasno.ru/docs/) нет такого эндпоинта, а в [посте](https://practicum-students.slack.com/archives/C03JFJG1N9Z/p1658145656339419) есть описание со стринговыми типами
<img width="911" alt="Screenshot 2022-07-26 at 14 02 19" src="https://user-images.githubusercontent.com/54199578/180991799-cf90d0d4-4ad3-44d9-8e0a-f8be01e909ca.png">

2022-07-26 11:46 UTC, t0nyhat commented on src/service/api_client/site_api_service.py
> +            return response.json()
Вот тут честно пока не понял где await нужен `response = await response.json()`? Так вроде не работает , пишет `TypeError: object dict can't be used in 'await' expression`.

2022-07-26 12:04 UTC, t0nyhat commented on src/service/api_client/site_api_service.py
> +                return None
Понял, над этим поработаю

2022-07-26 21:05 UTC, t0nyhat commented on src/service/api_client/site_api_service.py
> +                return None
В последнем коммите:

1.  Добавил обработчики ошибок на все http коды кроме 20X
2. JSONDecodeError при приведении к json
3. TypeError если из json не получается создать dataclass
4. Добавил логеры
5. Сейчас возвращаю при ошибках None, хотел бы уточнить что нужно возвращать @veselij ?

2022-07-27 03:57 UTC, veselij commented on src/service/api_client/models.py
> +    average_user_answer_time: str
надо оставить int и float, так как там явно должны быть числа

2022-07-27 04:12 UTC, veselij requested changes

2022-07-27 04:12 UTC, veselij commented on src/service/api_client/site_api_service.py
> +                return response.json()
```suggestion
                return await response.json()
```

2022-07-27 04:12 UTC, veselij commented on src/service/api_client/site_api_service.py
> +                response.raise_for_status()
```suggestion
                await response.raise_for_status()
```

2022-07-27 04:12 UTC, veselij commented on src/service/api_client/site_api_service.py
> +            return None
надо поправить типы возвращаемых значений функциями, так как теперь это или объект или ничего. поправить надо тут, в базовом классе и в fake api

2022-07-27 21:06 UTC, t0nyhat commented
1. Обновил аннотации типов в мок апи, сайт апи и базовом классе
2. Вернул типы данных в модели UserMonthStat

2022-07-27 21:12 UTC, t0nyhat commented
1. Обновил аннотации типов в мок апи, сайт апи и базовом классе
2. Вернул  обратно типы данных в модели UserMonthStat
3. response.json() оставил без await

2022-08-03 08:50 UTC, veselij requested changes

2022-08-03 08:50 UTC, veselij commented on src/service/api_client/site_api_service.py
> +            return UserActiveConsultations(**active_consultations) if active_consultations else None
а зачем тебе тут if, если будет пустой ответ от API, то распаковка None вызовет TypeError, который ты уже обрабатываешь и так ниже. просто этот if сильно затрудняет понимание

2022-08-03 21:51 UTC, AntonZelinsky approved these changes

2022-08-04 05:08 UTC, t0nyhat commented
Убрал ненужные условия, но из-за изменения в файле ./src/core/config.py , не проходит тест flake8 в github actions

2022-08-04 06:15 UTC, veselij commented
> Убрал ненужные условия, но из-за изменения в файле ./src/core/config.py , не проходит тест flake8 в github actions

поправь файл config.py пожалуйста, там надо одну пустую строку удалить

2022-08-04 06:54 UTC, t0nyhat commented
Поправил config.py.

2022-08-04 07:51 UTC, veselij approved these changes

2022-08-04 07:51 UTC, merged