fix_dialogs
Studio-Yandex-Practicum/ask_nenaprasno_bot pull request #85
Opened 2022-08-01 21:51 UTC by ainokyn

Поправлены диалоги, за основу взят макет с Figma, но что-то приходилось смотреть из файла, который скинул Матвей (между ними есть небольшие расхождения).
После получения соответствующих задач, по этой теме будет еще сделано:
1) Будет добавлено ветвление диалога при запросе экспертом месячной статистики.
2) Для кнопки "в работе" должны быть ссылки на задачи в работе, а не на истекающие по срокам задачи.

2022-08-04 04:20 UTC, MatMerd commented
Саша, поправь конфликты

2022-08-04 04:21 UTC, MatMerd commented
И влей свой остальной код, который ты делала по диалогам

2022-08-05 08:21 UTC, veselij requested changes

2022-08-05 08:21 UTC, veselij commented on src/conversation/authorization.py
> +    "\"Просто спросить\". Я буду сообщать вам о новых заявках, "
```suggestion
    "\"Просто спросить\". \nЯ буду сообщать вам о новых заявках, "
```

2022-08-05 08:21 UTC, veselij commented on src/conversation/menu.py
> +                text="Статистика за месяц", callback_data=callback_data.CALLBACK_STATISTIC_MONTH_COMMAND
кнопка перестала работать

elegram.error.BadRequest: Can't parse entities: character ')' is reserved and must be escaped with the preceding '\'

2022-08-05 08:21 UTC, veselij commented on src/conversation/menu.py
> +        [InlineKeyboardButton(text="В работе", callback_data=callback_data.CALLBACK_ACTUAL_REQUESTS_COMMAND)],
в сообщение нет ссылки на трело доску отфильтрованную по врачу

2022-08-05 08:21 UTC, veselij commented on src/jobs.py
> +        "Посмотрите, как он прошел в \"Просто спросить\" 🔥\n\n"
надо проверить что это сообщение будет отправляться, а не будет ошибки как с кнопкой

2022-08-05 08:21 UTC, veselij commented on src/conversation/timezone.py
> +    buttons_after_timezone = [
после расшаривания геолокации кнопки не пропадают

2022-08-05 23:11 UTC, ainokyn commented on src/conversation/menu.py
> +        [InlineKeyboardButton(text="В работе", callback_data=callback_data.CALLBACK_ACTUAL_REQUESTS_COMMAND)],
В макете Figma для кнопки "в работе" прописана фраза: кнопка, нажав на которую пользователь сможет получить список ссылок на заявки, находящиеся в работе. Про Trello ничего не указано, поэтому я и не указывала ссылку на доску Trello. В документе с  диалогами нет диалогов для данной кнопки, поэтому ориентировалась на Figma. Если это необходимо, то я добавлю.

2022-08-06 01:48 UTC, ainokyn commented on src/conversation/timezone.py
> +    buttons_after_timezone = [
Возник вопрос: как я поняла, удаление кнопок происходит через передачу специальной удаляющей клавиатуры ReplyKeyboardRemove() в сообщении, но в этом сообщении должен быть обязательно какой-то текст, а новый текст-это новый диалог, которого нет в макете. В связи с этим вопрос такой: есть ли другой способ удаления клавиатуры или только такой и лишний диалог неизбежен?

2022-08-06 11:59 UTC, veselij commented on src/conversation/menu.py
> +        [InlineKeyboardButton(text="В работе", callback_data=callback_data.CALLBACK_ACTUAL_REQUESTS_COMMAND)],
там точно должна быть ссылка на трелло с фильтром по пользователю. добавь плиз

2022-08-06 12:02 UTC, veselij commented on src/conversation/timezone.py
> +    buttons_after_timezone = [
после того как настроили тайм-зону должно срузу отправиться меню с собщением "а еще с помощбю меня вы можете узнарь о.." - там можно удалить клавиатуру

2022-08-06 13:52 UTC, veselij commented on src/conversation/timezone.py
> +    buttons_after_timezone = [
я посмтрел, похоже нет варианта, кроме как отправить после установки таймзоны сообщение типа ТЗ установлена успешно с ReplyKeyboardRemove, а потов уже отправить меню с кнопками, по другому не получается

2022-08-07 12:19 UTC, veselij requested changes

2022-08-07 12:19 UTC, veselij commented on src/conversation/authorization.py
> +    " чтобы обсудить его на встрече."
Traceback (most recent call last):
  File "/home/ealmina/code/ask_nenaprasno_bot/src/core/send_message.py", line 82, in reply_message
    await message.reply_markdown_v2(text=text_to_markdown(text), reply_markup=reply_markup)
  File "/home/ealmina/code/ask_nenaprasno_bot/.venv/lib/python3.10/site-packages/telegram/_message.py", line 920, in reply_markdown_v2
    return await self.get_bot().send_message(
  File "/home/ealmina/code/ask_nenaprasno_bot/.venv/lib/python3.10/site-packages/telegram/_bot.py", line 236, in decorator
    result = await func(*args, **kwargs)
  File "/home/ealmina/code/ask_nenaprasno_bot/.venv/lib/python3.10/site-packages/telegram/_bot.py", line 649, in send_message
    return await self._send_message(  # type: ignore[return-value]
  File "/home/ealmina/code/ask_nenaprasno_bot/.venv/lib/python3.10/site-packages/telegram/ext/_extbot.py", line 254, in _send_message
    result = await super()._send_message(
  File "/home/ealmina/code/ask_nenaprasno_bot/.venv/lib/python3.10/site-packages/telegram/_bot.py", line 352, in _send_message
    result = await self._post(
  File "/home/ealmina/code/ask_nenaprasno_bot/.venv/lib/python3.10/site-packages/telegram/_bot.py", line 315, in _post
    return await request.post(
  File "/home/ealmina/code/ask_nenaprasno_bot/.venv/lib/python3.10/site-packages/telegram/request/_baserequest.py", line 162, in post
    result = await self._request_wrapper(
  File "/home/ealmina/code/ask_nenaprasno_bot/.venv/lib/python3.10/site-packages/telegram/request/_baserequest.py", line 325, in _request_wrapper
    raise BadRequest(message)
telegram.error.BadRequest: Can't parse entities: character '(' is reserved and must be escaped with the preceding '\'

2022-08-08 05:27 UTC, MatMerd approved these changes

2022-08-08 12:31 UTC, veselij approved these changes

2022-08-08 12:32 UTC, merged