Fix/change endpoint trello to site
Studio-Yandex-Practicum/ask_nenaprasno_bot pull request #87
Opened 2022-08-02 21:20 UTC by aybor

2022-08-03 10:09 UTC, veselij requested changes
привет,
1. Давай сделаем проверку токена, через midleware старлета. Но тут важно, учесть, что у нас 2 хоста от которых мы можем принимать запросы - телеграм и сайт ненапрастно. Поэтому надо сделать мидлваре которое проверяет все запросы на наличие или authorization или X-Telegram-Bot-Api-Secret-Token в хидере. и их значения. так же для того, чтобы телеграм нам прислыла этот токен нам надо его задать в методе set_webhook через параметр secret_token  (а его загрузить через env)
https://core.telegram.org/bots/api#setwebhook
https://www.starlette.io/middleware/

2. первый пункт нужен, чтобы не дублировать код проверки в каждом end point, так как нам надо сделать 4 отдельных end point (как напсиано в файле), а не через парметры с 1 энд поинт как ты сделал.
https://docs.google.com/spreadsheets/d/1ul1fCjuQeBiYlC7-n_x1929o3NXk4kUiu-ucxbHeahc/edit?usp=sharing
@AntonZelinsky

2022-08-03 22:11 UTC, aybor commented
Добавил проверку токена через middleware старлета.
Добавил проверку хостов  через middleware старлета.
Задал токен в методе set_webhook.
Разделил один эндпоинт на четыре в соответствии с тем, что указано в таблице.
Сделал четыре отдельные функции к каждому эндпоинту.

2022-08-04 11:00 UTC, veselij requested changes

2022-08-04 11:00 UTC, veselij commented on src/bot.py
> +        secret_token=os.getenv('SECRET_TOKEN')
все переменные окружения надо прочитать в файле config и потом их импортировать. аналогично в мидлваре, иначе ты на каждый реквест читаешь из оружения, место того, чтобы держать в памяти

2022-08-04 11:00 UTC, veselij commented on src/check_headers_backend.py
> +    ) -> tuple[AuthCredentials, SimpleUser] | AuthCredentials | None:
не правильная анатация возврщаемого результат. посмотри базовый класс

2022-08-04 11:00 UTC, veselij commented on src/check_headers_backend.py
> +            token = conn.headers['authorization']
Authorization vs authorization

2022-08-04 11:00 UTC, veselij commented on src/check_headers_backend.py
> +                logger.warning(f'Unauthorized access attempt with token {token}')
можно вынести в отельный метод и вызывать его с параметрами

2022-08-04 11:00 UTC, veselij commented on src/check_headers_backend.py
> +class CheckHeadersBackend(AuthenticationBackend):
может назвать TokenAuthBackend

2022-08-04 11:00 UTC, veselij commented on src/run_webhook_api.py
> +load_dotenv()
а зачем?

2022-08-04 11:00 UTC, veselij commented on src/run_webhook_api.py
> +async def try_to_deserialize(request: Request, deserializer):
```suggestion
async def deserialize(request: Request, deserializer):
```
нет аннтотации возвращаемого значаения

2022-08-04 11:00 UTC, veselij commented on src/run_webhook_api.py
> +    deserializer = AssignDeserializerModel
можно сразу класс передать, без выделения в локальную переменную

2022-08-04 11:00 UTC, veselij commented on src/run_webhook_api.py
> +    if request.user.is_authenticated:
может через декоратор сделать и убать эти if

from starlette.authentication import requires


@requires('authenticated')
async def dashboard(request):
    ...

2022-08-04 11:00 UTC, veselij commented on src/run_webhook_api.py
> +    Middleware(TrustedHostMiddleware, allowed_hosts=[os.getenv('SITE_API_URL'), os.getenv('WEBHOOK_URL')]),
не надо хосты проверять, токена достаточно. зачем лишняя проверка. к тому же WEBHOOK_URL это не тот url с которого нам телеграмм будет присылват обновления

2022-08-04 11:00 UTC, veselij commented on src/check_headers_backend.py
> +import os
файл лучше назвать middleware.py

2022-08-04 11:00 UTC, veselij commented on src/service/bot_api_data_deserializers.py
> +from dataclasses import dataclass, field
модели надо перенести в файл models.py

2022-08-04 11:00 UTC, veselij commented on src/service/bot_api_data_deserializers.py
> +class CloseDeserializerModel:
```suggestion
class ClosedConsultationModel:
```

2022-08-04 11:00 UTC, veselij commented on src/service/bot_api_data_deserializers.py
> +class MessageFeedbackDeserializerModel:
```suggestion
class ConsultationModel:
```

2022-08-04 11:00 UTC, veselij commented on src/service/bot_api_data_deserializers.py
> +class AssignDeserializerModel:
```suggestion
class AssignedConsultationModel(ConsultationModel):
```

2022-08-04 11:01 UTC, veselij reviewed
надо в .env.sample добавить пример токенов

2022-08-04 18:46 UTC, aybor commented on src/bot.py
> +        secret_token=os.getenv('SECRET_TOKEN')
Добавил нужные переменные окружения, и импортировал из конфига.

2022-08-04 18:47 UTC, aybor commented on src/check_headers_backend.py
> +            token = conn.headers['authorization']
Исправил

2022-08-04 19:16 UTC, aybor commented on src/check_headers_backend.py
> +    ) -> tuple[AuthCredentials, SimpleUser] | AuthCredentials | None:
поправил

2022-08-04 19:17 UTC, aybor commented on src/check_headers_backend.py
> +class CheckHeadersBackend(AuthenticationBackend):
назвал

2022-08-04 19:18 UTC, aybor commented on src/run_webhook_api.py
> +load_dotenv()
убрал

2022-08-04 19:19 UTC, aybor commented on src/run_webhook_api.py
> +async def try_to_deserialize(request: Request, deserializer):
поправил

2022-08-04 19:20 UTC, aybor commented on src/run_webhook_api.py
> +    deserializer = AssignDeserializerModel
поправил

2022-08-04 19:26 UTC, aybor commented on src/run_webhook_api.py
> +    Middleware(TrustedHostMiddleware, allowed_hosts=[os.getenv('SITE_API_URL'), os.getenv('WEBHOOK_URL')]),
Убрал проверку. Но, я считаю, что она не помешала бы на случай, если токен будет скомпрометирован.

2022-08-04 19:28 UTC, aybor commented on src/check_headers_backend.py
> +import os
сделал

2022-08-04 19:31 UTC, aybor commented on src/service/bot_api_data_deserializers.py
> +from dataclasses import dataclass, field
сделал

2022-08-04 19:32 UTC, aybor commented on src/service/bot_api_data_deserializers.py
> +class CloseDeserializerModel:
сделал

2022-08-04 19:32 UTC, aybor commented on src/service/bot_api_data_deserializers.py
> +class MessageFeedbackDeserializerModel:
сделал

2022-08-04 19:33 UTC, aybor commented on src/service/bot_api_data_deserializers.py
> +class AssignDeserializerModel:
сделал

2022-08-04 19:35 UTC, aybor commented on src/run_webhook_api.py
> +    deserializer = AssignDeserializerModel
сделал

2022-08-04 19:38 UTC, aybor commented on src/run_webhook_api.py
> +    if request.user.is_authenticated:
сделал

2022-08-04 19:48 UTC, aybor commented on src/check_headers_backend.py
> +                logger.warning(f'Unauthorized access attempt with token {token}')
Предлагаю альтернативное решение

2022-08-05 08:08 UTC, veselij approved these changes

2022-08-05 08:08 UTC, veselij commented on src/middleware.py
> +                actual_token = self.CREDENTIALS[header]['token']
```suggestion
                actual_token = header['token']
```

2022-08-05 08:08 UTC, veselij commented on src/middleware.py
> +                user = self.CREDENTIALS[header]['username']
```suggestion
                user = header['username']
```

2022-08-05 10:28 UTC, aybor commented on src/middleware.py
> +                actual_token = self.CREDENTIALS[header]['token']
Но так не будет работать. header - это строка, значение одного из ключей словаря CREDENTIALS.

2022-08-05 10:28 UTC, aybor commented on src/middleware.py
> +                user = self.CREDENTIALS[header]['username']
Аналогично предыдущему комментарию.

2022-08-05 10:28 UTC, merged