Уведомление о новом сообщении
Studio-Yandex-Practicum/ask_nenaprasno_bot pull request #90
Opened 2022-08-07 21:23 UTC by AkuLinker

Добавлена функция send_new_message_notification в файл src/core/sendmessage.py  
Добавлены различные изменения в файл src/run_webhook_api.py в соответсвии с требованиями pylint.

2022-08-08 12:46 UTC, veselij requested changes

2022-08-08 12:46 UTC, veselij commented on src/run_webhook_api.py
> +    await send_new_message_notification(bot, request_data)
надо слелать проверку, request_data не пустая ли, если пустая то отправлять не надо.
а ты пробовал у бота взять контекст и его передать в функцию send_message, чтобы не делать новую функцию отправки?

2022-08-08 12:46 UTC, veselij commented on src/core/send_message.py
> +        f"[Открыть заявку на сайте]({request_data.consultation_url})\n"
Url заявки надо конструироват, там только id будет

2022-08-08 14:52 UTC, AkuLinker commented on src/run_webhook_api.py
> +    await send_new_message_notification(bot, request_data)
Так request_data проверяется в функции deserialize.  
Если там чего то нужного не будет или будет пусто, то выскочит исключение и сообщение не будет отправлено.

2022-08-08 14:53 UTC, AkuLinker commented on src/run_webhook_api.py
> +    await send_new_message_notification(bot, request_data)
А по поводу контекста. Я ничего в документации не нашёл (возможно плохо искал).  
Поэтому и обращался с вопросом в общий чат.

2022-08-08 15:14 UTC, AkuLinker commented on src/core/send_message.py
> +        f"[Открыть заявку на сайте]({request_data.consultation_url})\n"
Исправил

2022-08-08 16:03 UTC, veselij commented on src/run_webhook_api.py
> +    await send_new_message_notification(bot, request_data)
не выскочит исключение, мы их обрабатываем в deserialize, поэтому надо проверять на None

2022-08-08 16:12 UTC, veselij commented on src/run_webhook_api.py
> +    await send_new_message_notification(bot, request_data)
> А по поводу контекста. Я ничего в документации не нашёл (возможно плохо искал). Поэтому и обращался с вопросом в общий чат.

вот, что надо сделать, надо модифицировать send_message, так чтобы она принимала не context, а бота, тогда и ты ее сможешь использовать, но надо поправить ее вызовы в остальных местах кода, передавать в нее не context, а бота из контекста

2022-08-08 22:32 UTC, AkuLinker commented on src/run_webhook_api.py
> +    await send_new_message_notification(bot, request_data)
Сделал проверку на None. Если None, то отправка сообщения игнорируется.  
Изменил функцию send_message, как предложено выше. Также поправил два места где эта функция вызывалась.

2022-08-09 08:11 UTC, veselij approved these changes

2022-08-09 08:13 UTC, merged