Reminder about overdue consultation after 1 hour
Studio-Yandex-Practicum/ask_nenaprasno_bot pull request #93
Opened 2022-08-09 15:34 UTC by knightsdd

2022-08-11 06:48 UTC, MatMerd requested changes

2022-08-11 06:48 UTC, MatMerd commented on src/bot.py
> +NAME_OVERDUE_REMINDER_JOB = "overdue_reminder"
У нас все константы находятся в отдельном модуле. Перенеси и эту туда пожалуйста. Название модуля включает в себя слово const

2022-08-11 06:48 UTC, MatMerd commented on src/jobs.py
> +DATETIME_FORMAT = "%Y-%m-%dT%H:%M:%S"
То же самое. Вынеси в константы и сделай нейминг более понятным. Когда эта константа будет лежать в модуле с другими константами, можно не понять, для каких целей этот формат даты

2022-08-11 06:48 UTC, MatMerd commented on src/jobs.py
> +        if due_time.date() == date.today():
Надо подумать, а возможна ли ситуация, когда время ответа на заявку истекает в 23:00 например. И тогда человеку придет напоминание об ИСТЕКШЕЙ заявке как о той, которая истекает.

2022-08-11 08:53 UTC, knightsdd commented on src/jobs.py
> +        if due_time.date() == date.today():
Я проанализировал еще раз алгоритм функций - всё должно работать правильно:

В полночь мы получим список всех заявок которые истекают сегодня, в том числе и ту, которая в 23:00 (или позже). Для каждой такой заявки будет создано задание: напомнить через час.
Если срок заявки не продлили (т.е. дата_время истечения будет меньше чем текущее значение минус 1 час) значит мы отправляем сообщение.
Значит если для заявки создана задача напомнить, то неважно будет это напоминание отправлено сегодня или завтра.

Если в поле due передается дата и время истечения заявки, то никаких проблем со статусом этой заявки быть не должно. Как это можно обсудить?

2022-08-11 08:53 UTC, knightsdd commented on src/bot.py
> +NAME_OVERDUE_REMINDER_JOB = "overdue_reminder"
будет сделано

2022-08-11 08:53 UTC, knightsdd commented on src/jobs.py
> +DATETIME_FORMAT = "%Y-%m-%dT%H:%M:%S"
будет сделано

2022-08-11 11:22 UTC, veselij requested changes

2022-08-11 11:22 UTC, veselij commented on src/jobs.py
> +        if due_time.date() == date.today():
эта проверка по идее не нужна, мы же от API получаем и так список только на сегодня

2022-08-11 11:22 UTC, veselij commented on src/jobs.py
> +                "[Открыть Trello](https://trello.com/)"
тут надо филтре по юзеру в трелло в ссылке сделать. поэтому надо еще 3им параметром в data передавать trello_name

2022-08-11 12:47 UTC, knightsdd commented on src/jobs.py
> +                "[Открыть Trello](https://trello.com/)"
могу сформировать такую ссылку: `https://trello.com/u/user12345678/cards`, будет открываться профиль пользователя на странице с карточками

2022-08-12 18:59 UTC, veselij requested changes

2022-08-12 18:59 UTC, veselij commented on src/constants/jobs.py
> +DATETIME_FORMAT_FOR_DUE_CONSULTATION = "%Y-%m-%dT%H:%M:%S"
а зачем его в константу выносить, формат api меняться не будет, лучше просто в функциях указать, точно не в файле jobs лежать

2022-08-12 18:59 UTC, veselij commented on src/constants/jobs.py
> +NAME_OVERDUE_REMINDER_JOB = "overdue_reminder"
а зачем префикс NAME. давай не называть их overdue, лучше daily_consulations_reminder_job

2022-08-12 18:59 UTC, veselij commented on src/jobs.py
> +async def check_and_send_reminder_about_overdue(context: CallbackContext) -> None:
вот видишь у тебя даже в названии 2 действия написано, это явный признак того, что надо разделить минимум на 2 функции. сейчас очень сложно прочитать эту функцию

2022-08-12 18:59 UTC, veselij commented on src/jobs.py
> +async def overdue_consult_reminder_job(context: CallbackContext) -> None:
daily_consulations_reminder_job. ну  вездке в переменных и api методах. так как у нас не overdue. по факту мы джобы на сегодня запрашиваем

2022-08-12 18:59 UTC, veselij commented on src/jobs.py
> +        time_remind = due_time + timedelta(hours=1)
можно в одну строку схлопнуть и таймдельту давай прокинем параметром через аргумент фунции так же как и функцию колбэка джбы check_and_send_reminder_about_overdue, чтобы в будущем мы могли использовать для разных субджоб

2022-08-12 18:59 UTC, veselij commented on src/jobs.py
> +            check_and_send_reminder_about_overdue,
вот эту через параметры прокинуть

2022-08-12 18:59 UTC, veselij commented on src/service/api_client/base.py
> +    async def get_overdue_consultation(self) -> list[OverdueConsultation]:
get_daily_consultations

2022-08-12 18:59 UTC, veselij commented on src/service/api_client/base.py
> +    async def get_due_consultation(self, consultation_id: int) -> DueConsultation:
get_consultation

2022-08-12 18:59 UTC, veselij commented on src/service/api_client/models.py
> +@dataclass
надо зафризить

2022-08-12 18:59 UTC, veselij commented on src/service/api_client/models.py
> +@dataclass
зафризить

2022-08-15 09:17 UTC, knightsdd commented on src/constants/jobs.py
> +DATETIME_FORMAT_FOR_DUE_CONSULTATION = "%Y-%m-%dT%H:%M:%S"
Данная константа используется в двух функциях, к тому же есть договоренность, что все константы мы выносим в отдельный модуль. Обсудили это замечание с Матвеем, решили оставить как есть.

2022-08-15 10:11 UTC, knightsdd commented on src/constants/jobs.py
> +NAME_OVERDUE_REMINDER_JOB = "overdue_reminder"
ok

2022-08-15 11:58 UTC, veselij requested changes

2022-08-15 11:58 UTC, veselij commented on src/bot.py
> +    bot_app.job_queue.run_daily(daily_consulations_reminder_job, time=time(0, 0), name=DAILY_CONSULTATIONS_REMINDER_JOB)
время лучше в конфиг вынести

2022-08-15 11:58 UTC, veselij commented on src/jobs.py
> +        'Посмотрите, как прошла ваша неделя  в *"Просто спросить"*\n'
а у тебя прехук работает? почему одинарная ковычка?

2022-08-15 11:58 UTC, veselij commented on src/constants/jobs.py
> +DATETIME_FORMAT_FOR_CONSULTATION = "%Y-%m-%dT%H:%M:%S"
точно тут не место. так как это файл для констан - джоб

2022-08-15 11:58 UTC, veselij commented on src/jobs.py
> +        'Посмотрите, как он прошел в *"Просто спросить"* 🔥\n\n'
опять одинарные

2022-08-15 11:58 UTC, veselij commented on src/jobs.py
> +        return False
можно сократить в одну строку, через or

2022-08-15 11:58 UTC, veselij commented on src/jobs.py
> +    if due_time > datetime.now() - timedelta(hours=1):
почему timedelta захардкодил. у нас там разные типы уведомдений будут, не писать же новую функцию для них

2022-08-15 11:58 UTC, veselij commented on src/jobs.py
> +async def daily_consulations_reminder_job(context: CallbackContext) -> None:
вот тут можно в параметрах передать функцию для джобы (которая сейчас send_reminder_about_overdue) и timedelta.
перед заведением job надо через functools.partial преапендить эти аргументы в daily_consulations_reminder_job

2022-08-15 11:58 UTC, veselij commented on src/run_webhook_api.py
> +# pylint: disable=W0703
надо на конкретной строке только отключить

2022-08-15 11:58 UTC, veselij commented on src/service/api_client/models.py
> +class OverdueConsultation:
почему overdue то, она же не истекла еще. просто Consultation

2022-08-15 11:58 UTC, veselij commented on src/service/api_client/models.py
> +class DueConsultation:
ConsultationDueDate

2022-08-15 12:03 UTC, veselij commented on src/jobs.py
> +                "[Открыть Trello](https://trello.com/)"
типа того надо
 f"\n[Открыть Trello](https://trello.com/{TRELLO_BORD_ID}/?filter=member:{username_trello}/?filter=overdue:true)\n\n"

2022-08-15 19:32 UTC, knightsdd commented on src/bot.py
> +    bot_app.job_queue.run_daily(daily_consulations_reminder_job, time=time(0, 0), name=DAILY_CONSULTATIONS_REMINDER_JOB)
Добавляем отдельную константу (DAYLY_COLLECT_CONSULTATIONS_TIME) в .env?

2022-08-15 19:34 UTC, knightsdd commented on src/jobs.py
> +        'Посмотрите, как прошла ваша неделя  в *"Просто спросить"*\n'
Похоже на автоматические исправления black, потому что я в чужой код не лез. Поверю что бы в следующем коммите такого не было.

2022-08-15 19:36 UTC, knightsdd commented on src/constants/jobs.py
> +DATETIME_FORMAT_FOR_CONSULTATION = "%Y-%m-%dT%H:%M:%S"
так вроде эта константа в джобах и используется, но если надо захардкодить, то я это сделаю.

2022-08-15 20:43 UTC, knightsdd commented on src/jobs.py
> +        return False
согласен

2022-08-15 20:44 UTC, knightsdd commented on src/jobs.py
> +async def daily_consulations_reminder_job(context: CallbackContext) -> None:
Спасибо, узнал про крутой инструмент functools.partial

2022-08-15 21:17 UTC, knightsdd commented on src/jobs.py
> +        'Посмотрите, как прошла ваша неделя  в *"Просто спросить"*\n'
Это действительно делает black. Подумаю как это можно исправить

2022-08-17 10:09 UTC, veselij approved these changes

2022-08-17 10:15 UTC, merged

2022-08-19 20:30 UTC, AntonZelinsky commented on src/jobs.py
> +        user_expired = await APIService().get_user_expired_consultations(telegram_id)
2 раза создаётся экземпляр класса, некритично, но зачем тратить на это время?

2022-08-19 20:30 UTC, AntonZelinsky commented on src/jobs.py
> +            "[Открыть заявку на сайте](https://ask.nenaprasno.ru/)\n\n"
Тут должна быть ссылка на саму консультацию и у нас для этого всё есть — домен и айди консультации. 
Правда, домен должен браться из конфига, так как у нас есть не одно, а целых 3 окружения

2022-08-19 20:30 UTC, AntonZelinsky commented on src/jobs.py
> +        'Посмотрите, как он прошел в *"Просто спросить"* 🔥\n\n'
Как линтеры вообще это пропускают? У нас на любимовке этой проблемы уже пол года не видел, хотя всегда много разработчиков и кто-то приходит, а кто-то уходит.

2022-08-19 20:30 UTC, AntonZelinsky commented on src/service/api_client/site_api_service.py
> +        except TypeError as error:
Правильнее не заворачивать в обработку ошибок попытку десериализовать данные, а перед этим проверить, что ответ от сервера был успешным и данные есть, тогда, не нужно ничего вообще заворачивать будет, так как данные всегда указанного формата будут. Если данные в апи поменяются, то и нечего их проглатывать, нужно падать с ошибками и всё. Но это, скорее, нереальный кейс.

2022-08-24 10:15 UTC, veselij commented on src/service/api_client/site_api_service.py
> +        except TypeError as error:
завел таску на рефакторинг