entry_points
Studio-Yandex-Practicum/ask_nenaprasno_bot pull request #97
Opened 2022-08-11 19:44 UTC by ainokyn

2022-08-12 16:33 UTC, veselij requested changes

2022-08-12 16:33 UTC, veselij commented on src/conversation/menu.py
> +dialogs_conversation = ConversationHandler(
а зачем переименовывать, это  же как было меню так и осталось. dialogs_conversation не добавляет информативности.
давай оставим menu_conversation, DIALOG_STATE переименуем в MENU_STATE, а внутри диалога menu_conversation MENU_STATE-> STATISTICS_STATE

2022-08-12 16:33 UTC, veselij commented on src/conversation/menu.py
> +dialogs_conversation = ConversationHandler(
CallbackQueryHandler(button_reaction_callback, pattern=callback_data.CALLBACK_STATISTIC_WEEK_COMMAND), надо удалить и обработчик тоже (он там ничего не делает и у нас нет запроса недельной статстики пользователем

2022-08-12 21:51 UTC, AntonZelinsky commented on src/conversation/menu.py
> +        MessageHandler(filters.Regex("Напишу свою таймзону сам"), callback=get_timezone_from_text_message_callback),
Зачем это? Какой-то лишний бесполезный и очень некрасивый шаг.(
Нужно сразу ожидать ввод часового пояса, либо нажатия на кнопку с таймзоной, либо шаринга локации. Всё.
Плюс, конверсейшен стал называться dialogs_conversation, что это значит? Раньше был меню, всё было просто и понятно, это вс относится к меню, но это...
И ввод тайм зоны не может быть в энтрипоинтах, так как это равносильно без состояния написать «Напишу свою тайм зону сам» или тайм зону и попадёт в обработчики этого события, а должно попадать только если было состояние установки тайм зон выбрано

2022-08-13 14:40 UTC, ainokyn commented on src/conversation/menu.py
> +        MessageHandler(filters.Regex("Напишу свою таймзону сам"), callback=get_timezone_from_text_message_callback),
1) нейминг для конверсейшн был повторно изменен на menu_conversation, после замечания от Александра.
2) По всему остальному есть вопросы, мы это обсуждали в слаке, но продублирую тут: на данный момент menu_conversation представляет собой машину состояний, которая объединяет в себе состояния меню и таймзоны. Изначально планировалась сделать отдельно timezone_conversation и menu_conversation их встроить в authorization_conversation. Но на моменте проработки этого варианта выяснилось. что между timezone_conversation и menu_conversation есть циклические зависимости (timezone_conversation надо включать MENU_STATE, поскольку после настройки таймзоны мы должны вернуть состояния меню, а в свою очередь при нажатии кнопки из menu_conversation возвращается TIMEZONE_STATE). Тогда было предложено объединить все это в одну машину  с тремя точками входа: одна для входа в меню (/menu) и две для входа в timezone (по фразе и по геолокации). Но возник глобальный вопрос по entry_points для перехода в timezone. По идее entry_points для перехода в состояние установки timezone должна быть функция get_timezone, но эта функция просто вызывает клавиатуру с KeyboardButton из-за чего не за что "зацепиться"  для входа в состояние установки таймзон. Поэтому и было сделано так некрасиво.
Из чего возникли следующие вопросы:
1) Оставлять ли объединенную машину для timezone и menu или разделить?
2) Как лучше решить проблему с  entry_points для timezone?
3)"Нужно сразу ожидать ввод часового пояса, либо нажатия на кнопку с таймзоной, либо шаринга локации." где это нужно ожидать?
4) Что же в итоге надо получить (3 машины состояний для меню, таймзон и авторизации не взирая на проблему с цикличность, 2 машины авторизация и объединенная машина или вообще что-то другое и смысл задачи был не в этом)?

2022-08-14 13:44 UTC, AntonZelinsky commented on src/conversation/menu.py
> +        MessageHandler(filters.Regex("Напишу свою таймзону сам"), callback=get_timezone_from_text_message_callback),
МОжно объединить, можно сделать разные, с циклическими конверсейченами проблем не должно быть, они просто переподключаются в нужном месте и всё. МОжно глянуть [пример тут](https://github.com/ProCharity/ProCharity_bot/blob/develop/bot/charity_bot.py). 
По времени уже обсуждали сотни раз! Должно быть шаринг локации через серую кнопку, возможность ввести сообщение вручную и кнопка использовать таймзону +3 по умолчанию. Если это супер тяжело, то упростите и сделайте один из этих вариантов, а потом добавятся другие, я правда не помнимаю, что тут сложного, это три очень простых действия.

2022-08-14 14:46 UTC, veselij commented on src/conversation/menu.py
> +        MessageHandler(filters.Regex("Напишу свою таймзону сам"), callback=get_timezone_from_text_message_callback),
Нельзя в телеграмм отправить и кнопку и Инлайн кнопку. Можно только после сообщения с обычной кнопкой отправить ещё одно сообщение с каким то текстом и к нему уже добавить эту Инлайн кнопку с дефолт +3 что в итоге становится ещё более громоздко.

2022-08-17 09:33 UTC, veselij requested changes
привет,
практически то, что надо, какой-то плавающий баг в п1. так как из меню все работает. скорее всего нет входа в диалог таймзоны.

1) при старте бота - кнопки установки таймзоны не работают.
2) кнопки дефолтной таймзоны и настройки - надо сделать друг под другом, так как с телефона текст не влезает и не понятно, что они значат
3) в меню кнопку установки таймзоны надо сделать последней
4) возможно, лучше не присылать меню, если пользователь из меню меняет тайм-зону. меню должно прихоить только при установке тайм-зоны при начальной настройке бота

2022-08-17 16:29 UTC, ainokyn commented
По багу: судя по всему он появлялся на устройствах, на которых никогда раньше не работал бот, я пофиксила, но все равно надо проверить.
Кнопки переставила, но на маленьких экранах смартфона кнопки все равно не видны адекватно, поэтому немного сократила текст, но "Москва" все равно не помещается.

2022-08-17 18:01 UTC, AntonZelinsky commented
Приложите скрины, пожалуйста, как слово москва может не поместиться не понимаю.

2022-08-17 19:25 UTC, veselij commented
![image](https://user-images.githubusercontent.com/23584808/185224975-0f1183ea-95d6-43ec-af84-c73ee2fdef20.png)
надо просто текст поменять, типа на первой кнопке "установить +3 Москва", а на второй "другую таймзону". Ну или надо что-то придумать. в целом мне сейчас все нравится

2022-08-19 08:09 UTC, veselij approved these changes

2022-08-19 08:09 UTC, merged