Test auth, timezone, active and edit 4 modules
Studio-Yandex-Practicum/ask_nenaprasno_bot pull request #99
Opened 2022-08-17 08:29 UTC by sdvkam

Тестирование бота

1. После внесенных изменений
2. Пока доктор не создан - система авторизации работает как ожидается
3. Когда создан - авторизация проходит как ожидалось
4. Таймзону можно установить как и ожидалось
5. Чистый запуск бота
    1. Предварительно удален файл: bot_persistence_file
    2. Не работает экранное меню, появляющееся после строчки: А еще с помощью ….
        1. на нажатие кнопок ничего не происходит на экране 
        2. функции для вывода информации не задействуются
    3. Если открыть всплывающее меню слева-внизу и нажать: Показать список возможных …,
    4. то начинает работать как экранное, так и всплывающее меню и информация выдается
6. функция запроса месячной статистики работает 
7. функция: активные заявки - работает
8. функция: просроченные заявки - не знаю как тестировать

2022-08-17 11:26 UTC, veselij requested changes

2022-08-17 11:26 UTC, veselij commented on src/conversation/menu.py
> +            num += 1
ой-ой, антипатен в питоне. надо через for num, consultation enumerate(consultations_list) делать

2022-08-17 11:26 UTC, veselij commented on src/conversation/menu.py
> +            num += 1
аналогично

2022-08-17 11:26 UTC, veselij commented on src/service/api_client/site_api_service.py
> +            return None if exp_consultations is None else UserExpiredConsultations.from_dict(exp_consultations)
а зачем этот if у тебя же и так вывалится TypeError и вернется None

2022-08-17 18:12 UTC, sdvkam commented on src/service/api_client/site_api_service.py
> +            return None if exp_consultations is None else UserExpiredConsultations.from_dict(exp_consultations)
exp_consultations может прийти в двух вариантах:
1. словарик
2. None
   - результат ошибки в функции: __get_json_data
   - эта ошибка будет записана в логи

Если мы уберём if и exp_consultations придёт как None возникнет ошибка и в этой функции, как результат предыдущей ошибки. Она будет записана в логи. Получим на одну ошибку две записи в логах.
Это наверное более информативно, но может и сбивать с толку, в какой момент ошибка возникла.
Вопрос, риторический наверное:
  - Чистота кода + больше информации vs. одна ошибка - одна запись в логах?
Вопрос практический:
  - может лучше ошибку TypeError тогда описать отдельно?

2022-08-18 08:29 UTC, sdvkam commented on src/service/api_client/site_api_service.py
> +        except (AttributeError, KeyError) as error:
TypeError вообще никак не проявляются

2022-08-19 08:04 UTC, veselij approved these changes

2022-08-19 08:07 UTC, merged